(function(g){var window=this;var tZ=function(a){a.i||(a.i=new g.Bo,g.G(a,a.i));return a.i},uZ=function(a,b){var c=g.V(a.app);
b.event="iv";a.isFullscreen()&&(b.fs=1);b.ux=1;c=c.C;if(c.i){c=c.i;var d={};d.rt=g.pD(c.g).toFixed(3);g.Ta(d,g.qD(c.g));var e=c.g.xb,f=c.g.videoData;e={ns:e.V,html5:"1",el:g.JB(f),ps:e.playerStyle,fexp:e.experiments.experimentIds.join(",")||void 0,feature:f.ls||f.Ei||void 0,ctrl:f.ue||void 0,ytr:f.we||void 0,list:f.playlistId};g.MB(f)&&(e.autoplay="1");f.subscribed&&(e.subscribed=f.subscribed);g.Ta(d,e);delete d.fexp;g.Ta(d,b);d=g.oq(c.g.xb.C+"player_204",d);g.BD(c,d,void 0)}},vZ=function(a){a.N("cardstatechange",
a.ud()&&a.De()?1:0)},wZ=function(a){var b=g.Lh(a);
a=g.Sh(a);return new g.nh(b.x,b.y,a.width,a.height)},xZ=function(a,b){var c=a.style;
"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*Number(b)+")")},yZ=function(a){return"none"!=a.style.display},zZ=function(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);
var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return+e},Nna=function(a){var b=g.Fh(a,"fontSize");
var c=(c=b.match(Kna))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.Md){if(String(c)in Lna)return zZ(a,b);if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in Mna)return a=a.parentNode,c=g.Fh(a,"fontSize"),zZ(a,b==c?"1em":b)}c=g.Rd("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.Xd(c);return b},Ona=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Ck&&a.dataset){if(g.kc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.fd("pollChoiceIndex"))},CZ=function(a){a=g.Ra(a);
delete AZ[a];g.Yb(AZ)&&BZ&&BZ.stop()},DZ=function(){BZ||(BZ=new g.M(function(){Pna()},20));
var a=BZ;a.isActive()||a.start()},Pna=function(){var a=(0,g.H)();
g.Lb(AZ,function(b){EZ(b,a)});
g.Yb(AZ)||DZ()},FZ=function(a,b){g.sf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.D;this.state=b.g},GZ=function(a,b,c,d){g.Wn.call(this);
if(!g.Ma(a)||!g.Ma(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.F=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.D=0;this.A=null},EZ=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.D=1E3/(b-a.A);a.A=b;HZ(a,a.progress);1==a.progress?(a.g=0,CZ(a),a.Zc(),a.l()):1==a.g&&a.Or()},HZ=function(a,b){g.Oa(a.C)&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.F[c]-a.i[c])*b+a.i[c]},IZ=function(a,b,c,d,e){GZ.call(this,b,c,d,e);
this.element=a},JZ=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
IZ.call(this,a,b,c,d,e)},Qna=function(a){return Math.pow(a,3)},Rna=function(a){return 3*a*a-2*a*a*a},KZ=function(a){g.D.call(this);
this.i=a||window;this.g=[]},Sna=function(a,b,c,d){c=(0,g.x)(c,d||a.i);
b=g.Wr(b,"change",c,"iv-card-poll-choice-input");a.g.push(b)},LZ=function(a,b){(0,g.z)(b,function(c){g.es("visualElementShown",{csn:a,
ve:g.Ls(c),eventType:4},g.js,void 0,void 0)})},MZ=function(a,b){(0,g.z)(b,function(c){g.es("visualElementHidden",{csn:a,
ve:g.Ls(c),eventType:8},g.js,void 0,void 0)})},NZ=function(a,b){g.Sf.call(this);
this.Tj=a;this.Yp=b;this[g.uf]=!1},SZ=function(a,b,c,d){NZ.call(this,a,b);
a=this.Yp;b=this.ga();c?(b.setAttribute("stroke",c.i),b.setAttribute("stroke-opacity",1),c=c.g,g.Fa(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/Tna(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.Yp;a=this.ga();if(d instanceof OZ)a.setAttribute("fill",d.F),a.setAttribute("fill-opacity",d.H);else if(d instanceof PZ){b="lg-"+d.u+"-"+d.C+"-"+d.A+"-"+d.D+"-"+d.g+"-"+d.i;var e=b in c.g?c.g[b]:null;if(!e){e=QZ(c,"linearGradient",{x1:d.u,y1:d.C,
x2:d.A,y2:d.D,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.g;g.Ha(d.l)&&(f+=";stop-opacity:"+d.l);f=QZ(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.i;g.Ha(d.o)&&(f+=";stop-opacity:"+d.o);d=QZ(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=RZ(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},m_=function(){},A_=function(a,b){NZ.call(this,a,b)},B_=function(){this.Ta=[];
this.Ca=[];this.Sd=[]},C_=function(a,b,c,d){var e=a.xd[0]-b*Math.cos(g.td(d))+b*Math.cos(g.td(d+90)),f=a.xd[1]-c*Math.sin(g.td(d))+c*Math.sin(g.td(d+90));
a.Ta.push(3);a.Ca.push(1);a.Sd.push(b,c,d,90,e,f);a.Wk=!1;a.xd=[e,f]},Vna=function(a,b){for(var c=a.Sd,d=0,e=0,f=a.Ta.length;e<f;e++){var k=a.Ta[e],l=Una[k]*a.Ca[e];
b(k,c.slice(d,d+l));d+=l}},D_=function(a,b,c,d){SZ.call(this,a,b,c,d)},E_=function(a,b){this.g=a;
this.i=b},F_=function(a,b,c,d,e){g.ho.call(this,e);
this.width=a;this.height=b;this.l=c||null;this.I=d||null},Tna=function(a){var b=a.Ij();
return b?b.width/(a.l?new g.wd(a.l,a.I):a.Ij()).width:0},PZ=function(a,b,c,d,e,f,k,l){this.u=a;
this.C=b;this.A=c;this.D=d;this.g=e;this.i=f;this.l=g.Ea(k)?k:null;this.o=g.Ea(l)?l:null},OZ=function(a,b){this.F=a;
this.H=null==b?1:b},G_=function(a,b){NZ.call(this,a,b)},H_=function(a,b,c,d){SZ.call(this,a,b,c,d)},I_=function(a,b,c,d,e){F_.call(this,a,b,c,d,e);
this.g={};this.R=g.Od&&!g.od(526);this.P=new g.an(this)},QZ=function(a,b,c){a=a.M.g.createElementNS("http://www.w3.org/2000/svg",b);
if(c)for(var d in c)a.setAttribute(d,c[d]);return a},J_=function(a,b,c,d){b=QZ(a,"path",{d:Wna(b)});
c=new H_(b,a,c,d);a.o.ga().appendChild(c.ga())},Wna=function(a){var b=[];
Vna(a,function(c,d){switch(c){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var e=d[3];b.push("A",d[0],d[1],0,180<Math.abs(e)?1:0,0<e?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},RZ=function(a,b,c){if(b in a.g)return a.g[b];
var d="_svgdef_"+Xna++;c.setAttribute("id",d);a.g[b]=d;a.C.appendChild(c);return d},Yna=function(){K_||(K_=new g.Fg(400),K_.start());
return K_},L_=function(a,b){function c(l){return l.baseUrl}
function d(l){if(l){var m=l.simpleText;if(m)return m;if(l.runs)return(0,g.B)(l.runs,function(n){return n.text}).join("")}}
function e(l){if(l){var m=[],n=l.videoId;n&&m.push("v="+n);(n=l.playlistId)&&m.push("list="+n);(l=l.startTimeSeconds)&&m.push("t="+l);return"/watch?"+m.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.B)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;a.trackingParams&&(f.visualElement=g.Ks(a.trackingParams));var k=(0,g.B)(a.elements||[],function(l,m){var n=l.endscreenElementRenderer;if(!n)return null;var p={},r=n.style,u=n.endpoint||{};p.id="element-"+m;p.type=r;p.title=d(n.title);p.metadata=d(n.metadata);p.callToAction=d(n.callToAction);p.lv=n.image;p.left=parseFloat(n.left);p.width=parseFloat(n.width);p.top=parseFloat(n.top);p.aspectRatio=
parseFloat(n.aspectRatio);p.startMs=parseInt(n.startMs,10);p.endMs=parseInt(n.endMs,10);p.clickUrls=(0,g.B)(u.loggingUrls||[],c);p.Dl=g.Tb(n,"title","accessibility","accessibilityData","label");p.impressionUrls=(0,g.B)(n.impressionUrls||[],c);p.VD=(0,g.B)(n.hovercardShowUrls||[],c);p.Xb={itct:n.trackingParams};p.visualElement=g.Ks(n.trackingParams);if("VIDEO"==r)p.targetUrl=u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.Cm=!1,p.ao=b,p.videoDuration=d(n.videoDuration);else if("PLAYLIST"==r)p.targetUrl=
u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.Cm=!1,p.ao=b,p.playlistLength=d(n.playlistLength);else if("CHANNEL"==r){if(r=g.Tb(u,"browseEndpoint","browseId"))p.channelId=r,p.targetUrl="/channel/"+r;p.Cm=!1;p.ao="new";p.isSubscribe=!!n.isSubscribe;if(p.isSubscribe){a:{if(r=n.hovercardButton)if(r=r.subscribeButtonRenderer){u=d(r.unsubscribedButtonText);var A=d(r.subscribedButtonText);if(r.subscribed){var C=d(r.subscriberCountWithUnsubscribeText);var E=d(r.subscriberCountText)}else C=d(r.subscriberCountText),
E=d(r.subscriberCountWithSubscribeText);var F=null;if(n.signinEndpoint&&(F=g.Tb(n,"signinEndpoint","webNavigationEndpointData","url"),!F)){n=void 0;break a}if(u&&(A||F)){n={subscribed:r.subscribed,subscribeText:u,subscribeCount:C,unsubscribeText:A,unsubscribeCount:E,enabled:r.enabled,signinUrl:F,classic:n.useClassicSubscribeButton};break a}}n=void 0}p.subscribeButton=n}else p.subscribersText=d(n.subscribersText)}else"WEBSITE"==r&&(p.targetUrl=g.Tb(u,"urlEndpoint","url"),p.Cm=!0,p.ao="new",p.iconUrl=
n.icon.thumbnails[0].url);return p});
f.elements=(0,g.Yd)(k,function(l){return!!l});
return f},M_=function(a){g.zK.call(this,a);
this.i=null;this.H=!1;this.o=null;this.g={};this.C={};this.A=this.l=null;this.I=[];a=g.X(a);this.P=g.Fy(a)||g.Hy(a);this.FA=!0;this.D=0;this.F=new g.Mn;this.u=new g.rs(this);g.G(this,this.u);this.u.K(this.player,g.ND("creatorendscreen"),this.QE);this.u.K(this.player,"crx_creatorendscreen",this.RE);this.u.K(this.player,"resize",this.Wa);this.u.K(window,"focus",this.LL);this.load();var b=g.Sd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.pf(this,function(){g.Xd(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},N_=function(a){return a.player.getVideoData().Nb?"current":a.P?"new":"current"},O_=function(a){return"creator-endscreen-editor"===a},P_=function(a,b){g.hK(a.player,"creatorendscreen");
a.l&&(a.l.dispose(),a.l=null,a.A.dispose(),a.A=null);for(var c in a.g)a.g[c].dispose();a.g={};a.C={};0<a.I.length&&(a.I.forEach(function(l){l.dispose()}),a.I.length=0);
a.D=0;if((a.i=b)&&b.elements){Zna(a);c=[];var d=new g.KD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.X(a.player).g||(a.l=new g.W({B:"div",G:"ytp-ce-shadow"}),g.lK(a.player,a.l.element,4),a.A=new g.WP(a.l,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=$na(a,e);a.g[e.id]=f;a.C[e.id]=e;g.lK(a.player,f.element,4);var k=new g.KD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);aoa(a,f,e)}g.eK(a.player,
c);a.Wa()}},Zna=function(a){var b=g.$s(),c=g.at();
c&&b&&a.i.visualElement&&g.Ms(c,b,[a.i.visualElement],void 0)},$na=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={B:"div",W:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":b.Dl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:Q_(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:R_(a,b.targetUrl),tabindex:"-1"},J:[{B:"div",W:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Nn(a.F,b.title||"")},T:b.title},{B:"div",G:"ytp-ce-video-duration",T:b.videoDuration}]}]};
c=new g.W(c);break;case "PLAYLIST":c={B:"div",W:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":b.Dl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:Q_(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:R_(a,b.targetUrl),tabindex:"-1"},J:[{B:"div",W:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Nn(a.F,b.title||"")},T:b.title},{B:"div",G:"ytp-ce-playlist-count",J:[{B:"div",
G:"ytp-ce-playlist-icon"},{B:"div",G:"ytp-ce-playlist-count-text",T:b.playlistLength}]}]}]};c=new g.W(c);break;case "CHANNEL":c={B:"div",W:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":b.Dl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",J:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",
J:[{B:"div",G:"ytp-ce-expanding-overlay-body",J:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",J:[{B:"a",W:["ytp-ce-channel-title","ytp-ce-link"],L:{href:R_(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Nn(a.F,b.title||"")},T:b.title},b.subscribeButton?{B:"div",G:"ytp-ce-subscribe-container",J:[{B:"div",G:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{B:"div",G:"ytp-ce-channel-subscribers-text",T:b.subscribersText}:"",b.metadata?{B:"div",W:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],T:b.metadata}:""]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:Q_(b)}]};c=new g.W(c);var d=g.Fd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.J(d,"ytp-ce-subscribe-button");if(g.X(a.player).g){var e=null;var f=b.Xb.itct}else e="endscreen",f=null;e=new g.PV(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.I.push(e)}break;case "WEBSITE":c={B:"div",W:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":b.Dl||"","aria-hidden":"true"},J:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",J:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",J:[{B:"div",G:"ytp-ce-expanding-overlay-body",
J:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",J:[{B:"div",G:"ytp-ce-website-title",L:{dir:g.Nn(a.F,b.title||"")},T:b.title},{B:"div",G:"ytp-ce-website-metadata",T:b.metadata},{B:"a",W:["ytp-ce-website-goto","ytp-ce-link"],L:{href:R_(a,b.targetUrl),target:"_blank",tabindex:"-1"},T:b.callToAction}]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:Q_(b)},{B:"div",G:"ytp-ce-expanding-icon",L:S_(b.iconUrl)}]},c=new g.W(c)}b.g&&g.J(c.element,"ytp-ce-placeholder");return c},Q_=function(a){if(a.lv)var b=
a.lv.thumbnails;
return S_(b?b[b.length-1].url:null)},S_=function(a){return a?{style:"background-image: url("+a+")"}:{}},aoa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ca("mouseenter",(0,g.x)(a.Zq,a,b,c));b.ca("mouseleave",(0,g.x)(a.Tr,a,b,c));g.X(a.player).g||b.ca("click",(0,g.x)(function(l){g.J(l.element,"ytp-ce-element-hover")},a,b));
b.ca("click",(0,g.x)(a.Ly,a,c));b.ca("keypress",(0,g.x)(a.Ly,a,c));b.ca("focus",(0,g.x)(function(l,m){this.Zq(l,m)},a,b,c));
b.ca("blur",(0,g.x)(function(l,m){this.Tr(l,m)},a,b,c));
b.ca("touchstart",(0,g.x)(a.Zq,a,b,c));var f=g.Hd("ytp-ce-expanding-overlay-hider",b.element);f&&b.K(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Tn(b.element,"ytp-ce-element-hover");g.Tn(b.element,"ytp-ce-force-expand")});
b.ca("keydown",(0,g.x)(function(l,m){this.FA=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.D+=n;0<this.D?(g.J(l.element,"ytp-ce-force-expand"),T_(this,m.id,!0)):(g.Tn(l.element,"ytp-ce-force-expand"),g.Tn(l.element,"ytp-ce-element-hover"),T_(this,m.id,!1))},a,b,c);
a=(0,g.x)(function(l,m){m&&(l.ca("blur",function(){yZ(m)&&this.FA&&m.focus()}),l.K(m,"focus",d),l.K(m,"blur",e))},a,b);
a(g.Hd("ytp-sb-subscribe",b.element));a(g.Hd("ytp-sb-unsubscribe",b.element));b.ca("focus",d);b.ca("blur",e)},R_=function(a,b){var c=g.X(a.player);
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.kz(c)+b}else return"";return b},T_=function(a,b,c){a.l&&(c?a.A.show():a.A.hide());
for(var d in a.g)d!=b&&g.K(a.g[d].element,"ytp-ce-element-shadow-show",c)},U_=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||O_(g.X(a.player).playerStyle))c&&c();else{b=boa(a,b);var e=0,f=!1,k=new g.M(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.$q(b[a],d)}},V_=function(a,b,c){U_(a,b.clickUrls,c);
(a=g.at())&&b.Cm&&g.Os(a,b.visualElement)},boa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(coa(b[e],c));return d},coa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},W_=function(a){return g.Ma(a)&&a.length?a[0]:a},X_=function(a){var b=/.+/;
return g.Fa(a)&&null!=b&&null!=a&&a.match(b)?a:""},Y_=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},Z_=function(a){return g.Fa(a)?a:""},$_=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},a0=function(a,b){return"true"==a||"false"==a?"true"==a:b},b0=function(a,b){return g.Fa(a)?parseFloat(a):b},c0=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.qd(a,b,c);if(a>=b&&a<=c)return a}return e},doa=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.z)(a,function(d){d=parseFloat(d);0>d&&(c=-c);b=60*b+Math.abs(d)});
return c*b},d0=function(a,b){if(null==a)return null;
if(g.Na(a)){var c=[];(0,g.z)(a,function(e){(e=b(e))&&c.push(e)});
return c}var d=b(a);return d?[d]:[]},eoa=function(a){function b(c){return null!=c&&!isNaN(c)}
return(a=a?new g.kh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},foa=function(a){function b(c){return(0,g.Yd)(c.split(/ +/),function(d){return""!=d})}
return null==a?[]:b(a)},goa=function(a){this.externalId=a},hoa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.g=d},e0=function(a){if(!a)return null;
var b=g.Dc(Z_(a.value));b=g.Ac(b);if(!b)return null;var c=$_(a.target,ioa,"current");return null==c?null:new hoa(b,c,a0(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},f0=function(a){return a.value?a.value:null},joa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},moa=function(a){if(!a)return null;
var b=$_(a.type,koa),c=$_(a.trigger,loa),d=W_(a.url);d=e0(d?d:null);a=W_(a.subscribeData);var e=a?a:null;e?(a=Z_(e.external_user_id),e=Z_(e.subscription_token),a=a&&e?new goa(a):null):a=null;return b?new joa(b,c,d,a):null},g0=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},h0=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},i0=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.Xi=c;this.l=d;this.t=e;this.u=f;this.A=k;this.C=l;this.o=m;this.i=n;this.g=p},j0=function(a,b){if(!a)return null;
var c=b0(a.x,0),d=b0(a.y,0),e=b0(a.w,0),f=b0(a.h,0),k=doa(a.t),l=b0(a.d,0),m=b0(a.px,0),n=b0(a.py,0),p=b0(a.scaleSlope,1),r=b0(a.scaleSlopeX,p);p=b0(a.scaleSlopeY,p);var u=$_(a.scaleDimension,noa,"xy");return b(c,d,e,f,k,l,m,n,r,p,u)},m0=function(a,b){var c=k0(b,l0(a,new g.nh(a.x,a.y,a.Xi,a.l),b.g)),d=b.g,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.qd(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.qd(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},l0=function(a,b,c){var d=a.A,e=a.C,f=a.g?a.g:"xy",k=g0(c,a.o,f);
a=h0(c,a.i,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.nh(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},n0=function(a){return a?j0(a,function(b,c,d,e,f,k,l,m,n,p,r){return new i0(b,c,d,e,f,k,l,m,n,p,r)}):null},o0=function(a,b){this.g=a;
this.i=b||null},k0=function(a,b){var c=a.i?m0(a.i,new o0(a.g)):a.g;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.ud?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Ha(c)&&(d.top+=c));return d},p0=function(a,b,c,d,e,f,k,l,m,n,p,r,u){i0.call(this,a,b,c,d,e,l,m,n,p,r,u);
this.D=f;this.F=k},ooa=function(a){if(!a)return null;
var b=b0(a.sx,0),c=b0(a.sy,0);return j0(a,function(d,e,f,k,l,m,n,p,r,u,A){return new p0(d,e,f,k,l,b,c,m,n,p,r,u,A)})},poa=function(a,b,c,d,e,f,k,l,m,n,p,r,u,A){this.i=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.g=e;this.A=f;this.l=k;this.textAlign=l;this.textSize=m;this.o=n;this.padding=p;this.effects=r;this.cornerRadius=u;this.u=A},q0=function(a){if(!a)return null;
var b=Y_(a.fgColor,"#1A1A1A"),c=Y_(a.bgColor,"#FFF"),d=Y_(a.borderColor,"#000"),e=c0(a.borderWidth,0,5,!1,0),f=c0(a.bgAlpha,0,1,!1,.8),k=Y_(a.highlightFontColor,"#F2F2F2"),l=c0(a.highlightWidth,0,5,!1,3),m=Z_(a.textAlign),n=c0(a.textSize,3.3,30.1,!0,3.6107),p=Z_(a.fontWeight),r=eoa(a.padding),u=foa(a.effects),A=c0(a.cornerRadius,0,10,!0,0);a=W_(a.gradient);if(a=a?a:null){var C=c0(a.x1,0,100,!0,0),E=c0(a.y1,0,100,!0,0),F=c0(a.x2,0,100,!0,100),L=c0(a.y2,0,100,!0,100),aa=Y_(a.color1,"#FFF"),qa=Y_(a.color2,
"#000");a=new qoa(C,E,F,L,aa,qa,c0(a.opacity1,0,100,!0,100),c0(a.opacity2,0,100,!0,0))}else a=null;return new poa(b,c,d,e,f,k,l,m,n,p,r,u,A,a)},qoa=function(a,b,c,d,e,f,k,l){this.l=a;
this.u=b;this.o=c;this.A=d;this.g=e;this.i=f;this.C=k;this.D=l},roa=function(a,b,c,d){this.type=a;
this.i=b;this.g=c;this.l=d},toa=function(a){if(!a)return null;
var b=$_(a.type,soa,"rect"),c=d0(a.rectRegion,n0),d=d0(a.anchoredRegion,ooa);a=d0(a.shapelessRegion,n0);return new roa(b,c,d,a)},r0=function(a){return a.i&&a.i.length?a.i[0]:a.g&&a.g.length?a.g[0]:a.l&&a.l.length?a.l[0]:null},uoa=function(a,b){this.i=a;
this.g=b},voa=function(a,b){this.state=a;
this.ref=b},s0=function(a){if(!a)return null;
var b=$_(a.state,woa);a=X_(a.ref);return b?new voa(b,a):null},xoa=function(a,b,c,d){this.g=a||[];
this.l=b||[];this.o=c;this.i=d;this.value=!1},yoa=function(a){if(!a)return null;
var b=d0(a.condition,s0),c=d0(a.notCondition,s0),d=a0(a.show_delay,!1);a=a0(a.hide_delay,!1);return b||c?new xoa(b,c,d,a):null},zoa=function(a,b,c){(0,g.z)(a.g,g.Sa(b,!1),c);
(0,g.z)(a.l,g.Sa(b,!0),c)},t0=function(a,b,c,d,e,f,k,l,m,n,p,r,u,A){this.id=a;
this.author=b;this.type=c;this.style=d;this.l=e;this.segment=f;this.i=k||[];this.A=l||[];this.g=m;this.u=n;this.o=p;this.data=r;this.bb=u;this.itct=A},Coa=function(a){if(!a)return null;
var b=X_(a.id),c=X_(a.author),d=$_(a.type,Aoa),e=$_(a.style,u0),f=Z_(W_(a.TEXT)),k=Z_(a.data);k=0!=k.length?JSON.parse(k):{};var l=W_(a.segment);var m=l?l:null;m?(X_(m.timeRelative),l=X_(m.spaceRelative),l=(m=d0(m.movingRegion,toa))?new uoa(l,m):null):l=null;m=d0(a.action,moa);var n=d0(a.trigger,yoa),p=W_(a.appearance);(p=q0(p?p:null))||(p=q0({}));var r=$_(a.coordinate_system,Boa,"video_relative"),u=a0(a.closeable,!0),A=Z_(a.log_data);a=Z_(a.itct);return b&&d?new t0(b,c,d,e,f,l,m,n,p,r,u,k,A,a):null},
w0=function(a){return v0(a,function(b){return"click"==b.trigger})},v0=function(a,b){return(0,g.Mj)(a.i,b,void 0)},Doa=function(a,b,c){(0,g.z)(a.i,b,c)},Eoa=function(a,b){return g.Ya(a.i,b,void 0)},x0=function(a,b,c){(0,g.z)(a.A,b,c)},Foa=function(a,b){(0,g.B)(a.A,b,void 0)},z0=function(a){return(a=y0(a))?r0(a):null},y0=function(a){a.segment?(a=a.segment,a=a.g.length?a.g[0]:null):a=null;
return a},A0=function(a,b){var c=z0(a);
return c&&b?h0(b,c.i,c.g?c.g:"xy"):1},C0=function(a,b,c){this.g={};
this.l=!1;this.u="ivTrigger:"+a;this.i=c;zoa(b,function(d,e){var f=B0(e.state,e.ref);this.i.subscribe(f,(0,g.x)(this.o,this,f,d));this.g[f]=d},this)},B0=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},D0=function(){this.g=!1;
this.u=this.i=null},E0=function(a,b,c){a.i?(a.i.setSize(b,c),a.i.clear()):(b=new I_(b,c,void 0,void 0,void 0),a.i=b,a.i.fq(),a.u=g.Rd("DIV"),a.u.appendChild(a.i.ga()));
return a.i},F0=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Lb(b,function(f,k){d.setAttribute(k,f)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},G0=function(a,b){var c=g.go(g.fo.getInstance());
b.setAttribute("result",c);a.appendChild(b);return c},Goa=function(a,b){var c=G0(a,F0("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=G0(a,F0("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},F0("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=G0(a,F0("feComposite",{"in":c,in2:b,operator:"in"}));return G0(a,F0("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},Hoa=function(a,b){var c=G0(a,F0("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=G0(a,F0("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=G0(a,F0("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=G0(a,F0("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=G0(a,F0("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=G0(a,F0("feComposite",{operator:"out","in":c,in2:d}));return G0(a,F0("feComposite",{operator:"over","in":b,in2:c}))},Ioa=function(a,b){return b},Joa=function(a){var b=
F0("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.z)(a,function(d){a:{switch(d){case "bevel":d=Goa;break a;case "dropshadow":d=Hoa;break a}d=Ioa}c=d(b,c)});
return b},Koa=function(a){a=(0,g.Yd)(a,function(b){return b in H0});
g.rb(a,function(b,c){return H0[b]-H0[c]});
return a},Loa=function(a){return g.Ya(a,function(b){return"dropshadow"==b})?new g.kh(0,7,7,0):new g.kh(0,0,0,0)},I0=function(a,b,c){var d=new B_;
d.moveTo(a.left+b+c,a.top+c);d.Zb(a.left+a.width-b-c,a.top+c);C_(d,b,b,-90);d.Zb(a.left+a.width-c,a.top+a.height-b-c);C_(d,b,b,0);d.Zb(a.left+b+c,a.top+a.height-c);C_(d,b,b,90);d.Zb(a.left+c,a.top+b+c);C_(d,b,b,180);d.close();return d},J0=function(a,b,c,d){var e=a.u;
e?a=new PZ(e.l*b/100,e.u*c/100,e.o*b/100,e.A*c/100,e.g,e.i,e.C,e.D):(b=a.g,a=new OZ(a.bgColor,d?Math.max(b,.9):b));return a},K0=function(a,b){var c=g.oh(a),d=Loa(b);
g.Pa(d)?(c.top-=d.top,c.right+=d.right,c.bottom+=d.bottom,c.left-=d.left):(c.top-=d,c.right+=Number(void 0),c.bottom+=Number(void 0),c.left-=Number(void 0));return new g.nh(c.left,c.top,c.right-c.left,c.bottom-c.top)},L0=function(a,b,c){if(c.length&&(b=g.Fd(document,"g",void 0,b),b.length)){var d=Koa(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.g?a.g[c]:null;e?a=e:(d=Joa(d),a=0<d.childNodes.length?RZ(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},M0=function(){D0.call(this);
this.o=0},Moa=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},N0=function(){D0.apply(this,arguments)},O0=function(){D0.apply(this,arguments)},P0=function(){M0.apply(this,arguments)},Q0=function(a,b,c,d,e){g.D.call(this);
this.g=a;this.R=b;this.A=c;this.X=d;this.Z=e;this.F=!1;this.aa=new KZ(this);g.G(this,this.aa);this.M=this.u=this.C=this.P=this.i=null;this.V=!1;this.ba=this.H=this.I=null;this.qn=new g.Al(this.xD,100,this);g.G(this,this.qn);this.D=new g.M(this.yw,500,this);g.G(this,this.D);this.O=this.l=this.o=null},Noa=function(a,b){var c=(0,g.x)(function(d,e,f){e=f?R0(this,e,(0,g.x)(f,this)):R0(this,e);
this.aa.ca(b,d,e)},a);
c("mouseover","G",a.xx);c("mouseout","F",a.Dg);c("click","D");c("touchend","D")},Ooa=function(a){if(a.g.o){if(v0(a.g,function(d){return"close"==d.type}))var b=a.i;
else a.o=g.Rd("DIV","annotation-close-button"),g.Th(a.o,!1),g.Fp(a.o,"annotation_id",a.g.id),a.i.appendChild(a.o),b=a.o;var c=function(d){d.stopPropagation()};
a.aa.ca(b,"click",R0(a,"E",c));a.aa.ca(b,"touchend",R0(a,"E",c))}},R0=function(a,b,c){return(0,g.x)(function(d){if(this.Z)c&&c(d);
else if(d.event.target instanceof Element){var e=d.event.target;g.Th(e,!1);try{var f=document.elementFromPoint(d.event.clientX,d.event.clientY);if(g.ge(f,null,"annotation",void 0)){var k=document.createEvent("MouseEvent");k.initMouseEvent(d.event.type,d.event.bubbles,d.event.cancelable,d.event.view,d.event.detail,d.event.screenX,d.event.screenY,d.event.clientX,d.event.clientY,d.event.ctrlKey,d.event.altKey,d.event.shiftKey,d.event.metaKey,d.event.button,d.event.relatedTarget);f.dispatchEvent(k)}}finally{g.Th(e,
!0)}}e=wZ(d.target);d=new g.ud(d.clientX,d.clientY);"F"==b&&e.contains(d)||this.X.N(b,this.g)},a)},U0=function(a){if(a.i||a.l){var b=z0(a.g);
if(b){var c=S0(a);if(a.i){b=m0(b,c);var d=g.YJ(a.A).getVideoContentRect();g.Rh(a.i,b.width,b.height);g.Hh(a.i,b.left,b.top);a.P=new g.nh(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=z0(a.g))&&d?g0(d,e.o,e.g?e.g:"xy"):1;var f=A0(a.g,d);d=a.g.g;d.padding?d=d.padding:(d="speech"==a.g.style?1.6:.8,d=new g.kh(d,d,d,d));d=new g.kh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.u&&(d.right+=1.5*c.g.height/100);a.i.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+d.left+
"px";"label"==a.g.style&&a.C&&(a.C.style.padding=a.i.style.padding);d=c.g;var k=!1,l=0,m=0;var n=g.YJ(a.A).getVideoContentRect();var p=g.cK(a.A);g.ph(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.g.u&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.u){f=T0(a,23,b,d,e);if(a.o){var r=43-f.width;0<r&&(b.left+f.left-r>n.left&&(f.left-=r),f.width+=r)}r=f;g.Rh(a.u,f.width,f.height);g.Hh(a.u,f.left,f.top)}a.o&&(r?b=new g.ud(r.left+
r.width-23-18,a.V?r.top+2:r.top+r.height-18-2):(r=T0(a,18,b,d,e),b=new g.ud(r.left,r.top),g.Rh(a.o,r.width,r.height)),g.Hh(a.o,b));a.M=new g.nh(a.P.left+r.left,a.P.top+r.top,r.width,r.height);a.I=a.aa.ca(g.YJ(a.A),"mousemove",a.IF,a)}else a.u&&(r=e/f*d.height*4.2/100,r=new g.wd(r,r),"highlight"==a.g.type||"label"==a.g.style?(e=1.5*d.height/100,r=new g.nh(b.width-r.width-e,b.height-r.height-e,r.width,r.height)):r=new g.nh(b.width-r.width-3*d.height/100,(b.height-r.height)/2,r.width,r.height),g.Rh(a.u,
r.width,r.height),g.Hh(a.u,r.left,r.top)),a.o&&(r=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.Hh(a.o,r&&e?new g.ud(b.width-9,-9):r?new g.ud(b.width-9,45<b.height?9:b.height-9):e?new g.ud(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.ud(45<b.width?b.width-9-18:-9,b.height-9):new g.ud(-9,45<b.height?9:b.height-9)))}a.l&&a.l.l(a.g,c);if(a.i){c=a.i;b=a.g.g;c.style.color="highlightText"==a.g.style?b.A:b.i;r=g.YJ(a.A).getVideoContentRect();c.style.fontSize=360*b.textSize*
A0(a.g,r)/100+"px";r=a.g.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==r||"highlightText"==r?"center":"left";b.o&&(c.style.fontWeight=b.o);a=a.i;c=a.style.overflow;r=(b=g.Hd("annotation-link-icon",a))?yZ(b):!1;e=(d=g.Hd("annotation-close-button",a))?yZ(d):!1;r&&g.Th(b,!1);e&&g.Th(d,!1);m=f="";if(n=g.Hd("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth){l=
k=Nna(a);p=5;for(var u=Math.floor(k/2);u;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+u,k)):l=Math.max(l-u,p),u=Math.floor(u/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.Th(d,!0);r&&g.Th(b,!0)}}}},T0=function(a,b,c,d,e){var f=0<e;
b=new g.nh(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.J(a.i,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.J(a.i,"annotation-extend-up"),a.V=!0);return b},V0=function(a){return"label"!=a.g.style||a.l.g},S0=function(a){var b=g.YJ(a.A).getVideoContentRect();
if("player_relative"==a.g.u){var c=g.YJ(a.A).getPlayerSize();b=new g.nh(-b.left,-b.top,c.width,c.height)}else b=new g.nh(0,0,b.width,b.height);return new o0(b,a.O?z0(a.O):null)},W0=function(a,b){return b?new g.nh(a.x+b.left,a.y+b.top,b.width,b.height):null},X0=function(a,b,c){g.D.call(this);
this.i=a;this.annotation=b;this.view=c;this.g=null;this.l=this.isVisible=!1;Poa(b,a)},Poa=function(a,b){Foa(a,function(c){return new C0(a.id,c,b)})},Y0=function(a){a.i.unsubscribe("resize",a.wx,a);
a.i.unsubscribe("onVideoAreaChange",a.kz,a)},Z0=function(a){a.g&&(a.g.stop(),a.g=null)},$0=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Qoa=function(a,b){this.merchant=a;
this.price=b},Roa=function(a){this.g=a;
this.i={}},Soa=function(a){var b={};
b=(b["iv-event"]=1,b);uZ(a.g,b)},d1=function(a,b,c,d){if(b){var e=a1(a,b);
a.i[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=b1(a,"cta_annotation_shown",e,c);c1(a,e,Toa(b,d))}},e1=function(a,b,c,d,e,f){if(b){var k=a1(a,b);
k["iv-event"]=3;k["i-time"]=a.i[b]||"";d&&g.fc(k,d);b=b1(a,"cta_annotation_clicked",k,e);c1(a,k,b,c,f)}},f1=function(a,b){if(b){var c=a1(a,b);
c["iv-event"]=4;c["i-time"]=a.i[b]||"";var d=b1(a,"cta_annotation_closed",c);c1(a,c,d)}},Toa=function(a,b){return b?(0,g.B)(a,g.Sa(function(c,d){return g.dn(d,c)},b)):a},b1=function(a,b,c,d){d=d?g.ib(d):[];
var e=c["a-type"];if(30==e||31==e&&g.Q(g.X(a.g).experiments,"enable_async_click_tracking")){a:{c=c["a-id"];a=a.g.getVideoData();if(a.wu){if((b=a.wu[b])&&g.bv(b)){a=g.Xc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.Hn){b=g.oq(a.Hn,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},c1=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.z)(c||[],function(n){f++;
g.$q(n,m)});
e&&(f++,0!=e&&a.g.sendVideoStatsEngageEvent(e,m));uZ(a.g,b)},a1=function(a,b){var c={};
if(b){var d=new g.Tm(b);(0,g.z)(d.Gd(),function(e){c[e]=escape(d.get(e,""))})}c["p-time"]=a.g.getCurrentTime().toFixed(2);
c.ps=g.X(a.g).playerStyle;return c},g1=function(a,b,c,d,e){e=a1(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;c1(a,e,d)},h1=function(a,b,c,d){c&&(c=a1(a,c),c["iv-event"]=b,c1(a,c,d))},Uoa=function(a,b,c,d,e,f,k){this.g=a;
this.l=b;this.xb=c;this.videoData=d;this.logger=e;this.Y=f;this.i=k},i1=function(a,b){this.g=a;
this.o=b;this.i=new g.Mn},Woa=function(a,b){var c=[];
(0,g.z)(b.choices,function(k){c.push(Voa(this,b,k))},a);
var d={B:"ul",L:{role:"radiogroup"},J:c},e={};b.Od&&(e["aria-label"]=g.jN("$POLL_TITLE - \u0e25\u0e07\u0e0a\u0e37\u0e48\u0e2d\u0e40\u0e02\u0e49\u0e32\u0e43\u0e0a\u0e49\u0e40\u0e1e\u0e37\u0e48\u0e2d\u0e42\u0e2b\u0e27\u0e15",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{B:"div",G:"iv-card-content",J:[j1(a,"h2",e,b.title),{B:"form",J:[{B:"fieldset",J:[d]}]}]}];b.Od&&(f.push("iv-card-unavailable"),d.push({B:"div",W:["iv-card-sign-in"],J:[{B:"h2",T:"\u0e15\u0e49\u0e2d\u0e07\u0e01\u0e32\u0e23\u0e42\u0e2b\u0e27\u0e15\u0e43\u0e0a\u0e48\u0e44\u0e2b\u0e21"},
{B:"a",W:["iv-card-sign-in-button","iv-button"],L:{href:f0(b.Od)},J:[{B:"span",W:["iv-button-content"],T:"\u0e25\u0e07\u0e0a\u0e37\u0e48\u0e2d\u0e40\u0e02\u0e49\u0e32\u0e43\u0e0a\u0e49"}]}]}));f=new g.W({B:"div",W:f,J:d});d=f.element;k1(b,d);Sna(a.g.g,d,g.Sa(a.u,b),a);(0,g.z)(g.Gd("iv-card-poll-choice-input",d),function(k){this.g.g.ca(k,"focus",g.Sa(this.l,!0));this.g.g.ca(k,"blur",g.Sa(this.l,!1))},a);
b.Od&&(d=g.Hd("iv-card-sign-in-button",d),a.o(d,b.Od,b.id,b.Xb,b.bb,b.qd.click,5));return f},o1=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.YM?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.gE&&b.Au?{B:"span",W:d,L:e,T:b.Au}:"";c={B:"div",W:["iv-card",c],J:[{B:"a",G:"iv-click-target",L:{href:f0(b.url)},J:[l1(b.al,d?{B:"div",G:"iv-card-image-text",J:[d,b.priceText]}:""),{B:"div",G:"iv-card-content",J:[{B:"h2",G:"iv-card-primary-link",T:b.title},m1(a,b)]}]}]};c=new g.W(c);n1(a,c,b);return c},p1=function(a,b){return b.customMessage?j1(a,"div",
"iv-card-message",b.customMessage):""},l1=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{B:"div",G:"iv-card-image",L:{style:c},J:d}},m1=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.z)(b.metaInfo,function(d){c.push(j1(this,"li","",d))},a);
return{B:"ul",G:"iv-card-meta-info",J:c}},Voa=function(a,b,c){return{B:"li",
G:$0(b,c.index),J:[{B:"label",J:[{B:"input",G:"iv-card-poll-choice-input",L:{type:"checkbox",role:"radio",name:b.id.replace(/[^a-z0-9-]/gi,"-")+c.index.toString(),value:c.index.toString(),"data-poll-choice-index":c.index.toString()}},{B:"span",G:"iv-card-poll-choice-text",J:[{B:"span",G:"iv-card-poll-choice-percent"},j1(a,"span",void 0,c.desc)]}]},{B:"div",G:"iv-card-poll-result",J:[{B:"div",G:"iv-card-poll-result-bar"}]}]}},j1=function(a,b,c,d){c?g.Fa(c)?c={"class":c}:g.Ma(c)&&(c={"class":c.join(" ")}):
c={};
c.dir=g.Nn(a.i,d);return{B:b,L:c,T:d}},q1=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.cp&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.cp+");");d.dir=g.Nn(a.i,b.customMessage);var e=[{B:"span",T:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({B:"span",G:"iv-card-link-icon"}));return{B:"div",W:c,L:d,J:e}},k1=function(a,b){var c=0;
(0,g.z)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Hd($0(a,e.index),b);e=e.count/c;null==a.he&&(e=0);g.K(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.he==d);f.getElementsByTagName("input")[0].checked=a.he==d;var k=Math.floor(100*e).toFixed(0),l=g.Hd("iv-card-poll-choice-percent",f);g.be(l,g.jN("$PERCENT%",{PERCENT:k}));f=g.Hd("iv-card-poll-result-bar",f);g.zh(f,"transform","scaleX("+e.toFixed(2)+")")}g.K(b,"iv-card-poll-voted",null!=a.he);g.K(b,"iv-card-poll-expanded",
null!=a.he&&1<a.choices.length)},n1=function(a,b,c,d,e){c.Od&&r1(a,g.Gd("iv-card-sign-in-button",b.element),c,c.Od,e);
c.url&&r1(a,g.Gd("iv-click-target",b.element),c,c.url,d)},r1=function(a,b,c,d,e){(0,g.z)(b,function(f){if(e){var k=(0,g.x)(function(l){l.stopPropagation();
l.preventDefault();e();return!1},this);
this.g.g.ca(f,"click",k)}else d&&this.o(f,d,c.id,c.Xb,c.bb,c.qd.click,5)},a)},s1=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},u1=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=t1(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},t1=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},Xoa=function(a){a=f0(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!u1(a))||(b=g.Qg(g.Sg(5,a))||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.mq(a);if(!b||!b.v)return null;if(b=b.t)return s1(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.kq(a[1]))&&a.t?s1(a.t):-1},v1=function(a){a=f0(a);
a=a.replace(/https?:\/\//g,"");return u1(a)?(a=g.mq(a))&&a.v?a.v:null:null},Yoa=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},w1=function(a,b){return b?b:u1(a)?"current":"new"},x1=function(a,b){g.D.call(this);
this.Ba=a;this.context=b;this.lt=!1;this.X=0},Zoa=function(a){return(0,g.H)()-a.X},$oa=function(a,b,c,d,e,f){var k=f0(b);
if(k){var l=w1(k,b.target),m=(0,g.x)(function(){b.g&&this.context.Y.pauseVideo();var p=this.context.videoData.Nb||!1,r=g.mq(k||"");p&&r&&(r.v||r.list)?g.VX(this.context.Y.app,r.v,c,r.list,!1,void 0):g.rL(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=Zoa(a);e1(a.context.logger,d,m,n,e,f);u1(k)||(a=g.at(),d=c.itct,a&&d&&g.Os(a,g.Ks(d)))}},A1=function(a,b,c){x1.call(this,b,c);
var d=this;this.i=a;this.R=null;this.V=this.wa=this.u=this.va=!1;this.ba=null;this.M=new g.M(g.Ja,c.xb.fd?4E3:3E3);g.G(this,this.M);this.ka=new g.M(g.Ja);g.G(this,this.ka);this.D=new i1(c,(0,g.x)(this.Ni,this),(0,g.x)(this.Nm,this));this.F=new g.W({B:"div",G:"iv-drawer",L:{id:"iv-drawer"},J:[{B:"div",G:"iv-drawer-header",L:{"aria-role":"heading"},J:[{B:"span",G:"iv-drawer-header-text"},{B:"button",W:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"\u0e0b\u0e48\u0e2d\u0e19\u0e01\u0e32\u0e23\u0e4c\u0e14",
tabindex:"0"}}]},{B:"div",G:"iv-drawer-content"}]});g.G(this,this.F);this.A=this.F.element;this.ua=new g.WP(this.F,330);g.G(this,this.ua);this.xa=g.Hd("iv-drawer-header-text",this.A);this.o=g.Hd("iv-drawer-content",this.A);this.l=[];this.ma=this.O=this.C=this.Z=this.g=null;this.I=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.wa&&y1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.wa=d.u)&&z1(d)});
this.P=this.H=this.fa=null},apa=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c){var d=b.data.tracking||{};d={XD:d.impression,click:d.click,close:d.close,IM:d.teaser_impression,Ps:d.teaser_click};var e=b.data.tracking_params||{},f=null;switch(c){case "collaborator":d={id:b.id,bb:b.bb,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,qd:d,rf:e.card?g.Ks(e.card):null,af:e.teaser?g.Ks(e.teaser):
null,de:e.icon?g.Ks(e.icon):null,channelId:b.data.channel_id,customMessage:b.data.custom_message?b.data.custom_message:null,cM:b.data.image_url,title:b.data.title,metaInfo:b.data.meta_info,url:e0({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url})};B1(a,d);break;case "episode":case "movie":d={id:b.id,bb:b.bb,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,
autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,qd:d,rf:e.card?g.Ks(e.card):null,af:e.teaser?g.Ks(e.teaser):null,de:e.icon?g.Ks(e.icon):null,al:b.data.image_url,Au:b.data.badge_symbol||"",priceText:b.data.price_text||"",title:b.data.title,metaInfo:b.data.meta_info,gE:!!b.data.is_paygated,YM:!!b.data.user_has_entitlement,url:e0({target:b.data.target||"new",value:b.data.url})};B1(a,d);break;case "playlist":d={id:b.id,bb:b.bb,timestamp:b.data.timestamp||0,type:b.data.card_type,
teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,qd:d,rf:e.card?g.Ks(e.card):null,af:e.teaser?g.Ks(e.teaser):null,de:e.icon?g.Ks(e.icon):null,al:b.data.image_url,playlistVideoCount:b.data.playlist_video_count,customMessage:b.data.custom_message?b.data.custom_message:null,title:b.data.title,metaInfo:b.data.meta_info,url:e0({pause_on_navigation:b.data.pause_on_navigation,
target:b.data.target||"new",value:b.data.url})};B1(a,d);break;case "poll":d={id:b.id,bb:b.bb,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,qd:d,rf:e.card?g.Ks(e.card):null,af:e.teaser?g.Ks(e.teaser):null,de:e.icon?g.Ks(e.icon):null,title:b.data.title,choices:b.data.choices,he:b.data.hasOwnProperty("old_vote")?
b.data.old_vote:null,Od:b.data.signin_url?e0({target:"current",value:b.data.signin_url}):null,hN:b.data.hasOwnProperty("xsrf_token")?b.data.xsrf_token:null};B1(a,d);break;case "productListing":b.data.signin_url&&(f=e0({target:"current",value:b.data.signin_url}));c=[];for(var k=b.data.offers||[],l=0;l<k.length;l++)c.push(new Qoa(g.bd(k[l].merchant),g.bd(k[l].price)));d={JQ:!1,id:b.id,bb:b.bb,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,
startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,qd:d,rf:e.card?g.Ks(e.card):null,af:e.teaser?g.Ks(e.teaser):null,de:e.icon?g.Ks(e.icon):null,imageUrl:b.data.image_url,displayDomain:b.data.display_domain?b.data.display_domain:null,showLinkIcon:b.data.show_link_icon,cp:b.data.button_icon_url,title:b.data.title,customMessage:b.data.custom_message?b.data.custom_message:null,url:e0({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||
"new",value:b.data.url}),Od:f,AA:b.data.signin_title||null,zA:b.data.signin_message||null,offers:c};B1(a,d);break;case "simple":b.data.signin_url&&(f=e0({target:"current",value:b.data.signin_url}));d={id:b.id,bb:b.bb,timestamp:b.data.timestamp||0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,qd:d,rf:e.card?g.Ks(e.card):null,af:e.teaser?g.Ks(e.teaser):
null,de:e.icon?g.Ks(e.icon):null,imageUrl:b.data.image_url,displayDomain:b.data.display_domain?b.data.display_domain:null,showLinkIcon:b.data.show_link_icon,cp:b.data.button_icon_url,title:b.data.title,customMessage:b.data.custom_message?b.data.custom_message:null,url:e0({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url}),Od:f,AA:b.data.signin_title||null,zA:b.data.signin_message||null};B1(a,d);break;case "video":d={id:b.id,bb:b.bb,timestamp:b.data.timestamp||
0,type:b.data.card_type,teaserText:b.data.teaser_text,teaserDurationMs:b.data.teaser_duration_ms,startMs:b.data.start_ms,autoOpen:b.data.auto_open||!1,Xb:b.data.session_data||{},sponsored:b.data.sponsored||!1,qd:d,rf:e.card?g.Ks(e.card):null,af:e.teaser?g.Ks(e.teaser):null,de:e.icon?g.Ks(e.icon):null,al:b.data.image_url,videoDuration:b.data.video_duration||null,customMessage:b.data.custom_message?b.data.custom_message:null,title:b.data.title,metaInfo:b.data.meta_info,isLiveNow:!!b.data.is_live_now,
url:e0({pause_on_navigation:b.data.pause_on_navigation,target:b.data.target||"new",value:b.data.url})},B1(a,d)}}},bpa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){y1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){z1(a)});
var c=b.data.headerText;g.be(a.xa,c);a.O&&a.O.setAttribute("title",c);b.data.eventId&&(a.R=b.data.eventId);a.fa=g.Ks(b.data.trackingParams);a.P=g.Ks(b.data.closeTrackingParams);a.H=g.Ks(b.data.iconTrackingParams)},D1=function(a,b){var c=cpa(a,b);
c&&(c==a.g&&(a.g=null),a.i.removeCueRange(c.Fb.id),g.Xd(c.lp),g.db(a.l,c),a.Ll(),C1(a))},y1=function(a,b,c,d){if(!a.u){a.ua.show();
a.Z=new g.M(function(){g.J(a.context.Y.getRootNode(),"ytp-iv-drawer-open")},0);
a.Z.start();a.ba=g.Nr(a.o,"mousewheel",(0,g.x)(a.gF,a));a.u=!0;a.X=(0,g.H)();g1(a.context.logger,a.R,7,void 0,d&&d.Fb?d.Fb.bb:void 0);var e=g.at();e&&a.fa&&a.P&&LZ(e,[a.fa,a.P]);var f={TRIGGER_TYPE:b};(0,g.z)(a.l,function(k){k.Vw||(k.Vw=!0,d1(a.context.logger,k.Fb.bb,k.Fb.qd.XD,f));e&&LZ(e,[k.Fb.rf])});
vZ(a.i);c&&(a.C=new g.M(function(){a.da=a.O;a.ma.focus()},330),a.C.start())}},z1=function(a){a.u&&(a.ua.hide(),g.Or(a.ba),a.ba=null,g.Tn(a.context.Y.getRootNode(),"ytp-iv-drawer-open"),a.u=!1,vZ(a.i),a.C&&a.C.stop(),a.C=new g.M(function(){a.da&&(a.da.focus(),a.da=null)},330),a.C.start())},dpa=function(a){var b=g.Hd("iv-drawer-close-button",a.A);
a.context.g.ca(b,"click",a.wC,a);a.context.g.ca(a.o,"touchend",function(){a.M.start()});
a.context.g.ca(a.o,"scroll",a.HC,a);a.context.i.subscribe("onHideControls",function(){a.V=!0});
a.context.i.subscribe("onShowControls",function(){a.V=!1});
a.context.i.subscribe("onVideoAreaChange",function(){a.V=g.Rn(a.i.getRootNode(),"ytp-autohide")});
a.I.push(g.Pp("iv-button-shown",a.qE,a));a.I.push(g.Pp("iv-button-hidden",a.pE,a));a.I.push(g.Pp("iv-teaser-shown",a.tE,a));a.I.push(g.Pp("iv-teaser-hidden",a.sE,a));a.I.push(g.Pp("iv-teaser-clicked",a.rE,a))},B1=function(a,b){a.va||(g.Sn(a.ga(),["html5-stop-propagation",
"iv-drawer-manager"]),g.lK(a.i,a.A,5),dpa(a),a.O=g.Hd("ytp-cards-button",a.i.getRootNode()),a.ma=g.Hd("iv-drawer-close-button",a.A),a.va=!0);D1(a,b.id);var c=epa(a,b);if(c){var d={Fb:b,lp:c.element,Vw:!1},e=fpa(a,d);g.lb(a.l,e,0,d);c.g(a.o,e);a.Ll();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Sa(a.uM,d)):(c=1E3*a.context.Y.getCurrentTime(),5E3>c&&c>b.startMs&&a.lA(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Sa(a.lA,d)),C1(a))}},epa=function(a,b){switch(b.type){case "simple":var c=
a.D,d=b.displayDomain?{B:"div",
G:"iv-card-image-text",T:b.displayDomain}:"",e=q1(c,b),f=["iv-card"];b.Od&&f.push("iv-card-unavailable");d=[{B:"a",G:"iv-click-target",L:{href:f0(b.url)},J:[l1(b.imageUrl,d),{B:"div",G:"iv-card-content",J:[j1(c,"h2",void 0,b.title),e]}]}];b.Od&&d.push({B:"div",W:["iv-card-sign-in"],J:[j1(c,"h2",void 0,b.AA||""),{B:"p",T:b.zA},{B:"a",W:["iv-card-sign-in-button","iv-button"],L:{href:f0(b.Od)},J:[j1(c,"span","iv-button-content","\u0e25\u0e07\u0e0a\u0e37\u0e48\u0e2d\u0e40\u0e02\u0e49\u0e32\u0e43\u0e0a\u0e49")]}]});
f=new g.W({B:"div",W:f,J:d});n1(c,f,b,void 0,void 0);return f;case "collaborator":return c=a.D,f={B:"div",W:["iv-card","iv-card-channel"],J:[{B:"a",W:["iv-click-target"],L:{href:f0(b.url),"data-ytid":b.channelId},J:[l1(b.cM),{B:"div",G:"iv-card-content",J:[p1(c,b),{B:"h2",G:"iv-card-primary-link",T:b.title},m1(c,b)]}]}]},f=new g.W(f),n1(c,f,b),f;case "episode":return o1(a.D,b,"iv-card-episode");case "movie":return o1(a.D,b,"iv-card-movie");case "playlist":return c=a.D,f={B:"div",W:["iv-card","iv-card-playlist"],
J:[{B:"a",G:"iv-click-target",L:{href:f0(b.url)},J:[l1(b.al,{B:"div",G:"iv-card-image-overlay",J:[{B:"span",G:"iv-card-playlist-video-count",T:b.playlistVideoCount.toString()}]}),{B:"div",G:"iv-card-content",J:[p1(c,b),j1(c,"h2","iv-card-primary-link",b.title),m1(c,b)]}]}]},f=new g.W(f),n1(c,f,b),f;case "poll":return Woa(a.D,b);case "productListing":c=a.D;e=0!=b.offers.length;f=["iv-card"];d="";var k=q1(c,b);e&&(f.push("iv-card-product-listing"),d="iv-card-primary-link",e=b.offers[0],k=[],e.price&&
k.push({B:"div",G:"iv-card-offer-price",T:e.price}),e.merchant&&k.push({B:"div",G:"iv-card-offer-merchant",T:e.merchant}),k={B:"div",J:k});f={B:"div",W:f,L:{tabindex:"0"},J:[{B:"a",W:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+b.imageUrl+");",href:f0(b.url),"aria-hidden":"true",tabindex:"-1"}},{B:"div",G:"iv-card-content",J:[b.sponsored?{B:"div",G:"iv-card-sponsored",J:["\u0e1c\u0e39\u0e49\u0e2a\u0e19\u0e31\u0e1a\u0e2a\u0e19\u0e38\u0e19",{B:"div",G:"iv-ad-info-container",
J:[{B:"div",G:"iv-ad-info",T:"{{adInfo}}"},{B:"div",G:"iv-ad-info-icon-container",J:[{B:"div",G:"iv-ad-info-icon"},{B:"div",G:"iv-ad-info-callout"}]}]}]}:"",{B:"a",G:"iv-click-target",L:{href:f0(b.url)},J:[j1(c,"h2",d,b.title),k]}]}]};f=new g.W(f);d=g.Sd("span");g.be(d,"\u0e04\u0e38\u0e13\u0e40\u0e2b\u0e47\u0e19\u0e1c\u0e25\u0e34\u0e15\u0e20\u0e31\u0e13\u0e11\u0e4c\u0e19\u0e35\u0e49\u0e40\u0e1e\u0e23\u0e32\u0e30\u0e40\u0e23\u0e32\u0e04\u0e34\u0e14\u0e27\u0e48\u0e32\u0e40\u0e01\u0e35\u0e48\u0e22\u0e27\u0e02\u0e49\u0e2d\u0e07\u0e01\u0e31\u0e1a\u0e27\u0e34\u0e14\u0e35\u0e42\u0e2d\u0e14\u0e31\u0e07\u0e01\u0e25\u0e48\u0e32\u0e27 Google \u0e2d\u0e32\u0e08\u0e44\u0e14\u0e49\u0e23\u0e31\u0e1a\u0e01\u0e32\u0e23\u0e0a\u0e14\u0e40\u0e0a\u0e22\u0e08\u0e32\u0e01\u0e1c\u0e39\u0e49\u0e02\u0e32\u0e22");
f.nb(d,"adInfo");n1(c,f,b);return f;case "video":return c=a.D,f=b.isLiveNow?{B:"span",W:["yt-badge","yt-badge-live"],T:"\u0e16\u0e48\u0e32\u0e22\u0e17\u0e2d\u0e14\u0e2a\u0e14"}:"",f={B:"div",W:["iv-card","iv-card-video"],J:[{B:"a",G:"iv-click-target",L:{href:f0(b.url)},J:[l1(b.al,b.videoDuration?{B:"span",G:"iv-card-video-duration",T:b.videoDuration}:""),{B:"div",G:"iv-card-content",J:[p1(c,b),j1(c,"h2","iv-card-primary-link",b.title),m1(c,b),f]}]}]},f=new g.W(f),n1(c,f,b),f}return null},fpa=function(a,
b){if(0==a.l.length)return 0;
var c=g.Za(a.l,function(d){return b.Fb.startMs>d.Fb.startMs||b.Fb.startMs==d.Fb.startMs&&b.Fb.timestamp>=d.Fb.timestamp?!0:!1});
return-1==c?0:c+1},gpa=function(a){return a.g?"productListing"==a.g.Fb.type:(0,g.jj)(a.l,function(b){return"productListing"==b.Fb.type})},C1=function(a){g.K(a.i.getRootNode(),"ytp-cards-shopping-active",gpa(a))},E1=function(a,b){if(a.F.Da()){var c=new GZ([0,
a.o.scrollTop],[0,b.lp.offsetTop],600,Rna);a.context.l.ca(c,"animate",function(d){a.o.scrollTop=d.y});
a.context.l.ca(c,"finish",function(d){a.o.scrollTop=d.y});
c.play()}else g.NC(a.F,!0),a.o.scrollTop=b.lp.offsetTop,g.NC(a.F,!1)},F1=function(a){return a.g&&a.g.Fb?a.g.Fb:a.l[0]&&a.l[0].Fb?a.l[0].Fb:null},cpa=function(a,b){return g.Ya(a.l,function(c){return c.Fb.id==b})},G1=function(a,b,c){x1.call(this,a,b);
this.annotation=c;this.isActive=!1},hpa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},H1=function(a,b,c){G1.call(this,a,b,c);
this.i=null;this.D=!1;this.l=null;this.o=!1;this.u=0;this.g=this.C=this.A=null},I1=function(a,b,c){G1.call(this,a,b,c);
this.F=this.u=this.H=!1;this.C=5E3;this.o=null;this.D=g.Rd("DIV","iv-promo-contents");this.i=this.l=this.g=null;this.A=new g.M(function(){this.g.setAttribute("aria-hidden",!0);g.Th(this.l,!1);g.Th(this.i,!0)},700,this);
g.G(this,this.A)},ipa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.C=b.collapse_delay_ms||a.C;var d=["iv-promo","iv-promo-inactive"];a.ga().setAttribute("aria-hidden",!0);a.ga().setAttribute("aria-label","\u0e01\u0e32\u0e23\u0e42\u0e1b\u0e23\u0e42\u0e21\u0e15");a.ga().tabIndex=0;var e=a.annotation.Jb(),f=b.image_url;if(f){var k=g.Rd("DIV",["iv-promo-img","iv-click-target"]);f=g.Rd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?
(f=g.Rd("SPAN","iv-promo-video-duration",b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.Rd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Ni(k,e,a.annotation.id,b.session_data,a.annotation.bb,void 0,c)}e?(f=g.Rd("A","iv-promo-txt"),g.Uc(f,f0(e)),a.g=f):a.g=g.Rd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_1));var m=g.Rd("P",null,g.Rd("SPAN","iv-promo-link",b.text_line_2));
if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.Q(a.context.xb.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Rd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Rd("BUTTON",["iv-button","iv-promo-button"],g.Rd("SPAN","iv-button-content",f));var p=g.Rd("DIV","iv-promo-button-container");p.appendChild(f);e&&a.Ni(a.ga(),e,a.annotation.id,b.session_data,a.annotation.bb,void 0,c)}g.J(a.g,"iv-click-target");e&&a.Ni(a.g,e,a.annotation.id,
b.session_data,a.annotation.bb,void 0,c);break;case "playlist":case "video":l=g.Rd("P",null,g.Rd("SPAN",null,b.text_line_1)),m=g.Rd("P",null,g.Rd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Rd("SPAN",["yt-badge","iv-promo-badge-live"],"\u0e16\u0e48\u0e32\u0e22\u0e17\u0e2d\u0e14\u0e2a\u0e14")),g.J(a.g,"iv-click-target"),e&&a.Ni(a.g,e,a.annotation.id,b.session_data,a.annotation.bb,void 0,c),d.push("iv-promo-video")}l&&a.g.appendChild(l);m&&a.g.appendChild(m);a.D.appendChild(a.g);p&&a.D.appendChild(p);
c=g.Rd("DIV","iv-promo-actions");a.i=g.Rd("BUTTON",["iv-promo-expand","ytp-button"]);a.i.title="\u0e02\u0e22\u0e32\u0e22";a.context.g.ca(a.i,"click",g.Sa(a.hq,5E3),a);c.appendChild(a.i);g.Th(a.i,!1);a.context.g.ca(a.ga(),"mouseover",a.zD,a);a.context.g.ca(a.ga(),"mouseout",a.yD,a);a.context.g.ca(a.ga(),"touchend",g.Sa(a.hq,5E3),a);a.l=g.Rd("BUTTON",["iv-promo-close","ytp-button"]);a.l.title="\u0e1b\u0e34\u0e14";a.context.g.ca(a.l,"click","cta"==a.annotation.style&&b.text_line_3?a.rD:a.qD,a);c.appendChild(a.l);
g.Sn(a.ga(),d);k&&(a.ga().appendChild(k),n&&k.appendChild(n));a.ga().appendChild(a.D);a.ga().appendChild(c)},J1=function(a){a.u||a.F||a.o||(g.J(a.ga(),"iv-promo-collapsed"),a.u=!0,a.A.start())},K1=function(a){a.A.stop();
a.u&&(g.Un(a.ga(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.u=!1,a.g&&a.g.removeAttribute("aria-hidden"),g.Th(a.i,!1),g.Th(a.l,!0))},M1=function(a,b){a.o||(a.o=g.Gg(function(){L1(this);
J1(this)},b,a))},L1=function(a){a.o&&(g.v.clearTimeout(a.o),a.o=null)},N1=function(a){g.zK.call(this,a);
this.I=!1;this.H=0;this.i={};this.P={};this.D=new Roa(a);this.A=new g.rs(this);g.G(this,this.A);this.C=this.l=null;this.A.K(this.player,"onVideoAreaChange",(0,g.x)(this.N,this,"onVideoAreaChange"));this.A.K(this.player,"onHideControls",(0,g.x)(this.N,this,"onHideControls"));this.A.K(this.player,"onShowControls",(0,g.x)(this.N,this,"onShowControls"));this.A.K(this.player,"resize",(0,g.x)(this.N,this,"resize"));this.A.K(this.player,"presentingplayerstatechange",(0,g.x)(this.N,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.dJ,this);this.subscribe("onShowControls",this.YK,this);this.subscribe("presentingplayerstatechange",this.iK,this);this.subscribe("resize",this.wn,this);this.subscribe("G",this.OE,this);this.subscribe("F",this.Dg,this);this.subscribe("D",this.aI,this);this.subscribe("E",this.DI,this);g.X(this.player).I.subscribe("vast_info_card_add",this.jz,this);this.R=new g.rs(this);g.G(this,this.R);this.R.K(this.player,g.ND("annotations_module"),this.ME);this.R.K(this.player,
"crx_annotations_module",this.NE);this.O=g.Rd("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.V=g.Rd("DIV","video-custom-annotations");this.u=new g.W({B:"div",W:["ytp-player-content","ytp-iv-player-content"]});g.G(this,this.u);g.lK(this.player,this.u.element,4);this.u.hide();this.o=new g.W({B:"div",W:["ytp-iv-video-content"]});g.G(this,this.o);g.Ud(this.o.element,g.Rd("DIV","video-annotations",this.O,this.V));this.F=this.g=null;this.M=[];jpa(this)&&this.load();var b=g.Sd("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.pf(this,function(){g.Xd(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},O1=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},jpa=function(a){var b=g.X(a.player);
a=a.player.getVideoData();return 1==(b.Yf||a.Yf)&&!a.iB||null!==b.I.get(a.videoId)},P1=function(a,b,c){a.I=!0;
a.C=g.Fq(b,c)},Q1=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Q1(a,e))}return c},R1=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},lpa=function(a,b){var c=kpa(a,b);
if(!c&&"marker"!=b.type)return null;x0(b,function(e){e=(0,g.x)(this.wL,this,b.id,e);this.subscribe("ivTrigger:"+b.id,e)},a);
var d=new X0(a.ua,b,c);g.G(d,c);return d},mpa=function(a,b){var c=g.Rd("DIV",["annotation",
"annotation-type-custom"]);g.Th(c,!1);var d=null;switch(b.type){case "branding":if(g.X(a.player).ej)break;a.u.element.appendChild(c);d=new H1(c,S1(a),b);break;case "promotion":g.lK(a.player,c,4),d=new I1(c,S1(a),b)}d&&d.Vn();return d},npa=function(a){var b=a.player.getVideoData();
if(b.Ed){var c=g.X(a.player),d=c.I.get(b.videoId);if(d){var e={format:"XML",Dc:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.Dc.gaming="1");e.Zc=(0,g.x)(function(f,k,l){R1(this,f,k)||(f=g.zq(l)&&l.responseXML?l.responseXML:null)&&T1(this,f)},a,a.H,b.videoId);
g.cq()&&(e.Zc=U1(a,e.Zc));e.ub={ic_only:"1"};V1(e,d);a.I=!0;g.Fq(b.Ed,e)}}},V1=function(a,b){a.method="POST";
a.ub=a.ub||{};b.Ql&&(a.ub.ic_coll=b.Ql);b.Rl&&(a.ub.ic_xml=b.Rl);b.Ws&&(a.ub.ic_track=b.Ws)},W1=function(a){var b=new g.W({B:"div"});
g.Th(b.element,!1);var c=new A1(a.player,b.element,S1(a));g.G(c,b);b.g(a.u.element);c.Vn();return c},S1=function(a){if(!a.F){var b=new KZ(a);
g.G(a,b);var c=new g.an(a);g.G(a,c);a.F=new Uoa(b,c,g.X(a.player),a.player.getVideoData(),a.D,a.player,a.ua)}return a.F},T1=function(a,b){var c=!1;
opa(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=Q1(a,d[e]),k=null;try{k=Coa(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=mpa(a,k))g.G(a,f),a.P[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.g||(a.g=W1(a),g.G(a,a.g)),"card"==k.type?apa(a.g,k):bpa(a.g,k),c=!0;else if(f=lpa(a,k))g.G(a,f),a.i[k.id]=f}}c&&(vZ(a.player),a.wn());g.Lb(a.i,function(l){if(l.view){var m=l.annotation;(l=l.view)&&m.segment&&m.segment.i&&
(m=this.i[m.segment.i])&&(l.O=m.annotation)}},a)},ppa=function(a,b){var c=!1;
a.g||(a.g=W1(a),g.G(a,a.g));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())c=!0;c&&(vZ(a.player),a.wn())},opa=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.at();
if(b){var c=g.$s();c&&g.Ms(b,c,[g.Ks(a)])}}},qpa=function(a,b,c,d){d?X1(a,b,c):Y1(a,b,c)},Y1=function(a,b,c){if(b=a.i[b])Z0(b),c&&c.i?(a=(0,g.x)(a.xw,a,b),b.g=new g.M(a,2E3),b.g.start()):a.xw(b)},X1=function(a,b,c){if(b=a.i[b])Z0(b),c&&c.o?(a=(0,g.x)(a.wA,a,b),b.g=new g.M(a,2E3),b.g.start()):a.wA(b)},Z1=function(a,b){var c=a.player.getVideoData();
if(!c.Fl)return!1;var d=f0(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!u1(d))return!1;d=g.mq(d);return d.list||d.p?!1:(d=v1(b))?c.videoId==d?!0:"new"!=b.target&&g.X(a.player).i?!0:!1:!1},kpa=function(a,b){if(rpa(b)){var c=b.o||v0(b,function(d){return"click"==d||"rollOut"==d||"rollOut"==d});
return new Q0(b,(0,g.x)(a.O.appendChild,a.O),a.player,a.ua,c)}return null},rpa=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in u0)if(a.style==u0[b])return!0;return!1},$1=function(a,b,c,d){a.N(B0(b,d),c,d)},U1=function(a,b){return(0,g.x)(function(){if(!this.ea()){var c=Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Sa.apply(window,c);this.M.push(g.aq(b))}},a)};
g.SJ.prototype.Ji=g.da(14,function(a,b){var c=g.TJ(this).l;c&&c.Ji(a,b)});
g.ho.prototype.fq=g.da(0,function(){this.i=this.M.createElement("DIV")});
var Kna=/[^\d]+$/,Lna={cm:1,"in":1,mm:1,pc:1,pt:1},Mna={em:1,ex:1},AZ={},BZ=null;g.y(FZ,g.sf);g.y(GZ,g.Wn);g.h=GZ.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.g)this.progress=0,this.coords=this.i;else if(1==this.g)return!1;CZ(this);this.startTime=a=(0,g.H)();-1==this.g&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.A=this.startTime;this.progress||this.o();this.Vd("play");-1==this.g&&this.Vd("resume");this.g=1;var b=g.Ra(this);b in AZ||(AZ[b]=this);DZ();EZ(this,a);return!0};
g.h.stop=function(a){CZ(this);this.g=0;a&&(this.progress=1);HZ(this,this.progress);this.Vd("stop");this.l()};
g.h.pause=function(){1==this.g&&(CZ(this),this.g=-1,this.Vd("pause"))};
g.h.U=function(){0==this.g||this.stop(!1);this.Vd("destroy");GZ.Xa.U.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Or=function(){this.Vd("animate")};
g.h.Vd=function(a){this.dispatchEvent(new FZ(a,this))};
g.y(IZ,GZ);IZ.prototype.u=g.Ja;IZ.prototype.Or=function(){this.u();IZ.Xa.Or.call(this)};
IZ.prototype.l=function(){this.u();IZ.Xa.l.call(this)};
IZ.prototype.o=function(){this.u();IZ.Xa.o.call(this)};
g.y(JZ,IZ);JZ.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};
g.t(KZ,g.D);KZ.prototype.ca=function(a,b,c,d){c=(0,g.x)(c,d||this.i);a=g.Nr(a,b,c);this.g.push(a);return a};
KZ.prototype.Om=function(a,b,c,d){c=(0,g.x)(c,d||this.i);a=g.Xr(a,b,c);this.g.push(a);return a};
KZ.prototype.Ka=function(a){g.Or(a);g.db(this.g,a)};
KZ.prototype.U=function(){g.Or(this.g);this.g.length=0;g.D.prototype.U.call(this)};g.y(NZ,g.Sf);g.h=NZ.prototype;g.h.Yp=null;g.h.Tj=null;g.h.ga=function(){return this.Tj};
g.h.addEventListener=function(a,b,c,d){g.Cf(this.Tj,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.Mf(this.Tj,a,b,c,d)};
g.h.U=function(){NZ.Xa.U.call(this);var a=this.Tj;if(a)if(g.vf(a))a.me&&g.zf(a.me);else if(a=g.Ff(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.Nf(d[e])&&++b}};g.y(SZ,NZ);SZ.prototype.fill=null;g.y(A_,NZ);B_.prototype.Ee=null;B_.prototype.xd=null;B_.prototype.Wk=!0;var Una=[2,2,6,6,0];g.h=B_.prototype;g.h.clear=function(){this.Ta.length=0;this.Ca.length=0;this.Sd.length=0;delete this.Ee;delete this.xd;delete this.Wk;return this};
g.h.moveTo=function(a,b){0==g.Wa(this.Ta)?this.Sd.length-=2:(this.Ta.push(0),this.Ca.push(1));this.Sd.push(a,b);this.xd=this.Ee=[a,b];return this};
g.h.Zb=function(a){var b=g.Wa(this.Ta);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.Ta.push(1),this.Ca.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Sd.push(c,d)}this.Ca[this.Ca.length-1]+=b/2;this.xd=[c,d]};
g.h.close=function(){var a=g.Wa(this.Ta);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.Ta.push(4),this.Ca.push(1),this.xd=this.Ee);return this};
g.h.clone=function(){var a=new this.constructor;a.Ta=this.Ta.concat();a.Ca=this.Ca.concat();a.Sd=this.Sd.concat();a.Ee=this.Ee&&this.Ee.concat();a.xd=this.xd&&this.xd.concat();a.Wk=this.Wk;return a};
g.h.transform=function(a){if(!this.Wk)throw Error("Non-simple path");a.transform(this.Sd,0,this.Sd,0,this.Sd.length/2);this.Ee&&a.transform(this.Ee,0,this.Ee,0,1);this.xd&&this.Ee!=this.xd&&a.transform(this.xd,0,this.xd,0,1);return this};
g.h.isEmpty=function(){return 0==this.Ta.length};g.y(D_,SZ);g.y(F_,g.ho);F_.prototype.o=null;F_.prototype.Ij=function(){return this.hh?g.Sh(this.ga()):g.Ha(this.width)&&g.Ha(this.height)?new g.wd(this.width,this.height):null};
F_.prototype.resume=function(){};g.y(PZ,m_);g.y(OZ,m_);g.y(G_,A_);G_.prototype.clear=function(){g.Vd(this.ga())};
G_.prototype.setSize=function(a,b){var c=this.ga(),d={width:a,height:b},e;for(e in d)c.setAttribute(e,d[e])};
g.y(H_,D_);var K_;g.y(I_,F_);var Xna=0;g.h=I_.prototype;g.h.fq=function(){var a=QZ(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=QZ(this,"g");this.C=QZ(this,"defs");this.o=new G_(b,this);a.appendChild(this.C);a.appendChild(b);this.i=a;this.l&&(this.ga().setAttribute("preserveAspectRatio","none"),this.R?this.YA():this.ga().setAttribute("viewBox","0 0 "+(this.l?this.l+" "+this.I:"")))};
g.h.YA=function(){if(this.hh){var a=this.Ij();0==a.width?this.ga().style.visibility="hidden":(this.ga().style.visibility="",this.o.ga().setAttribute("transform","scale("+a.width/this.l+" "+a.height/this.I+") translate(0 0)"))}};
g.h.setSize=function(a,b){g.Rh(this.ga(),a,b)};
g.h.Ij=function(){if(!g.Bh)return this.hh?g.Sh(this.ga()):I_.Xa.Ij.call(this);var a=this.width,b=this.height,c=g.Fa(a)&&-1!=a.indexOf("%"),d=g.Fa(b)&&-1!=b.indexOf("%");if(!this.hh&&(c||d))return null;if(c){var e=this.ga().parentNode;var f=g.Sh(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.ga().parentNode,f=f||g.Sh(e),b=parseFloat(b)*f.height/100);return new g.wd(a,b)};
g.h.clear=function(){this.o.clear();g.Vd(this.C);this.g={}};
g.h.xj=function(){I_.Xa.xj.call(this);this.R&&this.P.Ka(Yna(),"tick",this.YA)};
g.h.U=function(){delete this.g;delete this.C;delete this.o;this.P.dispose();delete this.P;I_.Xa.U.call(this)};g.t(M_,g.zK);g.h=M_.prototype;
g.h.load=function(){g.zK.prototype.load.call(this);if(!O_(g.X(this.player).playerStyle)){var a=g.IB(this.player.getVideoData());if(a)a=L_(a,N_(this)),P_(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.o&&this.o.abort();a={method:"POST",Zc:(0,g.x)(this.UI,this,a),Dc:{v:a},withCredentials:!0};"gaming"==g.X(this.player).playerStyle&&(a.Dc.gaming="1");this.P&&(a.Dc.ptype="embedded");var c=this.player.getVideoData().uv;c&&(a.ub={ad_tracking:c});if(b=g.HB(b))if(b=g.Dc(b),b=g.Ac(b))this.o=
g.Fq(b,a)}}};
g.h.unload=function(){P_(this,null);this.o&&(this.o.abort(),this.o=null);g.zK.prototype.unload.call(this)};
g.h.xc=function(a,b){if(!O_(g.X(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=L_(b,"new");P_(this,c);return!0}return null};
g.h.getOptions=function(){return O_(g.X(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.UI=function(a,b){var c=this.o=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=L_(c,N_(this)))}P_(this,c)};
g.h.Wa=function(){if(this.i&&this.i.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<a2.length;f++){var k=Math.abs(b.width-a2[f]);if(-1==e||d>=k)e=f,d=k}d=b2[e];this.l&&g.zh(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.i.elements.length;++b)if(f=this.i.elements[b].id,e=this.g[f],k=this.C[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Rh(e.element,Math.round(k.width*a.width),f);g.Hh(e.element,m,n);g.Un(e.element,spa);m=k.left+k.width/2;k=k.top+l/2;g.J(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Un(e.element,b2);g.J(e.element,d);(e=g.Fd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.zh(e,"height",f+"px")}}}}};
g.h.QE=function(a){if(this.i)if("ytp-ce-in-endscreen"==a.getId())this.H=!1,this.i.skip&&1==this.player.getPlayerState()?(g.aK(this.player,!0),this.player.seekTo(Infinity),this.H=!0):(U_(this,this.i.impressionUrls),(a=g.at())&&this.i.visualElement&&g.Ns(a,this.i.visualElement));else if(!this.H){a=a.getId().substring(15);var b=this.g[a],c=this.C[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.J(b,"ytp-ce-shown");U_(this,c.impressionUrls);
(b=g.at())&&g.Ns(b,c.visualElement);g.X(this.player).rb&&this.player.la("endscreenelementshown",a)}};
g.h.RE=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.H){a=a.getId().substring(15);var b=this.g[a];g.Tn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Tn(b,"ytp-ce-shown");g.X(this.player).rb&&this.player.la("endscreenelementhidden",a)}};
g.h.LL=function(a){var b=this;a.target===window&&(new g.M(function(){for(var c in b.g)g.Un(b.g[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.Ly=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Rn(c,"ytp-ce-element");){g.Rn(c,"subscribe-label")&&V_(this,a);if(g.Rn(c,"ytp-ce-channel-subscribe"))return;c=g.$d(c)}if(!c||g.Rn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.g[a.id])this.Tr(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.ao?(V_(this,a),this.fA(),this.player.pauseVideo(),c=g.Dc(R_(this,a.targetUrl)),c=g.Ac(c),g.rL(c,void 0,a.Xb)):(c=this.player.getVideoData().Nb,
c=(0,g.x)(this.BM,this,c,R_(this,a.targetUrl),a.Xb),c=(0,g.x)(this.fA,this,c),V_(this,a,c))}}};
g.h.BM=function(a,b,c){var d=g.mq(b);a&&d&&(d.v||d.list)?g.VX(this.player.app,d.v,c,d.list,!1,void 0):g.qL(b,c)};
g.h.Zq=function(a,b){g.Rn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.J(a.element,"ytp-ce-element-hover"):g.X(this.player).g?(new g.M(function(){g.J(a.element,"ytp-ce-element-hover")},200)).start():g.J(a.element,"ytp-ce-element-hover"),U_(this,b.VD),T_(this,b.id,!0))};
g.h.Tr=function(a,b){g.Tn(a.element,"ytp-ce-element-hover");g.Tn(a.element,"ytp-ce-force-expand");T_(this,b.id,!1)};
g.h.fA=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var a2=[346,426,470,506,570,640,853,1280,1920],b2="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),spa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var ioa={fO:"current",mP:"new"};var koa={CLOSE:"close",qP:"openUrl",aC:"subscribe"},loa={aO:"click",CLOSE:"close",IO:"hidden",QP:"rollOut",WB:"rollOver",XB:"shown"};var noa={vQ:"xx",wQ:"xy",xQ:"yx",yQ:"yy"};g.t(p0,i0);var soa={vB:"anchored",MP:"rect",TP:"shapeless"};var woa={CLOSED:"closed",zP:"playerControlShow",WB:"rollOver",XB:"shown"};t0.prototype.Jb=function(){var a=Eoa(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
t0.prototype.showLinkIcon=function(){return v0(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var u0={vB:"anchored",yB:"branding",CHANNEL:"channel",eO:"cta",KO:"highlightText",YO:"label",PLAYLIST:"playlist",CP:"popup",XP:"speech",aC:"subscribe",hQ:"title",VIDEO:"video",rQ:"website"},Aoa={yB:"branding",RN:"card",lO:"drawer",JO:"highlight",gP:"marker",HP:"promotion",TEXT:"text",tQ:"widget"},Boa={pQ:"video_relative",AP:"player_relative"};C0.prototype.o=function(a,b,c,d){this.g[a]=b?!c:c;a=g.Pb(this.g,function(e){return e});
this.l!=a&&(this.l=a,this.i.N(this.u,a,d))};D0.prototype.ga=function(){return this.u};
D0.prototype.l=function(){};var H0={bevel:1,dropshadow:2};g.t(M0,D0);
M0.prototype.l=function(a,b){var c=z0(a);if(c){var d=m0(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=y0(a))&&c.g?c.g:null)&&c.length?c[0]:null){var f=g.qh(k0(b,l0(e,new g.nh(e.D,e.F,e.Xi,e.l),b.g))),k=d.clone();c=new g.nh(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.g;k=K0(k,c.effects);l=E0(this,k.width,k.height);m=J0(c,k.width,k.height,this.g);
d=new g.nh(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.ud(f.x-k.left,f.y-k.top);this.o=17*h0(b.g,e.i,e.g?e.g:"xy");e=c.cornerRadius;f=a.g;var p=this.g&&w0(a),r=p?f.borderWidth+1:f.borderWidth;p=(f=r?new E_(r,p?f.i:f.borderColor):null)?f.g/2:0;r=Moa(d,n);var u=this.A(d,e,n,r),A=n.x;n=n.y;var C=d.width,E=d.height,F=d.left;d=d.top;var L=new B_;L.moveTo(F+e+p,d+p);"t"==r&&(L.Zb(u.start,d+p),L.Zb(A,n),L.Zb(u.end,d+p));L.Zb(F+C-e-p,d+p);C_(L,e,e,-90);"r"==r&&(L.Zb(F+C-p,u.start),L.Zb(A,n),L.Zb(F+
C-p,u.end));L.Zb(F+C-p,d+E-e-p);C_(L,e,e,0);"b"==r&&(L.Zb(u.end,d+E-p),L.Zb(A,n),L.Zb(u.start,d+E-p));L.Zb(F+e+p,d+E-p);C_(L,e,e,90);"l"==r&&(L.Zb(F+p,u.end),L.Zb(A,n),L.Zb(F+p,u.start));L.Zb(F+p,d+e+p);C_(L,e,e,180);L.close();J_(l,L,f,m);if(m=this.ga())g.J(m,"annotation-shape"),g.J(m,"annotation-speech-shape"),g.Hh(m,k.left,k.top),g.Rh(m,k.width,k.height),L0(l,m,c.effects)}}}};
M0.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=g.qd(k-f/2,l+b,l+m-f-b);return new g.Bi(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Bi(0,0)};g.t(N0,D0);N0.prototype.l=function(a,b){var c=z0(a);if(c){var d=m0(c,b);if(!(0>=d.width||0>=d.height)){var e=a.g;c=K0(d,e.effects);var f=E0(this,c.width,c.height),k=new E_(!e.l&&this.g?1:e.l,e.bgColor),l=new OZ("#000",0);d=I0(new g.nh(0,0,d.width,d.height),e.cornerRadius,k?k.g/2+1:0);J_(f,d,k,l);f=this.ga();g.J(f,"annotation-shape");e=e.g;xZ(f,this.g?Math.max(e,.9):e);g.Hh(f,c.left,c.top);g.Rh(f,c.width,c.height)}}};g.t(O0,D0);
O0.prototype.l=function(a,b){var c=z0(a);if(c){var d=m0(c,b);if(!(0>=d.width||0>=d.height)){c=a.g;var e=K0(d,c.effects),f=E0(this,e.width,e.height),k=new g.nh(0,0,d.width,d.height);d=J0(c,d.width,d.height,this.g);var l=c.cornerRadius;var m=a.g;var n=this.g&&w0(a),p=n?m.borderWidth+1:m.borderWidth;m=p?new E_(p,n?m.i:m.borderColor):null;k=I0(k,l,m?m.g/2+1:0);J_(f,k,m,d);if(k=this.ga())g.J(k,"annotation-shape"),g.J(k,"annotation-popup-shape"),g.Hh(k,e.left,e.top),g.Rh(k,e.width,e.height),L0(f,k,c.effects)}}};g.t(P0,M0);P0.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=k<=l+m/2?Math.max(l+m/4-f/2,l+b):Math.min(l+3*m/4-f/2,l+m-f-b);return new g.Bi(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.Bi(0,0)};g.t(Q0,g.D);g.h=Q0.prototype;g.h.xx=function(){this.F||(this.o&&g.Th(this.o,!0),this.u&&g.Th(this.u,!0),this.l&&(this.l.g=!0,xZ(this.i,V0(this)?1:0),this.l.l(this.g,S0(this))),this.D.isActive()&&this.D.stop(),this.F=!0,this.H=this.aa.Om(g.YJ(this.A),"mouseleave",function(a){this.qn.stop();this.Dg(a)}))};
g.h.Dg=function(){this.F&&(this.M?this.D.start():this.yw(),this.l&&(this.l.g=!1,xZ(this.i,V0(this)?1:0),this.l.l(this.g,S0(this))),this.F=!1,this.H&&(this.aa.Ka(this.H),this.H=null))};
g.h.yw=function(){this.o&&g.Th(this.o,!1);this.u&&g.Th(this.u,!1)};
g.h.IF=function(a){this.ba=a;this.qn.Rj()};
g.h.xD=function(){var a=this.ba,b=new g.ud(a.clientX,a.clientY),c=g.Lh(this.A.getRootNode()),d=W0(c,this.P);c=(this.u&&yZ(this.u)||this.o&&yZ(this.o))&&W0(c,this.M);d&&d.contains(b)||c&&c.contains(b)?this.xx(a):this.Dg(a)};
g.h.show=function(){var a=this.g.g;a=(a&&0==a.g||"title"==this.g.style||"highlightText"==this.g.style?!1:!0)&&!this.l;var b=!this.i;if(a){var c=S0(this),d=null;"highlight"==this.g.type||"label"==this.g.style?d=new N0:"popup"==this.g.style?d=new O0:"anchored"==this.g.style?d=new M0:"speech"==this.g.style&&(d=new P0);d&&(d.l(this.g,c),this.l=d,c=d.ga())&&(g.Th(c,!1),g.J(c,"annotation-type-"+this.g.type.toLowerCase()),this.R(c))}if(b){c=["annotation"];"highlightText"!=this.g.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.g.type.toLowerCase());this.i=g.Rd("DIV",c);g.Th(this.i,!1);this.g.l&&(this.C=g.Rd("DIV","inner-text"),"label"==this.g.style&&(g.J(this.C,"player-label-text"),this.C.style.backgroundColor=this.g.g.bgColor),g.be(this.C,this.g.l),this.i.appendChild(this.C));g.Fp(this.i,"annotation_id",this.g.id);this.R(this.i);Noa(this,this.i);if(w0(this.g)&&this.g.showLinkIcon()){if(d=this.g.Jb())c=this.i,d=new g.Nm(f0(d)),c.title=d.g+d.i;this.u=g.Rd("SPAN","annotation-link-icon");g.Th(this.u,
!1);this.i.appendChild(this.u)}Ooa(this);w0(this.g)||(this.i.style.cursor="default")}if(a||b){a:{a=this.g.segment.g;if(a.length&&(a=r0(a[0]))){a=a.u;break a}a=0}this.i&&(this.i.style.zIndex=a);this.l&&this.l.ga()&&(this.l.ga().style.zIndex=a)}g.Th(this.i,!0);xZ(this.i,V0(this)?1:0);U0(this);this.l&&this.l.ga()&&g.Th(this.l.ga(),!0)};
g.h.hide=function(){this.i&&g.Th(this.i,!1);this.l&&this.l.ga()&&g.Th(this.l.ga(),!1);this.I&&(this.aa.Ka(this.I),this.I=null)};g.t(X0,g.D);g.h=X0.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(Y0(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.i.subscribe("resize",this.wx,this),this.i.subscribe("onVideoAreaChange",this.kz,this))};
g.h.destroy=function(){if(this.view){Y0(this);var a=this.view,b=a.aa;g.Or(b.g);b.g.length=0;a.qn.dispose();a.D.dispose();a.i&&g.Xd(a.i);a.l&&a.l.ga()&&g.Xd(a.l.ga())}Z0(this)};
g.h.kz=function(){U0(this.view)};
g.h.wx=function(){U0(this.view)};i1.prototype.l=function(a,b){var c=g.ge(b.target,"label");c&&g.K(c,"iv-card-poll-choice-focused",a)};
i1.prototype.u=function(a,b){var c=g.ge(b.target,null,"iv-card-poll",void 0);if(c)if(a.Od)g.Hd("iv-card-sign-in-button",c).click();else{var d=parseInt(Ona(b.target),10);if(null==a.he)a.choices[d].count++,a.he=d;else if(a.he!=d){var e=a.choices[a.he];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.he=d}else e=a.choices[a.he],e.count=Math.max(e.count-1,0),a.he=null;k1(a,c);g.Jq(this.g.videoData.Ed,{Dc:{action_poll_vote:1},ub:{poll_id:a.id,index:d,session_token:a.hN}});e1(this.g.logger,a.bb,void 0,
{"link-id":d},a.qd.click,5);(c=g.at())&&a.rf&&g.Os(c,a.rf)}};g.t(x1,g.D);g.h=x1.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.KD(a,b,{id:c});g.G(this,a);a.namespace="annotations_module";d&&tZ(a).subscribe("onEnter",d,this);e&&tZ(a).subscribe("onExit",e,this);g.eK(this.context.Y,[a])};
g.h.Vn=function(){this.context.i.subscribe("resize",this.Ll,this)};
g.h.ga=function(){return this.Ba};
g.h.Ni=function(a,b,c,d,e,f,k){this.context.g.ca(a,"click",g.Sa(this.Nm,b,c,d,e,f||[],k||0),this);this.context.g.ca(a,"touchstart",g.Sa(function(){this.lt=!1}),this);
this.context.g.ca(a,"touchmove",g.Sa(function(){this.lt=!0}),this)};
g.h.Nm=function(a,b,c,d,e,f,k){if(this.lt)return!1;k&&(k.stopPropagation(),k.preventDefault());$oa(this,a,c,d,e,f);return!1};
g.h.show=function(){this.X=(0,g.H)()};
g.h.hide=function(){};
g.h.destroy=function(){g.Xd(this.ga())};
g.h.Ll=function(){};g.t(A1,x1);g.h=A1.prototype;g.h.isAvailable=function(){var a;if(a=!!this.l.length)(a=this.i.getRootNode())?(a=g.Sh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Ll=function(){var a=this.isAvailable();g.Th(this.ga(),a);g.K(this.context.Y.getRootNode(),"ytp-iv-drawer-enabled",a);vZ(this.i)};
g.h.destroy=function(){this.i.Ji(!1);this.i.getRootNode().removeChild(this.A);g.Qp(this.I);g.Or(this.ba);this.Z&&this.Z.dispose();this.C&&this.C.dispose();x1.prototype.destroy.call(this)};
g.h.gF=function(a){this.M.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.o.scrollTop+=a};
g.h.lA=function(a){if(!g.Rn(this.i.getRootNode(),"ytp-cards-teaser-shown")){if(this.g!=a){var b=g.at(),c=this.g?this.g.Fb.de:this.H;b&&c&&MZ(b,[c]);this.g=a;C1(this)}yZ(this.ga())&&(2==this.context.Y.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.Y.getAdState():void 0):(b=isNaN(void 0)?this.context.Y.getPlayerState():void 0,b=1==b||0==b&&0===this.context.Y.getCurrentTime()),b&&a.Fb.teaserDurationMs&&this.i.Ji(!0,{teaserText:a.Fb.teaserText,durationMs:a.Fb.teaserDurationMs}));this.ka.isActive()||
((!this.u||!this.M.isActive()&&this.V)&&E1(this,a),this.ka.start(910+a.Fb.teaserDurationMs))}};
g.h.uM=function(a){this.u||(this.g=a,C1(this),E1(this,a),y1(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.wC=function(){if(this.u){g1(this.context.logger,this.R,4,F1(this).qd.close);var a=g.at();a&&this.P&&g.Os(a,this.P);z1(this)}};
g.h.HC=function(){g.K(this.A,"iv-drawer-scrolled",0<this.o.scrollTop)};
g.h.qE=function(){var a=g.at(),b=F1(this);b=b?b.de:this.H;a&&b&&LZ(a,[b])};
g.h.pE=function(){var a=g.at(),b=F1(this);b=b?b.de:this.H;a&&b&&MZ(a,[b])};
g.h.tE=function(){var a=F1(this);h1(this.context.logger,8,a.bb,a.qd.IM);var b=g.at();b&&a&&LZ(b,[a.af,a.de])};
g.h.sE=function(){var a=g.at(),b=F1(this);a&&b&&MZ(a,[b.af])};
g.h.rE=function(a){var b=F1(this),c=g.at();this.g?a?(a=this.context.logger,h1(a,9,b.bb,b.qd.Ps),a.g.sendVideoStatsEngageEvent(4,void 0),c&&b.af&&g.Os(c,b.af)):(a=this.context.logger,h1(a,12,b.bb,b.qd.Ps),a.g.sendVideoStatsEngageEvent(4,void 0),c&&b.de&&g.Os(c,b.de)):(a=this.context.logger,g1(a,this.R,12,b.qd.Ps),a.g.sendVideoStatsEngageEvent(4,void 0),c&&this.H&&g.Os(c,this.H))};g.t(G1,x1);G1.prototype.Vn=function(){x1.prototype.Vn.call(this);hpa(this)};
G1.prototype.show=function(){x1.prototype.show.call(this);var a=g.at(),b=this.annotation.data;a&&b&&(b=b.session_data)&&LZ(a,[g.Ks(b.itct)])};
G1.prototype.hide=function(){x1.prototype.hide.call(this);var a=g.at(),b=this.annotation.data;a&&b&&(b=b.session_data)&&MZ(a,[g.Ks(b.itct)])};g.t(H1,G1);g.h=H1.prototype;g.h.CM=function(a,b,c,d){this.l.stop();if(!this.o){var e=g.Sh(a);this.g||(g.Qh(a,e.width),g.Qh(b,e.width));g.zh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.zh(c,"right","1px");this.o=!0;g.Th(a,!0);this.A=new g.M(function(){g.J(this.ga(),"iv-branding-active")},0,this);
this.A.start()}};
g.h.TD=function(a,b){g.Tn(this.ga(),"iv-branding-active");this.C=new g.M((0,g.x)(function(){g.Th(a,!1);this.g||g.Qh(b,0)},this),250);
this.C.start();this.o=!1};
g.h.show=function(){if(!this.isActive){G1.prototype.show.call(this);if(!this.D){g.J(this.ga(),"iv-branding");var a=this.annotation.data;this.u=a.image_width;this.i=g.Rd("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Th(this.i,!1);var b=g.Rd("DIV","branding-img-container",this.i);this.ga().appendChild(b);var c=g.Rd("DIV","iv-branding-context-name");g.be(c,a.channel_name);var d=g.Rd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.g=
new g.PV(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.Y),this.g.g(d);b=g.Rd("DIV","iv-branding-context-subscribe-caret");c=g.Rd("DIV","branding-context-container-inner",b,c,d);g.Th(c,!1);d=g.Rd("DIV","branding-context-container-outer",c);g.zh(d,"right",this.u+"px");this.ga().appendChild(d);var e=this.annotation.Jb();e&&this.Ni(this.i,e,this.annotation.id,a.session_data,
this.annotation.bb);this.l=new g.M(g.Sa(this.TD,c,d),500,this);g.G(this,this.l);this.context.g.ca(this.ga(),"mouseover",(0,g.x)(this.CM,this,c,d,b,a.image_height));this.context.g.ca(this.ga(),"mouseout",(0,g.x)(this.l.start,this.l,void 0));this.D=!0}d1(this.context.logger,this.annotation.bb);g.Th(this.ga(),!0);this.isActive=!0;if(this.i){a=this.i;var f=void 0===f?0:f;b=wZ(a).width;c=g.Ha(void 0)?void 0:b;g.Hh(a,c);f=new JZ(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,Qna);g.G(this,f);this.context.l.ca(f,
"begin",g.Sa(g.Th,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(G1.prototype.hide.call(this),g.Th(this.ga(),!1),this.isActive=!1)};
g.h.destroy=function(){this.g&&(this.g.dispose(),this.g=null);G1.prototype.destroy.call(this)};g.t(I1,G1);g.h=I1.prototype;g.h.show=function(){this.isActive||(G1.prototype.show.call(this),this.H||(ipa(this),this.H=!0),g.Th(this.ga(),!0),this.annotation&&this.annotation.bb&&d1(this.context.logger,this.annotation.bb),g.Gg(function(){g.Tn(this.ga(),"iv-promo-inactive")},100,this),this.ga().removeAttribute("aria-hidden"),this.isActive=!0,L1(this),K1(this),M1(this,this.C))};
g.h.hide=function(){this.isActive&&(g.J(this.ga(),"iv-promo-inactive"),this.isActive=!1,this.ga().setAttribute("aria-hidden",!0))};
g.h.Nm=function(a,b,c,d,e,f,k){return this.u?!1:G1.prototype.Nm.call(this,a,b,c,d,e,f,k)};
g.h.hq=function(a,b){b.stopPropagation();K1(this);M1(this,a);this.g.focus()};
g.h.zD=function(a){this.F=!0;this.hq(500,a)};
g.h.yD=function(){this.F=!1;J1(this)};
g.h.qD=function(a){a.stopPropagation();this.hide();f1(this.context.logger,this.annotation.bb)};
g.h.rD=function(a){a.stopPropagation();L1(this);this.u=!0;g.J(this.ga(),"iv-promo-collapsed-no-delay");this.A.start();f1(this.context.logger,this.annotation.bb)};
g.h.destroy=function(){this.A.dispose();G1.prototype.destroy.call(this)};g.t(N1,g.zK);g.h=N1.prototype;g.h.xc=function(a,b){if(!O1(g.X(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.Vn(b);c&&T1(this,c);return!0;case "removeCustomAnnotationById":return b&&this.g&&(D1(this.g,b),vZ(this.player)),!0}return null};
g.h.getOptions=function(){return O1(g.X(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.wn=function(){if(this.o){var a=g.YJ(this.player).getVideoContentRect(!0);g.Rh(this.o.element,a.width,a.height);g.Hh(this.o.element,a.left,a.top)}if(this.g){var b=g.cK(this.player);a=this.g;b=b.width;g.K(a.A,"iv-drawer-small",426>=b);g.K(a.A,"iv-drawer-big",1280<=b)}};
g.h.iK=function(a){this.gc(a.state);g.U(a.state,2)&&(this.ud()&&this.De()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Ji(!1))};
g.h.load=function(){g.zK.prototype.load.call(this);this.gc(g.XJ(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.VI,this,b,this.H),d=(0,g.x)(function(){this.C=null},this);
g.cq()&&(c=U1(this,c));c={format:"XML",Zc:c,onError:d,Dc:{}};a.isPharma&&(c.Dc.pharma="1");c.method="POST";c.withCredentials=!0;d=g.X(this.player);"gaming"==d.playerStyle&&(c.Dc.gaming="1");(b=d.I.get(b))&&V1(c,b);b=b&&(b.Rl||b.Ql);if(!a.El||b)a.Ed?P1(this,a.Ed,c):(this.l=(0,g.x)(this.PE,this,c),this.player.addEventListener("videodatachange",this.l));g.lK(this.player,this.o.element,4);this.wn();(a=a.Qa&&a.Qa.cards&&a.Qa.cards.cardCollectionRenderer||null)&&ppa(this,a)};
g.h.gc=function(a){a=!a.isCued()&&!g.U(a,1024);g.NC(this.u,a);g.NC(this.o,a)};
g.h.PE=function(a){var b=this.player.getVideoData();b.Ed&&(this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null),P1(this,b.Ed,a))};
g.h.unload=function(){Soa(this.D);g.hK(this.player,"annotations_module");g.Lb(this.i,function(a){a.destroy()});
g.Lb(this.P,function(a){a.destroy()});
this.F=null;this.g&&(this.g.destroy(),this.g=null,vZ(this.player));this.I=!1;this.C&&(this.C.abort(),this.C=null);this.i={};this.P={};this.u.hide();g.zK.prototype.unload.call(this);g.MC(this.o);this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null)};
g.h.VI=function(a,b,c){this.C=null;if(!R1(this,b,a)&&(a=g.zq(c)&&c.responseXML?c.responseXML:null)){T1(this,a);g.J(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.i){b=this.i[d].annotation;if(b.segment)if(c=b.segment,c.g.length)if(c=c.g[0].i||c.g[0].g||c.g[0].l,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.l,f.visible=!0);b=new g.KD(c,e,f);a.push(b)}}g.eK(this.player,a)}};
g.h.jz=function(a){a==this.player.getVideoData().videoId&&(this.loaded?npa(this):this.load())};
g.h.ME=function(a){a=a.getId();var b=this.i[a];b&&!b.l&&(b=b.annotation,X1(this,a),d1(this.D,b.bb))};
g.h.NE=function(a){Y1(this,a.getId())};
g.h.xw=function(a){a&&(a.hide(),$1(this,"shown",!1,a.annotation.id),this.Zl(a.annotation,"hidden"))};
g.h.wA=function(a){a&&(a.show(),$1(this,"shown",!0,a.annotation.id),this.Zl(a.annotation,"shown"))};
g.h.wL=function(a,b,c){var d=this.i[a];if(d&&b.value!=c){b.value=c;var e=!1;x0(d.annotation,function(f){e=e||f.value});
qpa(this,a,b,e)}};
g.h.aI=function(a){if(a&&a.id){var b=a.Jb();if(b){var c=f0(b);if(c){var d=(0,g.x)(this.Zl,this,a,"click");if("new"==w1(c,b.target)||Z1(this,b))d(),d=null;e1(this.D,a.bb,d)}}}};
g.h.Zl=function(a,b){Doa(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!Z1(this,c.url))){e=v1(c.url);var f=Xoa(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=S1(this).Y,g.VX(d.app,e,void 0,void 0,void 0,void 0),f&&S1(this).Y.dc()&&S1(this).Y.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.X(this.player),(d=f0(c.url))?(f=t1(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Sa(Yoa,e.pageId,e.hc),d=new g.Nm(d),e=e(d.i),d.i=e,d=d.toString())):d=null,d&&
(this.player.pauseVideo(),c=w1(d,c.url.target),e=a.itct,"ei"in g.mq(d)&&(d=g.hh(d,"ei")),g.rL(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.dJ=function(){$1(this,"playerControlShow",!1)};
g.h.YK=function(){$1(this,"playerControlShow",!0)};
g.h.OE=function(a){$1(this,"rollOver",!0,a.id)};
g.h.Dg=function(a){$1(this,"rollOver",!1,a.id)};
g.h.DI=function(a){a&&a.id&&(this.i[a.id].l=!0,Y1(this,a.id),f1(this.D,a.bb),this.Zl(a,"close"),$1(this,"closed",!0,a.id))};
g.h.ud=function(){return!!this.g&&this.g.isAvailable()};
g.h.De=function(){this.ud();return!!this.g&&this.g.u};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.ud();this.g&&(a?c?y1(this.g,c,b):y1(this.g,"YOUTUBE_DRAWER_AUTO_OPEN",b):z1(this.g))};
g.h.Ji=function(a,b){this.player.N(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.U=function(){g.X(this.player).I.unsubscribe("vast_info_card_add",this.jz,this);g.Tn(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.M,b=0,c=a.length;b<c;b++)g.dq(a[b]);this.M.length=0;g.zK.prototype.U.call(this)};g.XU.annotations_module=N1;g.XU.creatorendscreen=M_;})(_yt_player);
