(function(g){var window=this;var c2=function(a){var b={languageCode:a.i,languageName:a.l,displayName:g.tz(a),kind:a.o,name:a.u,id:a.H,is_servable:a.C,is_default:a.isDefault,is_translateable:a.D,vss_id:a.A};a.g&&(b.translationLanguage=a.g);return b},d2=function(a){return a.g?a.g.languageCode:a.i},tpa=function(a,b){var c=new g.sz;
c.i=a.i;c.l=a.l;c.u=a.u;c.o=a.o;c.isDefault=!1;c.C=a.C;c.D=a.D;c.A=a.A;c.F=a.F;c.g=b;return c},e2=function(a){if(!upa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(vpa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},wpa=function(){this.i=[];
this.g=[]},f2=function(a,b){return b?a.g.concat(a.i):a.g},g2=function(a,b){switch(b.o){case "asr":var c=a.i;
g.Ya(c,(0,g.x)(b.ar,b))||c.push(b);break;default:c=a.g,g.Ya(c,(0,g.x)(b.ar,b))||c.push(b)}},h2=function(){g.D.call(this);
this.i=new wpa;this.u=[]},i2=function(a,b,c){h2.call(this,a);
this.g=null;this.u=b.Fu;this.l=c},j2=function(){this.Ta=[]},k2=function(a,b,c,d,e,f){g.D.call(this);
this.I=a;this.o=b;this.A=new j2;this.g=null;this.F=d;this.P=f;this.i=this.l=null;this.D=c;this.C=e||!1;this.H=new g.M(this.Uw,1E3,this);g.G(this,this.H);this.u=new g.rs(this);g.G(this,this.u);g.Q(g.X(b).experiments,"html5_disable_captions_seek_complete")?this.u.K(b,"seekto",this.Ex):this.u.K(b,"seekcomplete",this.VF);this.Ex(b.getCurrentTime());this.Uw()},l2=function(a,b){b-=a.o.Ib();
var c=a.g;a.g=g.Wa(a.D.zf(b).g);c!=a.g&&a.P&&a.P()},m2=function(a,b){var c=g.Bv(b,a.I,{}).Jb(),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.i=g.er(c,d,3,100).then((0,g.x)(a.EK,a));a.l=b;c=a.A;d=a.l.g[0].i;var e=g.pb(c.Ta,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Ta[e-1]&&e<c.Ta.length&&1==c.Ta[e]-d?(g.cb(c.Ta,e),g.cb(c.Ta,e-1)):0<e&&1==d-c.Ta[e-1]?c.Ta[e-1]=d:e<c.Ta.length&&1==c.Ta[e]-d?c.Ta[e]=d:(g.lb(c.Ta,e,0,d),g.lb(c.Ta,e+1,0,d)))},n2=function(a,b){h2.call(this,g.X(b));
this.g=a;this.C=b;this.l=null;this.o=!1;this.A=g.dz(g.X(this.C))&&!this.g.i},o2=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.QU(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.sz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},xpa=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},p2=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.QU(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},q2=function(a,b,c,d,e){h2.call(this,e||null);
c=c||g.mq(a).hl||"";c=c.split("_").join("-");this.o=g.oq(a,{hl:c});this.l=b;this.A=!!d;this.C={};this.g=null},r2=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.KD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.l=f;this.g=k},s2=function(a,b,c,d,e){g.KD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.g=[]},u2=function(a){a=void 0===a?{}:a;
var b="_"+t2++;return new s2(0,0x8000000000000,0,b,a)},w2=function(a,b,c,d,e,f){var k={};
g.Ta(k,b);g.Ta(k,a.params);g.Ta(k,c);var l={};g.Ta(l,b.wb);a.params.wb&&g.Ta(l,a.params.wb);g.Ta(l,c.wb);k.wb=l;g.W.call(this,{B:"div",G:"caption-window",L:{id:"caption-window-"+a.id,dir:1==k.ze?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{B:"span",G:"captions-text",L:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.O=!1;this.o=a;this.V=this.R=null;this.Pa=e;this.La=f;this.D=null;this.X=.96*e;this.wa=.96*f;this.l=k;this.Ia=c;this.A=this.i["captions-text"];this.Ba=
null!=this.A.style["box-decoration-break"]||null!=this.A.style["-webkit-box-decoration-break"];this.Z=d/360*16;this.type=0;this.ka=this.Z*v2(l);a=new g.Bs(this.element,!0);g.G(this,a);a.subscribe("dragstart",this.UF,this);a.subscribe("dragmove",this.TF,this);a.subscribe("dragend",this.SF,this);this.va=this.ma=0;b="";this.l.windowOpacity&&(a=e2(this.l.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");a={"background-color":b,display:!1===this.l.isVisible?"none":"","text-align":ypa[this.l.textAlign]};
this.Ba&&(a["border-radius"]=b?this.ka/8+"px":"");if(this.u=2==this.o.params.ze||3==this.o.params.ze)b=this.element,c="vertical-rl",1==this.l.HA&&(c="vertical-lr"),g.Md&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.zh(b,"-o-writing-mode",c),g.zh(b,"-webkit-writing-mode",c),g.zh(b,"writing-mode",c),g.zh(b,"text-orientation","upright"),g.J(b,"ytp-vertical-caption"),3==this.o.params.ze&&(g.zh(b,"text-orientation",""),g.zh(b,"transform","rotate(180deg)"));g.zh(this.element,a);switch(this.l.Xf){case 0:case 1:case 2:g.J(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.J(this.element,"ytp-caption-window-bottom")}},v2=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},x2=function(a,b){var c={},d=b.background?b.background:a.l.wb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.wb.backgroundOpacity;d=e2(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ba&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ka/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Z*v2(b)+"px";d=1;e=b.color||a.l.wb.color;if(b.color||null!=b.textOpacity)e=e2(e),d=null==b.textOpacity?a.l.wb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Nu&&(k=e=b.Nu);var l=a.Z/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Nq()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.wb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Qe&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.SD&&(c.visibility="hidden");1==b.UD&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.fz||g.gz,3==a.o.params.ze?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.ye||2==b.ye||3==b.ye||4==b.ye||5==b.ye)if(g.fz)c["font-weight"]="bold";else switch(c["text-emphasis"]="filled circle",c["webkit-text-emphasis"]="filled circle",b.ye){case 4:case 3:c["text-emphasis-position"]="under right";c["webkit-text-emphasis-position"]="under right";break;
case 5:case 2:c["text-emphasis-position"]="over left",c["webkit-text-emphasis-position"]="over left"}return c},y2=function(a){a.D=g.Sd("SPAN");
g.zh(a.D,{display:"block"});g.J(a.D,"caption-visual-line");a.A.appendChild(a.D)},z2=function(a,b){var c=g.Sd("SPAN");
g.zh(c,{display:"inline-block","white-space":"pre-wrap"});g.zh(c,x2(a,b));c.classList.add("ytp-caption-segment");a.D.appendChild(c);c.previousElementSibling&&(g.zh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.zh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},A2=function(a,b,c){a.O=a.O||!!c;
var d={};g.Ta(d,a.l.wb);g.Ta(d,c||b.g);g.Ta(d,a.Ia.wb);(c=!a.D)&&y2(a);for(var e=a.R&&a.V&&g.bc(d,a.V)?a.R:z2(a,d),f=g.Fa(b.text),k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.l,n=k[l];m&&!c?(y2(a),e=z2(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Td(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.fz||!g.Dh(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.Dh(n.children[2],"text-emphasis-position")&&(m=a.u?"padding-left":"padding-bottom"),g.Od?g.zh(e,m,"1em"):
g.zh(e,m,"0.5em")))}a.V=d;a.R=e;a.C.push(b)},B2=function(){},D2=function(){this.o=this.i=this.mode=this.l=0;
this.u=new C2(this);this.A=new C2(this);this.g=[];this.clear()},zpa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Il:a,
Jl:b,result:0};a=E2[a];b=E2[b];if(a&128){if(!(b&128)&&0!=c.g&&c.i==b)return{Il:a,Jl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Il:a,Jl:b,result:2};return{Il:a,Jl:b,result:3}},Apa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.o&&a.reset(),a.u.g.clear(),a.A.g.clear()):(a.o=0,F2(a.u,b,c,d))},Bpa=function(a,b){a.g.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.i=d.time;0==d.type?Apa(a,d.Hu,d.Iu,b):1==d.type&&a.l&496&&F2(a.A,d.Hu,d.Iu,b)}a.g.length=0},G2=function(){this.g=0},H2=function(){this.i=this.l=this.g=0},I2=function(){this.timestamp=this.Qd=0},J2=function(a){this.l=[];
for(var b=0;15>=b;b++){this.l[b]=[];for(var c=0;32>=c;c++)this.l[b][c]=new I2}this.g=this.i=this.row=0;this.style=new G2;this.u=a;this.o=0},K2=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.u.i+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.l[m][p];
if(0!=r.Qd){0==c&&(c=m,d=p);n=String.fromCharCode(r.Qd);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.Qd||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.u(c,d,e,l,f)}else for(d=c=0,f=e=a.u.i+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.l[k][m],r=p.Qd,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),u=p.timestamp,u<=e&&(e=u),l+=n,p.reset()),32==m||0==r)l&&b.u(c,d,e,f,l),e=f,l="",d=c=0},Gpa=function(a,b){switch(a){case 0:return Cpa[(b&127)-32];
case 1:return Dpa[b&15];case 2:return Epa[b&31];case 3:return Fpa[b&31]}return 0},L2=function(a){return a.l[a.row][a.i]},M2=function(a,b,c){2<=b&&1<a.i&&(--a.i,L2(a).Qd=0);
var d=L2(a);d.timestamp=a.u.i+0;d.Qd=Gpa(b,c);32>a.i&&a.i++},N2=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.l[b+e][f].jg(a.l[c+e][f])},O2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.l[b+d][e].reset()},P2=function(a){a.row=0<a.g?a.g:1;
a.i=1;O2(a,0,15)},Q2=function(a){this.o=a;
this.u=0;this.style=new G2;this.A=new J2(a);this.C=new J2(a);this.D=new J2(a);this.i=this.A;this.l=this.C;this.g=this.i},R2=function(a,b,c){var d=a.i,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:K2(d,c),P2(a.i),P2(a.l),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.o.mode=1<<d.o;e?d.i=1:d.g!=b&&(d.g>b?(K2(d,c),O2(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},S2=function(a){a.style.set(1);
a.g=a.l;a.g.g=0;a.g.style=a.style;a.o.mode=1<<a.g.o},T2=function(a){a.style.set(4);
a.g=a.D;a.g.style=a.style;a.o.mode=1<<a.g.o},C2=function(a){this.i=a;
this.g=new H2;this.u=0;this.l=new Q2(a);this.A=new Q2(a);this.o=this.l},F2=function(a,b,c,d){a.g.update();
b=zpa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Il;c=b.Jl;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.o.g,b&96&&M2(a,0,b),c&96&&M2(a,0,c),0!=b&&0!=c&&3==a.style.g&&K2(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.l=e,b.i=c,b.g=2,b=e&8?a.A:a.l,a.o=b,a.i.mode=1<<(a.u<<2)+(b.u<<1)+(4==b.style.g?1:0),(a.i.mode|1<<(a.u<<2)+(b.u<<1)+(4!=b.style.g?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;N2(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));O2(c,b,e)}}c.row=d;c.i=a+1}else switch(e&7){case 1:switch(c&112){case 32:M2(b.g,0,32);break a;case 48:57==c?(d=b.g,L2(d).Qd=0,32>d.i&&d.i++):M2(b.g,1,c&15)}break;case 2:c&32&&M2(b.g,2,c&31);break;case 3:c&32&&M2(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:S2(b);break;case 33:d=
b.g;1<d.i&&(--d.i,L2(d).Qd=0);break;case 36:d=b.g;b=L2(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.l[a][c]==b){for(;32>=c;c++)d.l[a][c].reset();break}break;case 37:R2(b,2,d);break;case 38:R2(b,3,d);break;case 39:R2(b,4,d);break;case 40:M2(b.g,0,32);break;case 41:b.style.set(2);b.g=b.i;b.g.g=0;b.g.style=b.style;b.o.mode=1<<b.g.o;break;case 42:d=b.D;d.g=15;d.style.set(4);P2(d);T2(b);break;case 43:T2(b);break;case 44:a=b.i;switch(b.style.get()){case 1:case 2:case 3:K2(a,d)}O2(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.i=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;K2(a,d);N2(a,b,b+1,a.g-1);O2(a,a.row,1)}break;case 46:O2(b.l,0,15);break;case 47:K2(b.i,d),b.l.updateTime(b.o.i+0),d=b.l,b.l=b.i,b.i=d,S2(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.g,32<(d.i+=c&3)&&(d.i=32)}}},U2=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.bd){var n=f[1],p=f[2],r=f[3];l.getAttribute("p");l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");r.getAttribute("t");f=g.Sd("RUBY");l=l.textContent;var u=g.Sd("SPAN");u.innerText=l;f.appendChild(u);n.getAttribute("p");u=g.Sd("RP");l=n.textContent;u.innerText=l;f.appendChild(u);k=k[p.getAttribute("p")];l=p.textContent;p=g.Sd("RT");p.innerText=l;f.appendChild(p);l=k.bd;if(10==l||11==l||12==l||13==l||14==l)if(g.zh(p,"text-emphasis","filled circle"),g.zh(p,"webkit-text-emphasis","filled circle"),
k.bd==k.bd==11||13==k.bd)g.zh(p,"webkit-text-emphasis-position","under left"),g.zh(p,"text-emphasis-position","under left");if(4==k.bd||7==k.bd||12==k.bd||14==k.bd)g.zh(f,"ruby-position","over"),g.zh(f,"-webkit-ruby-position","before");else if(5==k.bd||6==k.bd||11==k.bd||13==k.bd)g.zh(f,"ruby-position","under"),g.zh(f,"-webkit-ruby-position","after");r.getAttribute("p");l=r.textContent;r=g.Sd("RP");r.innerText=l;f.appendChild(r);return new r2(a,b,e,c,f,d,m)}switch(m.bd){case 9:case 10:m.ye=1;break;
case 11:m.ye=2;break;case 12:m.ye=3;break;case 13:m.ye=4;break;case 14:m.ye=5}return new r2(a,b,e,c,l.textContent||"",d,m)},V2=function(){g.D.apply(this,arguments)},W2=function(a){V2.call(this);
this.l={};this.F={};this.H={};this.u="_"+t2++;this.A=a;this.D={};this.i=this.g=null;this.C=!0},X2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},Y2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},Z2=function(a,b){var c=X2(a,b);
return void 0!=c?c:null},a3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return $2.test(c),c},b3=function(a,b){var c={},d=b.getAttribute("ws");
g.Ta(c,d?a.H[d]:a.A);d=Z2(b,"mh");null!=d&&(c.Vq=d);d=Z2(b,"ju");null!=d&&(c.textAlign=d);d=Z2(b,"pd");null!=d&&(c.ze=d);d=Z2(b,"sd");null!=d&&(c.HA=d);d=a3(b,"wfc");null!=d&&(c.windowColor=d);d=X2(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},c3=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ta(c,a.F[d]);d=Z2(b,"ap");null!=d&&(c.Xf=d);d=X2(b,"cc");null!=d&&(c.Ul=d);d=X2(b,"ah");null!=d&&(c.Re=d);d=X2(b,"rc");null!=d&&(c.Mk=d);d=X2(b,"av");null!=d&&(c.Jg=d);return c},d3=function(a,b,c,d){var e={};
g.Ta(e,c3(a,b));g.Ta(e,b3(a,b));d?g.bc(e,a.A)?(d=a.u,e=a.A):d="_"+t2++:d=b.getAttribute("id")||"_"+t2++;a=X2(b,"t")+c;b=X2(b,"d")||0x8000000000000;if(2==e.ze||3==e.ze)c=e.Mk,e.Mk=e.Ul,e.Ul=c;return new s2(a,b,0,d,e)},e3=function(a,b,c,d,e,f,k){w2.call(this,a,b,c,d,e,f,k);
this.type=1},f3=function(a,b,c){this.C=c;
this.version=this.A=this.o=this.g=0;this.i=new DataView(a);this.l=[]},g3=function(a){var b=a.g;
a.g+=1;return a.i.getUint8(b)},h3=function(a){var b=a.g;
a.g+=4;return a.i.getUint32(b)},i3=function(a,b){V2.call(this);
this.i=a;this.track="CC3"==b.l?4:0;this.g=new D2;this.g.l=1<<this.track},k3=function(a){if(g.Fa(a))return!1;
a=new f3(a,8,0);return j3(a)},j3=function(a){if(!(a.g<a.i.byteLength)||1380139777!=h3(a))return!1;
a.version=g3(a);if(1<a.version)return!1;g3(a);g3(a);g3(a);return!0},l3=function(a,b,c,d,e,f,k){w2.call(this,a,b,c,d,e,f,k);
g.J(this.element,"ytp-caption-window-rollup");this.type=2;this.F=[];this.I=this.H=this.fa=0;this.M=NaN;this.xa=0;this.Ea=null;this.da=new g.M(this.JK,433,this);g.G(this,this.da)},Hpa=function(a,b){return(a.u?b.offsetHeight:b.offsetWidth)+1},Ipa=function(a){if(isNaN(a.M)){var b=a.l.Ul;
if(b){var c=g.Sd("SPAN");g.be(c,"\u2013".repeat(b));g.zh(c,x2(a,a.l.wb));a.A.appendChild(c);a.M=c.offsetWidth;a.A.removeChild(c)}else a.M=0}return a.M},Jpa=function(a,b){if(!b)return"";
a.u&&1!=a.o.params.HA&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},m3=function(a){a.F=[].concat(g.fa(document.getElementsByClassName("caption-visual-line")));
for(var b=a.o.params.Mk,c=0,d=0,e=a.F.length-1;c<b&&-1<e;){var f=a.F[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.F.length<b&&(d*=b/a.F.length);a.H=d;a.I=Math.max(Ipa(a),a.xa,Hpa(a,a.A))},Kpa=function(a,b){m3(a);
var c=a.F.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.H-c;if(c!=a.fa){var d=0<c&&0==a.fa;b||isNaN(c)||d||(g.J(a.element,"ytp-rollup-mode"),g.bo(a.da));g.zh(a.A,"transform",Jpa(a,c));a.fa=c}m3(a)},n3=function(){V2.call(this)},o3=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Qe=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new r2(b,c,d,e.id,p.nodeValue,f||0<n,g.Yb(l)?void 0:l);m.push(p);var r=e;g.G(r,p);r.g.push(p)}else r={},g.Ta(r,l),o3(a,b,c,d,e,!0,p,r,m)}},p3=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},q3=function(a,b,c,d){d=Object.assign({Vq:0},d);
return new s2(a,b,c,"_"+t2++,d)},r3=function(a){g.D.call(this);
this.i=a;this.g=null},u3=function(a){g.zK.call(this,a);
this.u=g.X(a);this.l=a.getVideoData();this.wa=g.YJ(a);this.I=a;var b=null,c=g.So("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Co(c));this.ba=b;this.o={wb:{}};this.A={wb:{}};this.H=[];this.M={};this.V={};this.P=!1;this.ma=g.RU(this.l,this.I);this.xa=!!this.l.captionTracks.length;this.Ba=!!this.l.oj;this.ka="3"==this.u.l;b=a.app.u;c=!(!b||!b.Zk());this.va=!(!b||!b.Ch());this.C=this.ka&&c&&!this.ma;this.R=!this.C&&this.ka&&this.va&&this.ma;this.i=this.D=this.F=this.O=this.da=null;this.Z=
new r3(this.u);g.G(this,this.Z);c=b=this.g=null;this.C||(b=new g.Zn(this.WA,void 0,this),g.G(this,b),c=new g.M(this.iM,2E3,this),g.G(this,c));this.X=b;this.fa=c;this.aa=new g.rs(this);g.G(this,this.aa);this.C||this.aa.K(a,"resize",this.gt);this.aa.K(a,"onPlaybackAudioChange",this.kI);this.aa.K(a,g.ND("captions"),this.YE,this);this.aa.K(a,"crx_captions",this.ZE,this);s3(this,t3(this,"display-settings")||{})},v3=function(a){if(1==a.u.eg||1==a.l.eg||"alwayson"==g.wB(a.l,"yt:cc"))return!0;
if(2==a.u.eg){var b=t3(a,"module-enabled");if(null!=b)return!!b}if(a.l.captionTracks.length)var c=a.player.getAudioTrack().kp;return"ON"==c||"on"==g.wB(a.l,"yt:cc")},w3=function(a,b){if(a.g&&(void 0===b||!b)||!a.l.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.gm||"FORCED_ON"==c.kp},y3=function(a,b){if(a.i){if(a.D&&a.D.g)return a.D.g;
var c=b;c||(c=a.Ba?!1:a.xa?!1:!0);c=f2(a.i.i,c);for(var d=[a.l.dg,a.u.dg,g.wB(a.l,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(d2(c[f])==d[e])return c[f];return a.D&&a.D.Cp?a.D.Cp:(d=c.find(function(k){return k.isDefault}))?d:c[0]||x3(a)}return null},x3=function(a){return a.D&&a.D.gm},z3=function(a){var b=x3(a);
return!!b&&a.g==b},A3=function(a,b){for(var c=a.I.app.u.ga().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},C3=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.P=c,a.P&&B3(a,"module-enabled",!!b));a.g=b;w3(a)&&(a.g=x3(a));a.load()},Lpa=function(a,b){var c=a.wa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.wa.getPlayerSize();switch(null!=b.params.Vq?b.params.Vq:1<b.g.length?1:0){case 1:return new e3(b,a.o,a.A,c,d.width,d.height,a.u.experiments);case 2:return new l3(b,a.o,a.A,c,d.width,d.height,a.u.experiments);default:return new w2(b,a.o,a.A,c,d.width,d.height,a.u.experiments)}},s3=function(a,b,c){var d=D3.wb;
a.o={};g.Ta(a.o,D3);a.o.wb={};g.Ta(a.o.wb,d);a.A={wb:{}};var e=b.backgroundOverride?a.A:a.o,f=b.background||d.background;$2.test(f);e.wb.background=f;e=b.colorOverride?a.A:a.o;f=b.color||d.color;$2.test(f);e.wb.color=f;e=b.windowColorOverride?a.A:a.o;f=b.windowColor||D3.windowColor;$2.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.A:a.o;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.wb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.A:a.o;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.wb.fontSizeIncrement=f;f=b.fontStyleOverride?a.A:a.o;e=b.fontStyle;null==e&&(e=d.bold&&d.Qe?3:d.bold?1:d.Qe?2:0);f=f.wb;switch(e){case 1:f.bold=!0;delete f.Qe;break;case 2:delete f.bold;f.Qe=!0;break;case 3:f.bold=!0;f.Qe=!0;break;default:delete f.bold,delete f.Qe}e=b.textOpacityOverride?a.A:a.o;f=b.textOpacity;null==f&&(f=d.textOpacity);e.wb.textOpacity=f;e=b.windowOpacityOverride?a.A:a.o;f=b.windowOpacity;null==f&&(f=D3.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.A:a.o;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.wb.charEdgeStyle=f;e=b.fontFamilyOverride?a.A:a.o;f=b.fontFamily;null==f&&(f=d.fontFamily);e.wb.fontFamily=f;a.loaded&&a.gt();c&&B3(a,"display-settings",b)},F3=function(a,b){if(b&&!a.F){var c=u2({ze:0,
lang:"th"});a.F=[c,new r2(c.start,c.end-c.start,0,c.id,"\u0e04\u0e33\u0e2d\u0e18\u0e34\u0e1a\u0e32\u0e22\u0e27\u0e34\u0e14\u0e35\u0e42\u0e2d\u0e08\u0e30\u0e40\u0e1b\u0e47\u0e19\u0e41\u0e1a\u0e1a\u0e19\u0e35\u0e49")];g.eK(a.player,a.F)}else!b&&a.F&&(E3(a,a.F),a.F=null)},E3=function(a,b){g.gK(a.player,b);
(0,g.z)(b,function(c){g.db(this.H,c)},a);
a.X.Pj()},t3=function(a,b){if(!a.ba)return null;
try{var c=a.ba.get(b)}catch(d){a.ba.remove(b)}return c},B3=function(a,b,c){if(a.ba)try{a.ba.set(b,c)}catch(d){}};
g.eC.prototype.qj=g.da(13,function(){for(var a=g.Fd(document,"track",void 0,this.g),b=0;b<a.length;b++)g.Xd(a[b])});
g.HW.prototype.qj=g.da(12,function(){this.g.qj()});
g.eC.prototype.Zk=g.da(11,function(){return!!this.g.textTracks});
g.HW.prototype.Zk=g.da(10,function(){return this.g.Zk()});
g.eC.prototype.jj=g.da(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.HW.prototype.jj=g.da(8,function(a){this.g.jj(a)});
g.WB.prototype.Ch=g.da(7,function(){});
g.eC.prototype.Ch=g.da(6,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.HW.prototype.Ch=g.da(5,function(){return this.g.Ch()});
g.sz.prototype.ar=g.da(3,function(a){return a?this.toString()==a.toString():!1});
g.rt.prototype.rm=g.da(2,function(a){return(a=this.mg(a))?a.i:0});
g.lw.prototype.rm=g.da(1,function(){return 0});
var Mpa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,vpa=/#(.)(.)(.)/,upa=/^#(?:[0-9a-f]{3}){1,2}$/i,$2=/^#(?:[0-9a-f]{3}){1,2}$/i;g.t(h2,g.D);h2.prototype.Cz=function(){return!1};
h2.prototype.U=function(){this.Kg();g.D.prototype.U.call(this)};
g.t(i2,h2);i2.prototype.Sq=function(a,b,c){b=this.Lj(a,b);var d=(0,g.x)(function(e){this.g=null;c(e.responseText,a)},this);
this.Kg();this.g=g.Fq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
i2.prototype.Tq=function(a){if(this.l)for(var b=g.q(this.l.captionTracks),c=b.next();!c.done;c=b.next())g2(this.i,c.value);a()};
i2.prototype.Lj=function(a,b){var c=a.Jb(),d={fmt:b};a.g&&(d.tlang=d2(a));return g.oq(c,d)};
i2.prototype.Kg=function(){this.g&&this.g.abort()};
j2.prototype.contains=function(a){a=g.pb(this.Ta,a);return 0<=a||0>a&&1==(-a-1)%2};
j2.prototype.length=function(){return this.Ta.length/2};
g.t(k2,g.D);g.h=k2.prototype;g.h.U=function(){g.D.prototype.U.call(this);this.i&&this.i.cancel()};
g.h.Ex=function(a){var b=this;if(this.D.hi())var c=this.u.K(this.o,"progresssync",function(){b.D.index.Eb()&&(b.reset(),b.g=null,l2(b,b.o.getCurrentTime()),b.u.Ka(c))});
else l2(this,a)};
g.h.VF=function(){l2(this,this.o.getCurrentTime())};
g.h.reset=function(){this.A=new j2;this.i&&(this.i.cancel(),this.i=null)};
g.h.Uw=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Kf(a);!a||this.i||this.g&&30<this.g.startTime-this.o.getCurrentTime()||(a=this.g,a=a.g.ri(a),a.g[0].duration&&(this.A.contains(a.g[0].i)||m2(this,a),this.g=g.Wa(a.g)));this.H.start()};
g.h.EK=function(a){var b=!(this.C?a.response:a.responseText)||400<=a.status,c=g.tw(a);c?(a=g.Bv(this.l,this.I,{}),b=this.l,g.wv(b.i,a,c),b.requestId=a.get("req_id"),m2(this,this.l)):(b||null===this.F||(this.C?this.F(a.response,1E3*(this.l.g[0].startTime+this.o.Ib())):this.F(a.responseText,1E3*(this.l.g[0].startTime+this.o.Ib()))),this.i=this.l=null)};
g.t(n2,h2);g.h=n2.prototype;g.h.Sq=function(a,b,c){this.Kg();b=xpa(this,a.getId());b||(b=a.i,b=this.g.i?p2(this,b,"386"):p2(this,b));if(b){var d=1E3*(b.index.rm(b.index.oe())-b.index.Hc(b.index.oe()));this.l=new k2(new g.Tu,this.C,b,function(e,f){c(e,a,f,d)},this.A||g.Nu(b.info),(0,g.x)(function(){this.l&&this.l.reset();
this.o=!0},this))}};
g.h.Cz=function(){var a=this.o;this.o=!1;return a};
g.h.Tq=function(a){var b;this.A?b=[new g.sz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.sz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.g.i?o2(this,"386"):o2(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())g2(this.i,c.value);a()};
g.h.Kg=function(){this.l&&(this.l.dispose(),this.l=null)};
g.h.Lj=function(){return""};
g.t(q2,h2);q2.prototype.Sq=function(a,b,c){b=this.Lj(a,b);var d=(0,g.x)(function(e){this.g=null;c(e.responseText,a)},this);
this.Kg();this.g=g.Fq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
q2.prototype.Tq=function(a){var b=this.o,c={type:"list",tlangs:1,v:this.l,vssids:1};this.A&&(c.asrs=1);b=g.oq(b,c);c=(0,g.x)(function(d){this.g=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.q(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),r="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
g2(this.i,new g.sz({languageCode:f,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:u,vss_id:k,is_default:r}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),p=d[f].getAttribute("id"),r="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,isDefault:r},this.C[l.languageCode]=l.languageName,this.u.push(l)}a()},this);
this.Kg();this.g=g.Fq(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
q2.prototype.Lj=function(a,b){var c=this.o,d={v:this.l,type:"track",lang:a.i,name:a.getName(),kind:a.o,fmt:b};a.g&&(d.tlang=d2(a));return c=g.oq(c,d)};
q2.prototype.Kg=function(){this.g&&this.g.abort()};var ypa=["left","right","center","justify"];var D3={windowColor:"#080808",windowOpacity:0,textAlign:2,Xf:7,Re:50,Jg:100,wb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(r2,g.KD);r2.prototype.toString=function(){return g.KD.prototype.toString.call(this)};g.t(s2,g.KD);s2.prototype.toString=function(){return g.KD.prototype.toString.call(this)};
var t2=0;g.t(w2,g.W);g.h=w2.prototype;g.h.UF=function(a,b){var c=g.Ph(this.element,this.element.parentElement);this.ma=a-c.x;this.va=b-c.y;g.J(this.element,"ytp-dragging")};
g.h.TF=function(a,b){var c=g.Sh(this.element),d=a-this.ma-.02*this.Pa,e=b-this.va-.02*this.La,f=(d+c.width/2)/this.X*3;f=Math.floor(g.qd(f,0,2));var k=(e+c.height/2)/this.wa*3;k=Math.floor(g.qd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.X;d=100*g.qd(d,0,1);c=(e+k/2*c.height)/this.wa;c=100*g.qd(c,0,1);this.o.params.Xf=l;this.o.params.Jg=c;this.o.params.Re=d;this.l.Xf=l;this.l.Jg=c;this.l.Re=d;this.Zz()};
g.h.SF=function(){g.Tn(this.element,"ytp-dragging")};
g.h.Zz=function(){this.Ah(this.C)};
g.h.Ah=function(a){var b=Math.min(this.Pv(),this.X),c=this.Ov(),d="";3==this.o.params.ze&&(d="rotate(180deg)");g.zh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Wo(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.l.Re+2;d=this.l.Xf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.A.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.l.Jg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.zh(this.element,a)};
g.h.Wo=function(a){var b;for(b=0;b<a.length&&a[b]==this.C[b];b++);if(this.O||this.C.length>b)b=0,this.O=!1,this.C=[],this.D=this.V=this.R=null,g.Vd(this.A);for(;b<a.length;b++)A2(this,a[b])};
g.h.Pv=function(){return 0};
g.h.Ov=function(){return 0};
g.h.toString=function(){return g.W.prototype.toString.call(this)};B2.prototype.u=function(){};D2.prototype.clear=function(){this.o=this.i=this.mode=0;this.g=[];this.reset()};
D2.prototype.reset=function(){this.mode=0;this.u.reset(0);this.A.reset(1)};
var E2=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];G2.prototype.set=function(a){this.g=a};
G2.prototype.get=function(){return this.g};
H2.prototype.clear=function(){this.g=0};
H2.prototype.update=function(){this.g=2==this.g?1:0};
H2.prototype.matches=function(a,b){return 0!=this.g&&a==this.l&&b==this.i};
I2.prototype.jg=function(a){this.Qd=a.Qd;this.timestamp=a.timestamp};
I2.prototype.reset=function(){this.timestamp=this.Qd=0};
J2.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.l[b][c].timestamp=a};
J2.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.l[b][c];a=0==d.Qd?a+"_":a+String.fromCharCode(d.Qd)}a+="\n"}return a};
J2.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.l[b][c].reset();this.o=a;this.g=0;this.i=this.row=1};
var Cpa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Dpa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Epa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Fpa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Q2.prototype.reset=function(a,b){this.u=b;this.style.set(2);this.i=this.A;this.l=this.C;this.g=this.i;var c=(a<<2)+(b<<1);this.A.reset(c);this.C.reset(c);this.D.reset((a<<2)+(b<<1)+1)};
C2.prototype.reset=function(a){this.u=a;this.g.clear();this.o=this.l;this.l.reset(a,0);this.A.reset(a,1)};g.t(V2,g.D);V2.prototype.reset=function(){};g.t(W2,V2);W2.prototype.reset=function(){this.D={};this.i=this.g=null;this.C=!0};
W2.prototype.o=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.l,l={},m=c.getAttribute("p");m&&g.Ta(l,this.l[m]);m=Y2(c,"b");null!=m&&(l.bold=
m);m=Y2(c,"i");null!=m&&(l.Qe=m);m=Y2(c,"u");null!=m&&(l.underline=m);m=Z2(c,"et");null!=m&&(l.charEdgeStyle=m);m=Z2(c,"of");null!=m&&(l.offset=m);m=a3(c,"bc");null!=m&&(l.background=m);m=a3(c,"ec");null!=m&&(l.Nu=m);m=a3(c,"fc");null!=m&&(l.color=m);m=Z2(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=X2(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=X2(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=X2(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=Z2(c,"rb");null!=m&&10!=m&&(l.bd=10<m?m-1:m);m=Z2(c,
"hg");null!=m&&(l.UD=m);c=Z2(c,"te");null!=c&&(2==c&&(l.bold=!1,c=1),l.ye=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.H[d]=b3(this,c);break;case "wp":d=c.getAttribute("id"),this.F[d]=c3(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=d3(this,d,e,!1);g.G(this,this.g);(d=this.D[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.D[this.g.id]=this.g;c.push(this.g);break;case "p":var n=
e;k=[];l=d.getAttribute("w")||this.u;m=!!Y2(d,"a");n=(X2(d,"t")||0)+n;var p=X2(d,"d")||5E3;m||(!this.C&&this.i&&this.i.windowId==l&&this.i.end>n&&(this.i.end=n),this.i&&"\n"==this.i.text&&(this.i.text=""));var r=m?6:5,u=this.l[d.getAttribute("p")],A=[].concat(g.fa(d.childNodes));A.length&&(this.C=null!=d.getAttribute("d"));for(var C=0;C<A.length;C++){var E=A[C];0<C&&(m=!0);var F=void 0;1==E.nodeType&&(F=E);if(F&&"s"==F.tagName)if((E=this.l[F.getAttribute("p")])&&E.bd)1==E.bd?(F=U2(n,p,l,m,r,A.slice(C,
C+4),this.l),C+=3):F=U2(n,p,l,m,r,[F],this.l);else{var L=F;F=n;E=p;var aa=l,qa=m,ya=r,fb=L.textContent?L.textContent:"",te=this.l[L.getAttribute("p")];L=X2(L,"t")||0;F=new r2(F+L,E-L,ya,aa,fb,qa,te)}else F=new r2(n,p,r,l,E.textContent||"",m,u);k.push(F);this.i=F}if(0<k.length)for(k[0].windowId==this.u&&(this.g=d3(this,d,e,!0),g.G(this,this.g),c.push(this.g)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.G(l,k),l.g.push(k),c.push(k)}e=c}else e=[];return e};g.t(e3,w2);e3.prototype.Wo=function(a){var b=this.o.g;w2.prototype.Wo.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.g==e)var d=f;else{d={};g.Ta(d,c.g);g.Ta(d,Npa);var e=c.g;var f=d}A2(this,c,d)}};
var Npa={SD:!0};g.t(f3,B2);f3.prototype.u=function(a,b,c,d,e){if(c<d){var f="_"+t2++;c=c/1E3-this.C;d=d/1E3-this.C;a=new s2(c,d-c,5,f,{textAlign:0,Xf:0,Re:2.5*b,Jg:5.33*a});e=new r2(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.t(i3,V2);i3.prototype.o=function(a){a=new f3(a,a.byteLength,this.i);if(j3(a)){for(;a.g<a.i.byteLength;)for(0==a.version?a.o=h3(a)*(1E3/45):1==a.version&&(a.o=4294967296*h3(a)+h3(a)),a.A=g3(a);0<a.A;a.A--){var b=g3(a),c=g3(a),d=g3(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.o,type:this.track,Hu:c,Iu:d,order:b.g.length}))}Bpa(this.g,a);return a.l}return[]};
i3.prototype.reset=function(){this.g.clear()};g.t(l3,w2);g.h=l3.prototype;g.h.Zz=function(){g.co(this.da)};
g.h.JK=function(){g.Tn(this.element,"ytp-rollup-mode");this.Ah(this.Ea,!0)};
g.h.Ov=function(){return this.u?this.I:this.H};
g.h.Pv=function(){return this.u?this.H:this.I};
g.h.Ah=function(a,b){this.Ea=a;if(this.o.params.Mk){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.xa=this.I;this.H=this.I=0;w2.prototype.Ah.call(this,a);Kpa(this,b);w2.prototype.Ah.call(this,a)}else w2.prototype.Ah.call(this,a)};g.t(n3,V2);
n3.prototype.o=function(a,b){for(var c=[],d=a.split(Opa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Ppa.test(f)){var l=G3.exec(f);if(l&&4<=l.length){var m=p3(l[1]),n=p3(l[2])-m;m+=k;var p,r=p=void 0,u=void 0,A=void 0,C=l[3];l={textAlign:2};C=g.q(C?C.split(" "):[]);for(var E=C.next();!E.done;E=C.next())if(E=E.value.split(":"),2==E.length){var F=E[1];switch(E[0]){case "line":E=F.split(",");E[0].endsWith("%")&&(A=E[0],l.Jg=Number.parseInt(A,10),2==E.length&&(u=E[1].trim()));break;case "position":E=F.split(",");
r=E[0];l.Re=Number.parseInt(r,10);2==E.length&&(p=E[1].trim());break;case "align":switch(F){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}A||(l.Jg=100,u||(u="end"));if(!r)switch(l.textAlign){case 0:l.Re=0;break;case 1:l.Re=100;break;default:l.Re=50}r=0;switch(u){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(p){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Xf=0>r||8<r?7:r;p=l;f=f.substring(G3.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=q3(m,n,5,r),n=new r2(m,n,5,k.id,p,!1,g.Yb(f)?void 0:f),c.push(k),c.push(n),g.G(k,n),k.g.push(n);else for(u=p.split(Qpa),1==u.length?(p=5,r=q3(m,n,p,r)):(A=p=6,r=Object.assign({Ul:32},r),r=new s2(m,n,A,"_"+t2++,r)),c.push(r),A=m,l=0;l<u.length;l++)C=u[l],0==l%2?(E=g.Vn("<html>"+C+"</html>"),E.getElementsByTagName("parsererror").length?
(F=E.createElement("span"),F.appendChild(E.createTextNode(C))):F=E.firstChild,o3(this,A,n-(A-m),p,r,0<l,F,f,c)):A=p3(C)+k}G3.lastIndex=0}}return c};
var Ppa=/^NOTE/,Opa=/(?:\r\n|\r|\n){2,}/,G3=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Qpa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(r3,g.D);r3.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
r3.prototype.reset=function(){this.g&&this.g.reset()};
r3.prototype.U=function(){this.clear();g.D.prototype.U.call(this)};g.t(u3,g.zK);g.h=u3.prototype;g.h.U=function(){if(this.C||this.R){var a=this.I.app.u;a&&a.qj()}else F3(this,!1);g.zK.prototype.U.call(this)};
g.h.Rk=function(){return this.ka?this.C||this.R:w3(this)?!0:v3(this)};
g.h.load=function(){g.zK.prototype.load.call(this);this.D=this.player.getAudioTrack();if(this.i)this.g&&(this.Z.clear(),this.C?A3(this,!0):3!=this.player.getPresentingPlayerType()&&this.i.Sq(this.g,"srv3",(0,g.x)(this.qL,this))),this.g&&!z3(this)?this.player.la("captionschanged",c2(this.g)):this.player.la("onCaptionsTrackListChanged");else{var a;this.ma?a=new n2(this.l.ia,this.player):this.xa?a=new i2(this.u,this.l,this.player.getAudioTrack()):a=new q2(this.l.oj,this.l.videoId,this.l.dg||this.u.dg||
g.wB(this.l,"yt:cc_default_lang")||this.u.Wb,this.l.ip,this.u);this.i=a;g.G(this,this.i);a.Tq((0,g.x)(this.pL,this))}};
g.h.unload=function(){this.C&&this.g?A3(this,!1):(this.fa&&g.eo(this.fa),g.hK(this.player,"captions"),this.H=[],this.i&&this.i.Kg(),this.Z.clear(),this.F&&g.eK(this.player,this.F),this.gt());g.zK.prototype.unload.call(this);var a=g.V(this.player.app);a&&g.LH(a.C);this.player.la("captionschanged",{})};
g.h.pL=function(){var a;this.P||v3(this)?a=y3(this,this.P):w3(this)&&(a=x3(this));if(this.C||this.R){for(var b=f2(this.i.i,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.tz(e),srclang:d2(e),id:e.toString()};this.R||(f.src=this.i.Lj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Rd("TRACK",f))}this.I.app.u.jj(c);a=this.I.app.u.ga();this.va&&this.aa.K(a.textTracks,"change",this.rL)}else!this.g&&a&&C3(this,a),this.player.la("onCaptionsTrackListChanged"),this.player.la("onApiChange")};
g.h.rL=function(){for(var a=this.I.app.u.ga().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=f2(this.i.i,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.g:null)!=b&&C3(this,b,!0)};
g.h.SM=function(){!this.g&&this.C||this.unload()};
g.h.qL=function(a,b,c,d){if(a){this.i.Cz()&&(this.H=[],g.hK(this.I,"captions"),this.X.Pj(),this.Z.reset());var e=this.Z;c=c||0;d=d||0;if(!g.Fa(a)){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.Mt(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!k3(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=
a[k++];var p=a[k++],r=a[k++];m=((m&7)<<18|(n&63)<<12|(p&63)<<6|r&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],p=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|p&63)}a=f.join("")}}if(a)try{if(g.Fa(a)){if("WEBVTT"==a.substring(0,6)){b=a;var u=c;e.g||(e.g=new n3);var A=e.g.o(b,u);.01>Math.random()&&g.Dp(Error("Deprecated subtitles format in web player: WebVTT"));var C=A}else b:{A=a;u=g.Vn(A);if(!u||!u.firstChild){var E=Error("Invalid caption track data");
E.params=A;throw E;}if("timedtext"==u.firstChild.tagName){if(3==parseInt(u.firstChild.getAttribute("format"),10)){if(!e.g){A={};var F=d2(b);F&&(A.lang=F,Mpa.test(F)&&(A.ze=1));e.g=new W2(A,e.i)}C=e.g.o(u,c);break b}var L=Error("Unsupported subtitles format in web player (Format2)");L.params=A;throw L;}if("transcript"==u.firstChild.tagName){var aa=Error("Unsupported subtitles format in web player (Format1)");aa.params=A;throw aa;}var qa=Error("Invalid caption track data");qa.params=A;throw qa;}var ya=
C}else{C=a;u=c;F=d;if(!k3(C))throw Error("Invalid binary caption track data");e.g||(e.g=new i3(F,b));ya=e.g.o(C,u)}var fb=ya}catch(te){g.N(te),e.clear(),fb=[]}else fb=[];g.eK(this.player,fb);!this.P||this.R||z3(this)||g.Ny(this.u)||g.Oy(this.u)||(g.eo(this.fa),fb=u2({Xf:0,Re:5,Jg:5,Mk:2,textAlign:0,ze:0,lang:"th"}),this.O=[fb],e=["\u0e04\u0e25\u0e34\u0e01 "," \u0e2a\u0e33\u0e2b\u0e23\u0e31\u0e1a\u0e01\u0e32\u0e23\u0e15\u0e31\u0e49\u0e07\u0e04\u0e48\u0e32"],this.da||(ya=new g.JC(g.GP()),g.G(this,ya),
this.da=ya.element),ya=fb.end-fb.start,(b=g.tz(this.g))&&this.O.push(new r2(fb.start,ya,0,fb.id,b)),this.O.push(new r2(fb.start,ya,0,fb.id,e[0]),new r2(fb.start,ya,0,fb.id,this.da,!0),new r2(fb.start,ya,0,fb.id,e[1],!0)),g.eK(this.player,this.O),g.bo(this.fa));!this.P||this.R||z3(this)||(B3(this,"module-enabled",!0),this.D&&(this.D.g=this.g),(fb=g.V(this.player.app))&&g.LH(fb.C));this.P=!1}};
g.h.YE=function(a){this.H.push(a);this.X.Pj()};
g.h.ZE=function(a){g.db(this.H,a);this.i instanceof n2&&this.i.A&&g.gK(this.player,[a]);this.X.Pj()};
g.h.bM=function(a){if(a instanceof s2){var b=this.M[a.id];b&&b.o!=a&&(b.dispose(),delete this.M[a.id],b=null);b||(b=Lpa(this,a))&&(this.M[a.id]=b)}else b=a.windowId,this.V[b]||(this.V[b]=[]),this.V[b].push(a)};
g.h.iM=function(){E3(this,this.O);this.O=null};
g.h.WA=function(){this.X.stop();g.Zb(this.V);this.H.sort(g.MD);var a=this.H;if(this.F){var b=(0,g.Yd)(a,function(c){return-1==this.F.indexOf(c)},this);
b.length&&(a=b)}(0,g.z)(a,this.bM,this);g.Lb(this.M,function(c,d){this.V[d]?(c.element.parentNode||g.lK(this.player,c.element,4),c.Ah(this.V[d])):(c.dispose(),delete this.M[d])},this)};
g.h.mM=function(){s3(this,{},!0)};
g.h.jD=function(){var a=D3.wb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Qe?3:a.bold?1:a.Qe?2:0,textOpacity:a.textOpacity,windowColor:D3.windowColor,windowOpacity:D3.windowOpacity};var b=t3(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.bB=function(a,b){var c={};g.Ta(c,t3(this,"display-settings"));g.Ta(c,a);s3(this,c,b);this.player.la("captionssettingschanged")};
g.h.gt=function(){!this.C&&this.loaded&&(g.Lb(this.M,function(a,b){a.dispose();delete this.M[b]},this),this.WA())};
g.h.xc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.qd(b,-2,4);this.bB({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&C3(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.u.rb&&B3(this,"module-enabled",!!b);break;case "track":if(!this.i)return{};if(b){if(this.C)break;if(!g.Pa(b))break;if(g.Yb(b)){C3(this,null,!0);break}for(var d=f2(this.i.i,!0),e=0;e<d.length;e++){var f=d[e];f.i!=b.languageCode||c&&f.l!=b.languageName||(c=b.translationLanguage?tpa(f,b.translationLanguage):
f)}!c||c==this.g&&this.loaded||C3(this,c,!0)}else return this.loaded&&this.g&&!z3(this)?c2(this.g):{};return"";case "tracklist":return this.i?(0,g.B)(f2(this.i.i,!(!b||!b.includeAsr)),function(k){return c2(k)}):[];
case "translationLanguages":return this.i?this.i.u:[];case "sampleSubtitles":this.C||void 0==b||F3(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.u.rb&&a.push("stickyLoading");return a};
g.h.Nj=function(){var a=this.g;return a?{cc:a.A}:{}};
g.h.LM=function(){this.loaded&&this.g&&!z3(this)?(B3(this,"module-enabled",!1),this.unload(),w3(this,!0)&&C3(this,x3(this),!1)):C3(this,z3(this)||!this.g?y3(this,!0):this.g,!0)};
g.h.kI=function(){var a=z3(this);w3(this,a)?C3(this,this.player.getAudioTrack().gm,!1):this.l.captionTracks.length&&(this.loaded&&this.unload(),this.Rk()&&(a?C3(this,y3(this),!1):this.load()))};g.XU.captions=u3;})(_yt_player);
