(function(g){var window=this;var Xpa=function(a,b){return g.Vb(a,b)},f5=function(){},Ypa=function(a){if(a.zc&&"function"==typeof a.zc)return a.zc();
if(g.Fa(a))return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Rb(a)},Zpa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||g.Fa(a))(0,g.z)(a,b,void 0);else{if(a.Gd&&"function"==typeof a.Gd)var c=a.Gd();else if(a.zc&&"function"==typeof a.zc)c=void 0;else if(g.Na(a)||g.Fa(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Sb(a);d=Ypa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},g5=function(a){g.Vm(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.H)()).toString(36));
return a},h5=function(a,b,c){g.Ma(c)||(c=[String(c)]);
g.$m(a.l,b,c)},i5=function(a){return(a=g.to(a))?new ActiveXObject(a):new XMLHttpRequest},j5=function(a,b){return b+" ["+a.ba+" "+a.D+" "+a.getStatus()+"]"},$pa=function(a){return"content-type"==a.toLowerCase()},k5=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.F&&(g.v.clearTimeout(a.F),a.F=null)},aqa=function(a){return g.Md&&g.od(9)&&g.Ha(a.timeout)&&g.Ea(a.ontimeout)},l5=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},m5=function(a,b){if(a.g){k5(a);
var c=a.g,d=a.P[0]?g.Ja:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},n5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;l5(a);m5(a)},o5=function(a){return a.g?a.g.readyState:0},p5=function(a){if(a.i&&"undefined"!=typeof g.kY)if(a.P[1]&&4==o5(a)&&2==a.getStatus())j5(a,"Local request error detected and ignored");
else if(a.C&&4==o5(a))g.Gg(a.kw,0,a);else if(a.dispatchEvent("readystatechange"),4==o5(a)){j5(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(1,String(a.D));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!bqa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<o5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";l5(a)}}finally{m5(a)}}},q5=function(a){g.Sf.call(this);
this.headers=new g.Km;this.M=a||null;this.i=!1;this.P=this.g=null;this.ba=this.D="";this.u=0;this.l="";this.o=this.V=this.C=this.O=!1;this.A=0;this.F=null;this.Z="";this.I=this.R=!1},r5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},cqa=function(a,b){var c=[];
g.Lk(b,function(d){try{var e=g.Io.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ea(e)?g.Ho(e)&&c.push(d):c.push(d)},a);
return c},dqa=function(a,b){var c=cqa(a,b);
(0,g.z)(c,function(d){g.Io.prototype.remove.call(this,d)},a)},s5=function(a){if(a.cd){if(a.cd.locationOverrideToken)return{locationOverrideToken:a.cd.locationOverrideToken};
if(null!=a.cd.latitudeE7&&null!=a.cd.longitudeE7)return{latitudeE7:a.cd.latitudeE7,longitudeE7:a.cd.longitudeE7}}return null},eqa=function(a,b){g.ab(a,b)||a.push(b)},t5=function(a){var b=0,c;
for(c in a)b++;return b},u5=function(a,b){var c=b instanceof g.yc?b:g.Ec(b,/^data:image\//i.test(b));
a.src=g.zc(c)},fqa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},gqa=function(a,b,c,d){var e=new g.Nm(null,void 0);
a&&g.Om(e,a);b&&g.Pm(e,b);c&&g.Qm(e,c);d&&(e.i=d);return e},v5=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return fqa(a)},w5=function(){this.g=[];
this.i=[]},x5=function(a,b){g.Np[a]=!0;
var c=g.Lp();c&&c.publish.apply(c,arguments);g.Np[a]=!1},y5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Km;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",hqa(this,a.capabilities||""),iqa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},hqa=function(a,b){a.capabilities.clear();
(0,g.Yd)(b.split(","),g.Sa(Xpa,jqa)).forEach(function(c){a.capabilities.add(c)})},iqa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},z5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},A5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},B5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},kqa=function(a){return new z5(a)},C5=function(a){return g.Ma(a)?(0,g.B)(a,kqa):[]},D5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},E5=function(a){return g.Ma(a)?"["+(0,g.B)(a,D5).join(",")+"]":"null"},F5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},lqa=function(a){return(0,g.B)(a,function(b){return{key:b.id,
name:b.name}})},G5=function(a,b){return g.Ya(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},H5=function(a,b){return g.Ya(a,function(c){return A5(c,b)})},I5=function(a){try{var b=(0,g.et)(),c=(0,g.dt)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},mqa=function(){var a=(0,g.dt)();
a&&dqa(a,a.g.lf(!0))},J5=function(){var a=g.gt("yt-remote-connected-devices")||[];
g.rb(a);return a},nqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.B)(a,function(d,e){return 0==e?d:d.substring(c.length)})},K5=function(a){g.ft("yt-remote-connected-devices",a,86400)},M5=function(){if(L5)return L5;
var a=g.gt("yt-remote-device-id");a||(a=F5(),g.ft("yt-remote-device-id",a,31536E3));for(var b=J5(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return L5=d},N5=function(){var a=J5(),b=M5();
g.ab(a,b);g.ht()&&g.tb(a,b);a=nqa(a);if(0==a.length)try{g.hs("remote_sid")}catch(c){}else try{g.gs("remote_sid",a.join(","),-1)}catch(c){}},O5=function(){return g.gt("yt-remote-session-browser-channel")},P5=function(){return g.gt("yt-remote-local-screens")||[]},Q5=function(){g.ft("yt-remote-lounge-token-expiration",!0,86400)},oqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.B)(P5(),function(d){return d.loungeToken}),c=(0,g.B)(a,function(d){return d.loungeToken});
(0,g.jj)(c,function(d){return!g.ab(b,d)})&&Q5();
g.ft("yt-remote-local-screens",a,31536E3)},pqa=function(a,b){g.ft("yt-remote-session-browser-channel",a);
g.ft("yt-remote-session-screen-id",b);var c=J5(),d=M5();g.ab(c,d)||c.push(d);K5(c);N5()},R5=function(a){a||(I5("yt-remote-session-screen-id"),I5("yt-remote-session-video-id"));
N5();a=J5();g.db(a,M5());K5(a)},T5=function(){if(!S5){var a=g.So();
a&&(S5=new g.Co(a))}return S5?!!S5.get("yt-remote-use-staging-server"):!1},U5=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},V5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},X5=function(a){a.length?W5(a.shift(),function(){X5(a)}):Y5()},qqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},W5=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},Y5=function(){var a=V5();
a&&a(!1,"No cast extension found")},Z5=function(){if(rqa){var a=2,b=V5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;W5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",Y5,c)}},sqa=function(){Z5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);X5(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},$5=function(a,b,c){g.D.call(this);
this.A=null!=c?(0,g.x)(a,c):a;this.Wc=b;this.u=(0,g.x)(this.mD,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},a6=function(){},b6=function(a,b,c,d){this.g=a;
this.l=b;this.C=c;this.A=d||1;this.o=45E3;this.aa=new g.an(this);this.i=new g.Fg;this.i.setInterval(250)},d6=function(a,b,c){a.Yh=1;
a.Zf=g5(b.clone());a.uh=c;a.u=!0;c6(a,null)},e6=function(a,b,c,d,e){a.Yh=1;
a.Zf=g5(b.clone());a.uh=null;a.u=c;e&&(a.eA=!1);c6(a,d)},c6=function(a,b){a.Hi=(0,g.H)();
f6(a);a.Gg=a.Zf.clone();h5(a.Gg,"t",a.A);a.jl=0;a.tc=a.g.Ap(a.g.Tk()?b:null);0<a.eq&&(a.In=new g.Al((0,g.x)(a.lB,a,a.tc),a.eq));a.aa.ca(a.tc,"readystatechange",a.eM);var c=a.bh?g.cc(a.bh):{};a.uh?(a.oo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.Gg,a.oo,a.uh,c)):(a.oo="GET",a.eA&&!g.Od&&(c.Connection="close"),a.tc.send(a.Gg,a.oo,null,c));a.g.te(1)},m6=function(a,b,c){for(var d=!0;!a.Rg&&a.jl<c.length;){var e=tqa(a,c);
if(e==g6){4==b&&(a.rg=4,h6(15),d=!1);break}else if(e==i6){a.rg=4;h6(16);d=!1;break}else j6(a,e)}4==b&&0==c.length&&(a.rg=1,h6(17),d=!1);a.xe=a.xe&&d;d||(k6(a),l6(a))},tqa=function(a,b){var c=a.jl,d=b.indexOf("\n",c);
if(-1==d)return g6;c=Number(b.substring(c,d));if(isNaN(c))return i6;d+=1;if(d+c>b.length)return g6;var e=b.substr(d,c);a.jl=d+c;return e},p6=function(a,b){a.Hi=(0,g.H)();
f6(a);var c=b?window.location.hostname:"";a.Gg=a.Zf.clone();g.Vm(a.Gg,"DOMAIN",c);g.Vm(a.Gg,"t",a.A);try{a.Be=new ActiveXObject("htmlfile")}catch(n){k6(a);a.rg=7;h6(22);l6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in n6)k=n6[l];else if(l in o6)k=n6[l]=o6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
n6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Sc(g.rc("b/12014412"),d+"</body></html>");a.Be.open();a.Be.write(g.Nc(c));a.Be.close();a.Be.parentWindow.m=(0,g.x)(a.vL,a);a.Be.parentWindow.d=(0,g.x)(a.iz,a,!0);a.Be.parentWindow.rpcClose=(0,g.x)(a.iz,a,!1);c=a.Be.createElement("DIV");a.Be.parentWindow.document.body.appendChild(c);d=g.Dc(a.Gg.toString());d=g.Zc(g.Ac(d));d=g.Sc(g.rc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Tc(c,d);a.g.te(1)},f6=function(a){a.mt=(0,g.H)()+a.o;
q6(a,a.o)},q6=function(a,b){if(null!=a.Yi)throw Error("WatchDog timer not null");
a.Yi=r6((0,g.x)(a.FL,a),b)},s6=function(a){a.Yi&&(g.v.clearTimeout(a.Yi),a.Yi=null)},l6=function(a){a.g.iw()||a.Rg||a.g.vn(a)},k6=function(a){s6(a);
g.qf(a.In);a.In=null;a.i.stop();g.cn(a.aa);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.Be&&(a.Be=null)},j6=function(a,b){try{a.g.cz(a,b),a.g.te(4)}catch(c){}},u6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;t6(a,b,function(k){k?c(!0):g.v.setTimeout(function(){u6(a,b,c,d,f)},f)})}},t6=function(a,b,c){var d=new Image;
d.onload=function(){try{v6(d),c(!0)}catch(e){}};
d.onerror=function(){try{v6(d),c(!1)}catch(e){}};
d.onabort=function(){try{v6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{v6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
u5(d,a)},v6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},w6=function(a){this.g=a;
this.i=new a6},y6=function(a){var b=x6(a.g,a.mj,"/mail/images/cleardot.gif");
g5(b);u6(b.toString(),5E3,(0,g.x)(a.sC,a),3,2E3);a.te(1)},A6=function(a){var b=a.g.F;
if(null!=b)h6(5),b?(h6(11),z6(a.g,a,!1)):(h6(12),z6(a.g,a,!0));else if(a.Cd=new b6(a,void 0,void 0,void 0),a.Cd.bh=a.bq,b=a.g,b=x6(b,b.Tk()?a.Uj:null,a.cq),h6(5),!g.Md||g.pd(10))h5(b,"TYPE","xmlhttp"),e6(a.Cd,b,!1,a.Uj,!1);else{h5(b,"TYPE","html");var c=a.Cd;a=!!a.Uj;c.Yh=3;c.Zf=g5(b.clone());p6(c,a)}},B6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new a6;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},uqa=function(a,b){this.g=a;
this.map=b;this.context=null},C6=function(a){g.sf.call(this,"statevent",a)},D6=function(a,b){g.sf.call(this,"timingevent",a);
this.size=b},E6=function(a){g.sf.call(this,"serverreachability",a)},I6=function(a){F6(a);
if(3==a.g){var b=a.Bk++,c=a.hm.clone();g.Vm(c,"SID",a.l);g.Vm(c,"RID",b);g.Vm(c,"TYPE","terminate");G6(a,c);b=new b6(a,a.l,b,void 0);b.Yh=2;b.Zf=g5(c.clone());u5(new Image,b.Zf.toString());b.Hi=(0,g.H)();f6(b)}H6(a)},K6=function(a){a.LC(1,0);
a.hm=x6(a,null,a.Zp);J6(a)},F6=function(a){a.hg&&(a.hg.abort(),a.hg=null);
a.Sb&&(a.Sb.cancel(),a.Sb=null);a.nf&&(g.v.clearTimeout(a.nf),a.nf=null);L6(a);a.yd&&(a.yd.cancel(),a.yd=null);a.ng&&(g.v.clearTimeout(a.ng),a.ng=null)},M6=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new uqa(a.KH++,b));2!=a.g&&3!=a.g||J6(a)},J6=function(a){a.yd||a.ng||(a.ng=r6((0,g.x)(a.hz,a),0),a.Sh=0)},P6=function(a,b){if(1==a.g){if(!b){a.Bk=Math.floor(1E5*Math.random());
var c=a.Bk++,d=new b6(a,"",c,void 0);d.bh=null;var e=N6(a),f=a.hm.clone();g.Vm(f,"RID",c);g.Vm(f,"CVER","1");G6(a,f);d6(d,f,e);a.yd=d;a.g=2}}else 3==a.g&&(b?O6(a,b):0==a.i.length||a.yd||O6(a))},O6=function(a,b){if(b)if(6<a.Sg){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.Bk-1;var d=N6(a)}else c=b.C,d=b.uh;else c=a.Bk++,d=N6(a);var e=a.hm.clone();g.Vm(e,"SID",a.l);g.Vm(e,"RID",c);g.Vm(e,"AID",a.li);G6(a,e);c=new b6(a,a.l,c,a.Sh+1);c.bh=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.yd=c;d6(c,e,d)},G6=function(a,b){if(a.Tc){var c=a.Tc.Iv();
c&&g.Lb(c,function(d,e){g.Vm(b,e,d)})}},N6=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Sg&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Sg?e:f-d;try{g.Lb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},Q6=function(a){a.Sb||a.nf||(a.C=1,a.nf=r6((0,g.x)(a.gz,a),0),a.Kh=0)},S6=function(a){if(a.Sb||a.nf||3<=a.Kh)return!1;
a.C++;a.nf=r6((0,g.x)(a.gz,a),R6(a,a.Kh));a.Kh++;return!0},z6=function(a,b,c){a.lo=c;
a.Ie=b.Bf;a.A||K6(a)},L6=function(a){null!=a.Wg&&(g.v.clearTimeout(a.Wg),a.Wg=null)},R6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U6=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.x)(a.JM,a);c||(c=new g.Nm("//www.google.com/images/cleardot.gif"),g5(c));t6(c.toString(),1E4,d)}else h6(2);T6(a,b)},T6=function(a,b){a.g=0;
a.Tc&&a.Tc.Ku(b);H6(a);F6(a)},H6=function(a){a.g=0;
a.Ie=-1;if(a.Tc)if(0==a.o.length&&0==a.i.length)a.Tc.mp();else{g.ib(a.o);var b=g.ib(a.i);a.o.length=0;a.i.length=0;a.Tc.mp(b)}},x6=function(a,b,c){var d=g.Wm(c);
if(""!=d.g)b&&g.Pm(d,b+"."+d.g),g.Qm(d,d.u);else{var e=window.location;d=gqa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.zj&&g.Lb(a.zj,function(f,k){g.Vm(d,k,f)});
g.Vm(d,"VER",a.Sg);G6(a,d);return d},r6=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},h6=function(a){V6.dispatchEvent(new C6(V6,a))},W6=function(){},vqa=function(a,b){this.action=a;
this.params=b||{}},X6=function(a,b){g.D.call(this);
this.g=new g.M(this.nL,0,this);g.G(this,this.g);this.Wc=5E3;this.i=0;if(g.Oa(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Oa(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},Y6=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Bo;this.i=new X6(this.nM,this);this.g=null;this.fb=!1;this.u=null;this.F="";this.D=this.o=0;this.C=[];this.I=c||!1},wqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.lo,sessionId:a.g.l,arrayId:a.g.li}},Z6=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&P6(a.g),I6(a.g));a.D=0},$6=function(a){return!!a.g&&3==a.g.g},xqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},a7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.Sg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Tg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.i=!1))},b7=function(a,b){var c=a.g;
if(g.Ea(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.ch(c+b,{})},c7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.o,d,!0),onError:g.Sa(a.l,e),ie:g.Sa(a.u,e)};c&&(a.ub=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Fq(b,a)},yqa=function(){var a=d7;
e7();f7.push(a);g7(f7)},h7=function(a,b){e7();
var c=f7,d=zqa(a,String(b));0==c.length?Aqa(d):(g7(c),(0,g.z)(c,function(e){e(d)}))},e7=function(){f7||(f7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",f7,void 0))},Aqa=function(a){var b=(i7+1)%50;
i7=b;j7[b]=a;k7||(k7=49==b)},g7=function(a){var b=j7;
if(b[0]){var c=i7,d=k7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.z)(a,function(f){f(e)})}while(d!=c);
j7=Array(50);i7=-1;k7=!1}},zqa=function(a,b){var c=((0,g.H)()-Bqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},l7=function(a){g.P.call(this);
this.C=a;this.g=[]},m7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},Cqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Yd)(a.g,function(f){return!!G5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=m7(a,b[d])||c;return c},Dqa=function(a,b){var c=a.g.length;
a.g=(0,g.Yd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},n7=function(a,b,c,d){g.P.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},p7=function(a){l7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;o7(this);this.info("Initializing with "+E5(this.g))},q7=function(a){if(a.g.length){var b=(0,g.B)(a.g,function(d){return d.id}),c=b7(a.l,"/pairing/get_lounge_token_batch");
c7(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.wD,a),(0,g.x)(a.vD,a))}},o7=function(a){var b=C5(P5());
b=(0,g.Yd)(b,function(c){return!c.uuid});
return Cqa(a,b)},r7=function(a,b){oqa((0,g.B)(a.g,B5));
b&&Q5()},t7=function(a,b){g.P.call(this);
this.A=b;var c=g.gt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;s7("Initialized with "+g.Kg(this.g))},u7=function(a,b,c){var d=b7(a.u,"/pairing/get_screen_availability");
c7(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},v7=function(a,b){a:if(t5(b)!=t5(a.g))var c=!1;
else{c=g.Sb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(s7("Updated online screens: "+g.Kg(a.g)),a.g=b,a.N("screenChange"));Eqa(a)},w7=function(a){isNaN(a.l)||g.Kp(a.l);
a.l=g.Ip((0,g.x)(a.rs,a),0<a.o&&a.o<(0,g.H)()?2E4:1E4)},s7=function(a){h7("OnlineScreenService",a)},x7=function(a){var b={};
(0,g.z)(a.A(),function(c){c.token?b[c.token]=c.id:this.Hb("Requesting availability of screen w/o lounge token.")});
return b},Eqa=function(a){a=g.Sb(g.Mb(a.g,function(b){return b}));
g.rb(a);a.length?g.ft("yt-remote-online-screen-ids",a.join(","),60):I5("yt-remote-online-screen-ids")},y7=function(a){l7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};Fqa(this)},A7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Hd();if(k=(c?H5(k,c):null)||H5(k,b)){k.uuid=b;var l=z7(a,k);u7(a.i,l,function(m){e(m?l:null)})}else c?Gqa(a,c,(0,g.x)(function(m){var n=z7(this,new z5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));u7(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},B7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},Gqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ub:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Fq(b7(a.A,"/pairing/get_lounge_token_batch"),e)},C7=function(a){a.g=a.l.Hd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+E5(a.g))},Fqa=function(a){D7(a);
a.l=new p7(a.A);a.l.subscribe("screenChange",(0,g.x)(a.ED,a));C7(a);a.o=C5(g.gt("yt-remote-automatic-screen-cache")||[]);D7(a);a.info("Initializing automatic screens: "+E5(a.o));a.i=new t7(a.A,(0,g.x)(a.Hd,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.N("onlineScreenChange")},a))},z7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=H5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.ft("yt-remote-automatic-screen-cache",(0,g.B)(a.o,B5)));D7(a);a.u[b.uuid]=b.id;g.ft("yt-remote-device-id-map",a.u,31536E3);return b},D7=function(a){a.u=g.gt("yt-remote-device-id-map")||{}},E7=function(a,b,c){g.P.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},F7=function(a,b){h7(a.P,b)},H7=function(a,b){E7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.x)(this.oN,this);this.u=(0,g.x)(this.QL,this);this.o=g.Ip((0,g.x)(function(){G7(this,null)},this),12E4)},Hqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ja,(0,g.x)(function(){F7(this,"Failed to send message: getMdxSessionStatus.")},a)):F7(a,"Sending yt message without session: "+g.Kg(b))},G7=function(a,b){g.Kp(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.xn,a),d=(0,g.x)(a.Kd,a);a.Yv(b,c,d,5)}}else a.Kd(Error("Waiting for session status timed out."))},I7=function(a,b,c){E7.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.C=g.Ja;this.A=NaN;this.I=(0,g.x)(this.rN,this);this.g=g.Ja},J7=function(a){a.g=a.F.qB(a.H,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ja;
this.xn(b)},a),(0,g.x)(function(b){this.g=g.Ja;
this.Kd(b)},a))},K7=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}T5()&&(b.env_useStageMdx=1);return g.ah(b)},L7=function(a,b){E7.call(this,a,b,"ManualSession");
this.g=g.Ip((0,g.x)(this.ni,this,null),150)},M7=function(a,b,c,d){g.P.call(this);
this.i=a;this.C=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.wK,this)},N7=function(a,b){return b?g.Ya(a.l,function(c){return A5(b,c.label)},a):null},O7=function(a){h7("Controller",a)},d7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},P7=function(a){return a.u||!!a.l.length||!!a.g},Q7=function(a,b,c){b!=a.g&&(g.qf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.fz,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.ni(null)):a.N("yt-remote-cast2-session-change",null))},R7=function(a){var b=a.i.pB(),c=a.g&&a.g.i;
a=(0,g.B)(b,function(d){c&&A5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=N7(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Lqa=function(a,b,c,d,e,f,k){Iqa()?Jqa(b,e,f,k)&&(T7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?U7(a,c):(window.__onGCastApiAvailable=function(l,m){l?U7(a,c):(V7("Failed to load cast API: "+m),W7(!1),T7(!1),I5("yt-remote-cast-available"),I5("yt-remote-cast-receiver"),X7(),c(!1))},d?g.Vp("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?sqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?Y5():(Z5(),X5(Kqa.map(qqa))))):S7("Cannot initialize because not running Chrome")},X7=function(){S7("dispose");
var a=Y7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);Z7(!1);g.Qp($7);$7.length=0},a8=function(){return!!g.gt("yt-remote-cast-installed")},b8=function(){var a=g.gt("yt-remote-cast-receiver");
return a?a.friendlyName:null},c8=function(){S7("clearCurrentReceiver");
I5("yt-remote-cast-receiver")},d8=function(){return a8()?Y7()?Y7().getCastSession():(V7("getCastSelector: Cast is not initialized."),null):(V7("getCastSelector: Cast API is not installed!"),null)},f8=function(){a8()?Y7()?e8()?(S7("Requesting cast selector."),Y7().requestSession()):(S7("Wait for cast API to be ready to request the session."),$7.push(g.Pp("yt-remote-cast2-api-ready",f8))):V7("requestCastSelector: Cast is not initialized."):V7("requestCastSelector: Cast API is not installed!")},g8=function(a,
b){e8()?Y7().setConnectedScreenStatus(a,b):V7("setConnectedScreenStatus called before ready.")},Iqa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Ow||a},Mqa=function(a,b){Y7().init(a,b)},Jqa=function(a,b,c,d){var e=!1;
Y7()||(a=new M7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.ft("yt-remote-cast-available",f);x5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){S7("onReceiverSelected: "+f.friendlyName);
g.ft("yt-remote-cast-receiver",f);x5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){S7("onReceiverResumed: "+f.friendlyName);
g.ft("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){S7("onSessionChange: "+D5(f));
f||I5("yt-remote-cast-receiver");x5("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
S7("cloudview.createSingleton_: "+e);return e},Y7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},U7=function(a,b){W7(!0);
T7(!1);Mqa(a,function(c){c?(Z7(!0),g.Sp("yt-remote-cast2-api-ready")):(V7("Failed to initialize cast API."),W7(!1),I5("yt-remote-cast-available"),I5("yt-remote-cast-receiver"),X7());b(c)})},S7=function(a){h7("cloudview",a)},V7=function(a){h7("cloudview",a)},W7=function(a){S7("setCastInstalled_ "+a);
g.ft("yt-remote-cast-installed",a)},e8=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},Z7=function(a){S7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},T7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},h8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.C=0;this.g=null;this.hasNext=this.Je=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},i8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Je=!1;a.hasNext=!1;a.C=0;a.A=(0,g.H)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},j8=function(a){return 1==a.playerState?((0,g.H)()-a.A)/1E3:0},k8=function(a,b){a.C=b;
a.A=(0,g.H)()},l8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.A)/1E3+a.C;
case -1E3:return 0}return a.C},m8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&i8(a)},n8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.g);b.hasPrevious=a.Je;b.hasNext=a.hasNext;b.playerTime=a.C;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},q8=function(a,b){g.P.call(this);
this.g=0;this.o=a;this.A=[];this.u=new w5;this.l=this.i=null;this.F=(0,g.x)(this.sI,this);this.C=(0,g.x)(this.Ek,this);this.D=(0,g.x)(this.rI,this);this.H=(0,g.x)(this.GI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.qt,this),o8(this))):c=3;0!=c&&(b?this.qt(c):g.Ip((0,g.x)(function(){this.qt(c)},this),0));
var d=d8();d&&p8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},r8=function(a){return new h8(a.o.getPlayerContextData())},o8=function(a){(0,g.z)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Sa(this.tK,b),this))},a)},s8=function(a){(0,g.z)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},t8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},v8=function(a,b,c){var d=r8(a);
k8(d,c);-1E3!=d.playerState&&(d.playerState=b);u8(a,d)},w8=function(a,b,c){a.o.sendMessage(b,c)},u8=function(a,b){s8(a);
a.o.setPlayerContextData(n8(b));o8(a)},p8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.C),a.Ek(null));
a.l=b;a.l&&(h7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.C),a.l.media.length&&a.Ek(a.l.media[0]))},x8=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=r8(a);b.contentId!=d.videoId&&h7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;k8(d,a.i.getEstimatedTime());u8(a,d)}else h7("CP","No cast media video. Ignoring state update.")},y8=function(a,b,c){return(0,g.x)(function(d){this.Hb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Hb("Retrying "+b+" using MDx browser channel."),w8(this,b,c))},a)},z8=function(a,b,c){g.P.call(this);
this.u=NaN;this.I=!1;this.D=this.C=this.F=this.H=NaN;this.P=[];this.o=this.A=this.l=this.Oa=this.g=null;this.O=a;this.P.push(g.Nr(window,"beforeunload",(0,g.x)(this.pD,this)));this.i=[];this.Oa=new h8;this.M=b.id;this.g=Nqa(this,c);this.g.subscribe("handlerOpened",this.wI,this);this.g.subscribe("handlerClosed",this.tI,this);this.g.subscribe("handlerError",this.uI,this);this.g.subscribe("handlerMessage",this.vI,this);xqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Oa.videoId;
g.ht()&&g.ft("yt-remote-session-video-id",d)},this)},A8=function(a){h7("conn",a)},Nqa=function(a,b){return new Y6(b7(a.O,"/bc"),b)},B8=function(a,b){a.N("proxyStateChange",b)},Oqa=function(a){a.u=g.Ip((0,g.x)(function(){A8("Connecting timeout");
this.Oh(1)},a),2E4)},C8=function(a){g.Kp(a.u);
a.u=NaN},D8=function(a){g.Kp(a.H);
a.H=NaN},Pqa=function(a){E8(a);
a.F=g.Ip((0,g.x)(function(){F8(this,"getNowPlaying")},a),2E4)},E8=function(a){g.Kp(a.F);
a.F=NaN},H8=function(a,b){b&&(C8(a),D8(a));
b==($6(a.g)&&isNaN(a.u))?b&&(B8(a,1),F8(a,"getSubtitlesTrack")):b?(a.Vv()&&a.Oa.reset(),B8(a,1),F8(a,"getNowPlaying"),G8(a)):a.Oh(1)},Qqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Oa.videoId&&(g.Yb(b.params)?a.Oa.g=null:a.Oa.g=b.params,a.N("remotePlayerChange"))},I8=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Oa.listId=b.params.listId||a.Oa.listId;m8(a.Oa,c,d);a.N("remoteQueueChange")},Rqa=function(a,b){b.params=b.params||{};
I8(a,b);J8(a,b);a.N("autoplayDismissed")},J8=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
k8(a.Oa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Oa.playerState&&(c=-1E3);a.Oa.playerState=c;c=Number(b.params.loadedTime);a.Oa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Oa.D=isNaN(c)?0:c;c=a.Oa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Oa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Oa.playerState?Pqa(a):E8(a);a.N("remotePlayerChange")},Sqa=function(a,b){if(-1E3!=
a.Oa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Oa.playerState=c;c=parseInt(b.params.currentTime,10);k8(a.Oa,isNaN(c)?0:c);a.N("remotePlayerChange")}},Tqa=function(a,b){var c="true"==b.params.muted;
a.Oa.volume=parseInt(b.params.volume,10);a.Oa.muted=c;a.N("remotePlayerChange")},Uqa=function(a,b){a.A=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},Vqa=function(a,b){var c="true"==b.params.hasNext;
a.Oa.Je="true"==b.params.hasPrevious;a.Oa.hasNext=c;a.N("previousNextChange")},G8=function(a){g.Kp(a.D);
a.D=g.Ip((0,g.x)(a.Oh,a,1),864E5)},F8=function(a,b,c){c?A8("Sending: action="+b+", params="+g.Kg(c)):A8("Sending: action="+b);
a.g.sendMessage(b,c)},K8=function(a){l7.call(this,"ScreenServiceProxy");
this.Vc=a;this.i=[];this.i.push(this.Vc.$_s("screenChange",(0,g.x)(this.mN,this)));this.i.push(this.Vc.$_s("onlineScreenChange",(0,g.x)(this.XJ,this)))},$qa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Ap("MDX_CONFIG")||b;mqa();N5();L8||(L8=new a7(b?b.loungeApiHost:void 0),T5()&&(L8.g="/api/loungedev"));M8||(M8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",M8,void 0));Wqa();var c=N8();if(!c){var d=new y7(L8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=N8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Lqa(a,d,function(m){m?O8()&&g8(O8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){x5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),P8("Initializing: "+g.Kg(b)),Q8.push(g.Pp("yt-remote-cast2-availability-change",function(){x5("yt-remote-receiver-availability-change")})),Q8.push(g.Pp("yt-remote-cast2-receiver-selected",function(){R8(null);
x5("yt-remote-auto-connect","cast-selector-receiver")})),Q8.push(g.Pp("yt-remote-cast2-receiver-resumed",function(){x5("yt-remote-receiver-resumed","cast-selector-receiver")})),Q8.push(g.Pp("yt-remote-cast2-session-change",Xqa)),Q8.push(g.Pp("yt-remote-connection-change",function(m){m?g8(O8(),"YouTube TV"):S8()||(g8(null,null),c8())})),a=T8(),b.isAuto&&(a.id+="#dial"),g.wq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),P8(" -- with channel params: "+
g.Kg(a)),Yqa(a),c.start(),O8()||Zqa())},ara=function(){var a=U8();
a8()&&g.gt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},U8=function(){var a=N8().Vc.$_gos();
var b=V8();b&&W8()&&(G5(a,b)||a.push(b));return lqa(a)},X8=function(){var a=bra();
!a&&a8()&&b8()&&(a={key:"cast-selector-receiver",name:b8()});return a},bra=function(){var a=U8(),b=V8();
b||(b=S8());return g.Ya(a,function(c){return b&&A5(b,c.key)?!0:!1})},V8=function(){var a=O8();
if(!a)return null;var b=N8().Hd();return H5(b,a)},Xqa=function(a){P8("remote.onCastSessionChange_: "+D5(a));
if(a){var b=V8();b&&b.id==a.id?g8(b.id,"YouTube TV"):(b&&Y8(),Z8(a,1))}else W8()&&Y8()},Y8=function(){e8()?Y7().stopSession():V7("stopSession called before API ready.");
var a=W8();a&&(a.disconnect(1),$8(null))},a9=function(){var a=W8();
return!!a&&3!=a.getProxyState()},P8=function(a){h7("remote",a)},N8=function(){if(!b9){var a=g.w("yt.mdx.remote.screenService_");
b9=a?new K8(a):null}return b9},O8=function(){return g.w("yt.mdx.remote.currentScreenId_")},c9=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},d9=function(){return g.w("yt.mdx.remote.connectData_")},R8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},W8=function(){return g.w("yt.mdx.remote.connection_")},$8=function(a){var b=W8();
R8(null);a||c9("");g.Ia("yt.mdx.remote.connection_",a,void 0);M8&&((0,g.z)(M8,function(c){c(a)}),M8.length=0);
b&&!a?x5("yt-remote-connection-change",!1):!b&&a&&x5("yt-remote-connection-change",!0)},S8=function(){var a=g.ht();
if(!a)return null;var b=N8().Hd();return H5(b,a)},Z8=function(a,b){V8()&&V8();
if(e9)f9=a;else{c9(a.id);var c=new z8(L8,a,T8());c.connect(b,d9());c.subscribe("beforeDisconnect",function(d){x5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){W8()&&$8(null)});
$8(c)}},Zqa=function(){var a=S8();
a?(P8("Resume connection to: "+D5(a)),Z8(a,0)):(R5(),c8(),P8("Skipping connecting because no session screen found."))},Wqa=function(){var a=T8();
if(g.Yb(a)){a=M5();var b=g.gt("yt-remote-session-name")||"",c=g.gt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},T8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Yqa=function(a){a?(g.ft("yt-remote-session-app",a.app),g.ft("yt-remote-session-name",a.name)):(I5("yt-remote-session-app"),I5("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},g9=function(a,b,c){g.D.call(this);
this.u=a;this.i=b;this.l=new g.rs(this);g.G(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.rJ);this.l.K(b,"captionschanged",this.qI);this.l.K(b,"captionssettingschanged",this.EA);this.l.K(b,"videoplayerreset",this.yn);this.l.K(b,"mdxautoplaycancel",this.rC);this.O=this.l.K(b,"onVolumeChange",this.Qy);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.bz,this);c.subscribe("remotePlayerChange",this.Gk,this);c.subscribe("remoteQueueChange",this.yn,this);c.subscribe("autoplayUpNext",this.Fy,
this);c.subscribe("previousNextChange",this.Yy,this);c.subscribe("nowAutoplaying",this.Uy,this);c.subscribe("autoplayDismissed",this.Ey,this);this.suggestion=null;this.F=new g.iC(64);this.o=new g.M(this.CA,500,this);g.G(this,this.o);this.A=new g.M(this.DA,1E3,this);g.G(this,this.A);this.I=new $5(this.TM,0,this);g.G(this,this.I);this.C={};this.P=new g.M(this.cB,1E3,this);g.G(this,this.P);this.H=new g.Al(this.NF,1E3,this);g.G(this,this.H);this.M=g.Ja;this.EA();this.yn();this.Gk()},h9=function(a,b){a.u.Kc(b,
a.i.getVideoData().lengthSeconds)},j9=function(a){h9(a,0);
a.o.stop();i9(a,new g.iC(64))},l9=function(a,b){if(k9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.fc(c,b));a.g.rA(a.i.getVideoData(1).videoId,c);a.C=r8(a.g).g}},m9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ra;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Ef,s5(c));i9(a,new g.iC(1))},n9=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{HQ:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},k9=function(a){return r8(a.g).videoId==a.i.getVideoData(1).videoId},i9=function(a,b){a.A.stop();
var c=a.F;if(!g.oC(c,b)){var d=g.U(b,2);d!=g.U(a.F,2)&&g.aK(a.i,d);a.F=b;o9(a.u,c,b)}},p9=function(){g.W.call(this,{B:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{B:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{B:"div",G:"ytp-mdx-popup-title",T:"\u0e04\u0e38\u0e13\u0e44\u0e14\u0e49\u0e2d\u0e2d\u0e01\u0e08\u0e32\u0e01\u0e23\u0e30\u0e1a\u0e1a\u0e41\u0e25\u0e49\u0e27"},{B:"div",G:"ytp-mdx-popup-description",T:"\u0e23\u0e30\u0e1a\u0e1a\u0e2d\u0e32\u0e08\u0e40\u0e1e\u0e34\u0e48\u0e21\u0e27\u0e34\u0e14\u0e35\u0e42\u0e2d\u0e17\u0e35\u0e48\u0e04\u0e38\u0e13\u0e14\u0e39\u0e25\u0e07\u0e43\u0e19\u0e1b\u0e23\u0e30\u0e27\u0e31\u0e15\u0e34\u0e01\u0e32\u0e23\u0e14\u0e39\u0e02\u0e2d\u0e07 TV \u0e41\u0e25\u0e30\u0e2a\u0e48\u0e07\u0e1c\u0e25\u0e01\u0e31\u0e1a\u0e04\u0e33\u0e41\u0e19\u0e30\u0e19\u0e33\u0e02\u0e2d\u0e07 TV \u0e2b\u0e32\u0e01\u0e44\u0e21\u0e48\u0e15\u0e49\u0e2d\u0e07\u0e01\u0e32\u0e23\u0e43\u0e2b\u0e49\u0e40\u0e01\u0e34\u0e14\u0e01\u0e23\u0e13\u0e35\u0e14\u0e31\u0e07\u0e01\u0e25\u0e48\u0e32\u0e27 \u0e42\u0e1b\u0e23\u0e14\u0e22\u0e01\u0e40\u0e25\u0e34\u0e01\u0e41\u0e25\u0e30\u0e25\u0e07\u0e0a\u0e37\u0e48\u0e2d\u0e40\u0e02\u0e49\u0e32\u0e43\u0e0a\u0e49 YouTube \u0e1a\u0e19\u0e04\u0e2d\u0e21\u0e1e\u0e34\u0e27\u0e40\u0e15\u0e2d\u0e23\u0e4c"},
{B:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{B:"button",W:["ytp-button","ytp-mdx-privacy-popup-cancel"],T:"\u0e22\u0e01\u0e40\u0e25\u0e34\u0e01"},{B:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],T:"\u0e22\u0e37\u0e19\u0e22\u0e31\u0e19"}]}]}]});this.l=new g.WP(this,250);g.G(this,this.l);this.C=this.i["ytp-mdx-privacy-popup-cancel"];this.K(this.C,"click",this.o);this.u=this.i["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},r9=function(a){g.W.call(this,{B:"div",
G:"ytp-remote",J:[{B:"div",G:"ytp-remote-display-status",J:[{B:"div",G:"ytp-remote-display-status-icon",J:[g.lP()]},{B:"div",G:"ytp-remote-display-status-text",T:"{{statustext}}"}]}]});this.l=new g.WP(this,250);g.G(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);q9(this,g.XJ(a))},q9=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.jN("\u0e40\u0e01\u0e34\u0e14\u0e02\u0e49\u0e2d\u0e1c\u0e34\u0e14\u0e1e\u0e25\u0e32\u0e14\u0e1a\u0e19 $RECEIVER_NAME",c):g.pC(b)||g.U(b,4)?g.jN("\u0e01\u0e33\u0e25\u0e31\u0e07\u0e40\u0e25\u0e48\u0e19\u0e1a\u0e19 $RECEIVER_NAME",c):g.jN("\u0e40\u0e0a\u0e37\u0e48\u0e2d\u0e21\u0e15\u0e48\u0e2d\u0e01\u0e31\u0e1a $RECEIVER_NAME \u0e41\u0e25\u0e49\u0e27",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},s9=function(a,b){g.GT.call(this,"\u0e40\u0e25\u0e48\u0e19\u0e1a\u0e19",0,a,
b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},t9=function(a){g.zK.call(this,a);
this.i={key:F5(),name:"\u0e04\u0e2d\u0e21\u0e1e\u0e34\u0e27\u0e40\u0e15\u0e2d\u0e23\u0e4c\u0e40\u0e04\u0e23\u0e37\u0e48\u0e2d\u0e07\u0e19\u0e35\u0e49"};this.u=null;this.o=[];this.C=this.g=null;this.A=[this.i];this.l=this.i;this.pk=new g.iC(64);this.H=0;this.Lm=-1;if(!g.Oy(g.X(this.player))){a=this.player;var b=g.cD(a);b&&(b=b.en())&&(b=new s9(a,b),g.G(this,b));b=new r9(a);g.G(this,b);g.lK(a,b.element,4);this.F=new p9;g.G(this,this.F);g.lK(a,this.F.element,4);this.D=!!S8()}},o9=function(a,b,c){a.pk=
c;
a.player.N("presentingplayerstatechange",new g.tD(c,b))},u9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)Y8();
else{var c;if(c=g.Q(g.X(a.player).experiments,"mdx_enable_privacy_disclosure"))c=g.Ap("PLAYER_CONFIG"),c=!(c&&c.args&&void 0!==c.args.authuser||g.Ap("SESSION_INDEX")||g.Ap("LOGGED_IN"));c&&!a.D&&(a.player.pauseVideo(),a.F.l.show(),W8()||(e9=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,
playerParams:c.playerParams,clickTrackingParams:c.Ef,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=s5(c))&&(d.locationInfo=c);c=d}else c=null;P8("Connecting to: "+g.Kg(b));"cast-selector-receiver"==b.key?(R8(c||null),e8()?Y7().setLaunchParams(c||null):V7("setLaunchParams called before ready.")):!c&&a9()&&O8()==b.key?x5("yt-remote-connection-change",!0):(Y8(),R8(c||null),c=N8().Hd(),(c=H5(c,b.key))&&Z8(c,1))}},bqa=/^https?$/i,cra=["POST",
"PUT"];g.y(q5,g.Sf);g.h=q5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.u=0;this.ba=b;this.O=!1;this.i=!0;this.g=this.M?i5(this.M):i5(g.GY);this.P=this.M?this.M.getOptions():g.GY.getOptions();this.g.onreadystatechange=(0,g.x)(this.kw,this);try{f5(j5(this,"Opening Xhr")),this.V=!0,this.g.open(b,String(a),!0),this.V=!1}catch(f){f5(j5(this,"Error opening Xhr: "+f.message));n5(this,f);return}a=c||
"";var e=this.headers.clone();d&&Zpa(d,function(f,k){e.set(k,f)});
d=g.Ya(e.Gd(),$pa);c=g.v.FormData&&a instanceof g.v.FormData;!g.ab(cra,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Z&&(this.g.responseType=this.Z);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{k5(this),0<this.A&&(this.I=aqa(this.g),f5(j5(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.x)(this.lw,this)):this.F=g.Gg(this.lw,this.A,this)),f5(j5(this,"Sending request")),this.C=!0,this.g.send(a),this.C=!1}catch(f){f5(j5(this,"Send error: "+f.message)),n5(this,f)}};
g.h.lw=function(){"undefined"!=typeof g.kY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,j5(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(j5(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),m5(this))};
g.h.U=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),m5(this,!0));q5.Xa.U.call(this)};
g.h.kw=function(){this.ea()||(this.V||this.C||this.o?p5(this):this.vK())};
g.h.vK=function(){p5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<o5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Fa(this.l)?this.l:String(this.l)};
var o6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},n6={"'":"\\'"},dra={};g.h=w5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.ab(this.g,a)||g.ab(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Lma)(b,a);0<=c?(g.cb(b,c),b=!0):b=!1;return b||g.db(this.i,a)};
g.h.zc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var jqa={KN:"atp",VP:"ska",KP:"que",kP:"mus",UP:"sus",BO:"dsp",RP:"seq"};y5.prototype.jg=function(){var a=new y5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var S5,L5="",rqa=U5("loadCastFramework")||U5("loadCastApplicationFramework"),Kqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.y($5,g.D);g.h=$5.prototype;g.h.lD=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.H)()+this.Wc:this.za=g.Gg(this.u,this.Wc)};
g.h.stop=function(){this.za&&(g.v.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.U=function(){this.stop();$5.Xa.U.call(this)};
g.h.mD=function(){this.l?(this.za=g.Gg(this.u,this.l-(0,g.H)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};a6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
a6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=b6.prototype;g.h.bh=null;g.h.xe=!1;g.h.Yi=null;g.h.mt=null;g.h.Hi=null;g.h.Yh=null;g.h.Zf=null;g.h.Gg=null;g.h.uh=null;g.h.tc=null;g.h.jl=0;g.h.Be=null;g.h.oo=null;g.h.rg=null;g.h.Vj=-1;g.h.eA=!0;g.h.Rg=!1;g.h.eq=0;g.h.In=null;var i6={},g6={};g.h=b6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.eM=function(a){a=a.target;var b=this.In;b&&3==o5(a)?b.Rj():this.lB(a)};
g.h.lB=function(a){try{if(a==this.tc)a:{var b=o5(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Md&&!g.pd(10)||g.Od&&!g.od("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ch&&!r5(this.tc))break a;this.Rg||4!=b||7==c||(8==c||0>=d?this.g.te(3):this.g.te(2));s6(this);var e=this.tc.getStatus();this.Vj=e;var f=r5(this.tc);(this.xe=200==e)?(4==b&&k6(this),this.u?(m6(this,b,f),g.Ch&&this.xe&&3==b&&(this.aa.ca(this.i,"tick",this.XL),this.i.start())):j6(this,f),this.xe&&!this.Rg&&(4==b?this.g.vn(this):(this.xe=
!1,f6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.rg=3,h6(13)):(this.rg=0,h6(14)),k6(this),l6(this))}}catch(k){this.tc&&r5(this.tc)}finally{}};
g.h.XL=function(){var a=o5(this.tc),b=r5(this.tc);this.jl<b.length&&(s6(this),m6(this,a,b),this.xe&&4!=a&&f6(this))};
g.h.vL=function(a){r6((0,g.x)(this.uL,this,a),0)};
g.h.uL=function(a){this.Rg||(s6(this),j6(this,a),f6(this))};
g.h.iz=function(a){r6((0,g.x)(this.tL,this,a),0)};
g.h.tL=function(a){this.Rg||(k6(this),this.xe=a,this.g.vn(this),this.g.te(4))};
g.h.cancel=function(){this.Rg=!0;k6(this)};
g.h.FL=function(){this.Yi=null;var a=(0,g.H)();0<=a-this.mt?(2!=this.Yh&&this.g.te(3),k6(this),this.rg=2,h6(18),l6(this)):q6(this,this.mt-a)};
g.h.getLastError=function(){return this.rg};g.h=w6.prototype;g.h.bq=null;g.h.Cd=null;g.h.Jn=!1;g.h.jw=null;g.h.fm=null;g.h.Oq=null;g.h.cq=null;g.h.ce=null;g.h.Bf=-1;g.h.Uj=null;g.h.mj=null;g.h.connect=function(a){this.cq=a;a=x6(this.g,null,this.cq);h6(3);this.jw=(0,g.H)();var b=this.g.D;null!=b?(this.Uj=b[0],(this.mj=b[1])?(this.ce=1,y6(this)):(this.ce=2,A6(this))):(h5(a,"MODE","init"),this.Cd=new b6(this,void 0,void 0,void 0),this.Cd.bh=this.bq,e6(this.Cd,a,!1,null,!0),this.ce=0)};
g.h.sC=function(a){if(a)this.ce=2,A6(this);else{h6(4);var b=this.g;b.Ie=b.hg.Bf;U6(b,9)}a&&this.te(2)};
g.h.Ap=function(a){return this.g.Ap(a)};
g.h.abort=function(){this.Cd&&(this.Cd.cancel(),this.Cd=null);this.Bf=-1};
g.h.iw=function(){return!1};
g.h.cz=function(a,b){this.Bf=a.Vj;if(0==this.ce)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ie=this.Bf;U6(c,2);return}this.Uj=c[0];this.mj=c[1]}else c=this.g,c.Ie=this.Bf,U6(c,2);else if(2==this.ce)if(this.Jn)h6(7),this.Oq=(0,g.H)();else if("11111"==b){if(h6(6),this.Jn=!0,this.fm=(0,g.H)(),c=this.fm-this.jw,!g.Md||g.pd(10)||500>c)this.Bf=200,this.Cd.cancel(),h6(12),z6(this.g,this,!0)}else h6(8),this.fm=this.Oq=(0,g.H)(),this.Jn=!1};
g.h.vn=function(){this.Bf=this.Cd.Vj;if(this.Cd.xe)0==this.ce?this.mj?(this.ce=1,y6(this)):(this.ce=2,A6(this)):2==this.ce&&((!g.Md||g.pd(10)?!this.Jn:200>this.Oq-this.fm)?(h6(11),z6(this.g,this,!1)):(h6(12),z6(this.g,this,!0)));else{0==this.ce?h6(9):2==this.ce&&h6(10);var a=this.g;this.Cd.getLastError();a.Ie=this.Bf;U6(a,2)}};
g.h.Tk=function(){return this.g.Tk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.te=function(a){this.g.te(a)};g.h=B6.prototype;g.h.zj=null;g.h.yd=null;g.h.Sb=null;g.h.Zp=null;g.h.hm=null;g.h.zu=null;g.h.sm=null;g.h.Bk=0;g.h.KH=0;g.h.Tc=null;g.h.ng=null;g.h.nf=null;g.h.Wg=null;g.h.hg=null;g.h.lo=null;g.h.li=-1;g.h.Pw=-1;g.h.Ie=-1;g.h.Sh=0;g.h.Kh=0;g.h.Sg=8;var V6=new g.Sf;g.y(C6,g.sf);g.y(D6,g.sf);g.y(E6,g.sf);g.h=B6.prototype;g.h.connect=function(a,b,c,d,e){h6(0);this.Zp=b;this.zj=c||{};d&&g.Ea(e)&&(this.zj.OSID=d,this.zj.OAID=e);this.A?(r6((0,g.x)(this.Su,this,a),100),K6(this)):this.Su(a)};
g.h.Su=function(a){this.hg=new w6(this);this.hg.bq=null;this.hg.i=this.u;this.hg.connect(a)};
g.h.iw=function(){return 0==this.g};
g.h.hz=function(a){this.ng=null;P6(this,a)};
g.h.gz=function(){this.nf=null;this.Sb=new b6(this,this.l,"rpc",this.C);this.Sb.bh=null;this.Sb.eq=0;var a=this.zu.clone();g.Vm(a,"RID","rpc");g.Vm(a,"SID",this.l);g.Vm(a,"CI",this.lo?"0":"1");g.Vm(a,"AID",this.li);G6(this,a);if(!g.Md||g.pd(10))g.Vm(a,"TYPE","xmlhttp"),e6(this.Sb,a,!0,this.sm,!1);else{g.Vm(a,"TYPE","html");var b=this.Sb,c=!!this.sm;b.Yh=3;b.Zf=g5(a.clone());p6(b,c)}};
g.h.cz=function(a,b){if(0!=this.g&&(this.Sb==a||this.yd==a))if(this.Ie=a.Vj,this.yd==a&&3==this.g)if(7<this.Sg){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ma(c)&&3==c.length)if(0==c[0])a:{if(!this.nf){if(this.Sb)if(this.Sb.Hi+3E3<this.yd.Hi)L6(this),this.Sb.cancel(),this.Sb=null;else break a;S6(this);h6(19)}}else this.Pw=c[1],0<this.Pw-this.li&&37500>c[2]&&this.lo&&0==this.Kh&&!this.Wg&&(this.Wg=r6((0,g.x)(this.mI,this),6E3));else U6(this,11)}else b!=dra.gO.g&&U6(this,11);else if(this.Sb==a&&
L6(this),!g.xb(b)){c=this.u.parse(b);g.Ma(c);for(var d=0;d<c.length;d++){var e=c[d];this.li=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.sm=e[2],e=e[3],null!=e?this.Sg=e:this.Sg=6,this.g=3,this.Tc&&this.Tc.Mu(),this.zu=x6(this,this.Tk()?this.sm:null,this.Zp),Q6(this)):"stop"==e[0]&&U6(this,7):3==this.g&&("stop"==e[0]?U6(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.Lu(e),this.Kh=0)}}};
g.h.mI=function(){null!=this.Wg&&(this.Wg=null,this.Sb.cancel(),this.Sb=null,S6(this),h6(20))};
g.h.vn=function(a){if(this.Sb==a){L6(this);this.Sb=null;var b=2}else if(this.yd==a)this.yd=null,b=1;else return;this.Ie=a.Vj;if(0!=this.g)if(a.xe)1==b?(b=(0,g.H)()-a.Hi,V6.dispatchEvent(new D6(V6,a.uh?a.uh.length:0,b,this.Sh)),J6(this),this.o.length=0):Q6(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ie)){if(d=1==b)this.yd||this.ng||1==this.g||2<=this.Sh?d=!1:(this.ng=r6((0,g.x)(this.hz,this,a),R6(this,this.Sh)),this.Sh++,d=!0);d=!(d||2==b&&S6(this))}if(d)switch(c){case 1:U6(this,
5);break;case 4:U6(this,10);break;case 3:U6(this,6);break;case 7:U6(this,12);break;default:U6(this,2)}}};
g.h.LC=function(a){if(!g.ab(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.JM=function(a){a?h6(2):(h6(1),T6(this,8))};
g.h.Ap=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new q5;a.R=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.te=function(a){V6.dispatchEvent(new E6(V6,a))};
g.h.Tk=function(){return!(!g.Md||g.pd(10))};
g.h=W6.prototype;g.h.Mu=function(){};
g.h.Lu=function(){};
g.h.Ku=function(){};
g.h.mp=function(){};
g.h.Iv=function(){return{}};
g.h.isActive=function(){return!0};g.y(X6,g.D);g.h=X6.prototype;g.h.nL=function(){this.Wc=Math.min(3E5,2*this.Wc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Wc+15E3*Math.random();g.bo(this.g,a);this.i=(0,g.H)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Wc=5E3};g.y(Y6,W6);g.h=Y6.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Lf=function(a){return this.l.eh(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.fb||(this.fb=!0,g.qf(this.l),Z6(this),g.qf(this.i),this.i=null)};
g.h.ea=function(){return this.fb};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new B6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.li):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.C.push(c):$6(this)&&M6(this.g,c)};
g.h.Mu=function(){this.i.reset();this.u=null;this.o=0;if(this.C.length){var a=this.C;this.C=[];for(var b=0,c=a.length;b<c;++b)M6(this.g,a[b])}this.N("handlerOpened")};
g.h.Ku=function(a){var b=2==a&&401==this.g.Ie;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.mp=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.C.push(d)}};
g.h.Iv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.fc(a,this.u);return a};
g.h.Lu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),I6(this.g)):this.N("handlerMessage",new vqa(a[0],a[1]))};
g.h.nM=function(){this.i.isActive();var a=this.g,b=0;a.Sb&&b++;a.yd&&b++;0==b&&this.connect(this.u,this.o)};a7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
a7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
a7.prototype.u=function(a){a(Error("request timed out"))};var Bqa=(0,g.H)(),f7=null,j7=Array(50),i7=-1,k7=!1;g.y(l7,g.P);l7.prototype.Hd=function(){return this.g};
l7.prototype.contains=function(a){return!!G5(this.g,a)};
l7.prototype.get=function(a){return a?H5(this.g,a):null};
l7.prototype.info=function(a){h7(this.C,a)};g.t(n7,g.P);g.h=n7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.oB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.Kp(this.za),this.za=NaN)};
g.h.U=function(){this.stop();g.P.prototype.U.call(this)};
g.h.oB=function(){this.za=NaN;this.g=g.Fq(b7(this.A,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.kN,this),onError:(0,g.x)(this.jN,this),ie:(0,g.x)(this.lN,this)})};
g.h.kN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new z5(c))};
g.h.jN=function(a){this.g=null;a.status&&404==a.status?this.i>=v9.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=v9[this.i],this.za=g.Ip((0,g.x)(this.oB,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.lN=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};
var v9=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.y(p7,l7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.N("screenChange");!g.gt("yt-remote-lounge-token-expiration")&&q7(this);g.Kp(this.i);this.i=g.Ip((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);m7(this,a);r7(this,!1);this.N("screenChange");b(a);a.token||q7(this)};
g.h.remove=function(a,b){var c=o7(this);Dqa(this,a)&&(r7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.fo=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,r7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.U=function(){g.Kp(this.i);p7.Xa.U.call(this)};
g.h.wD=function(a){o7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}r7(this,!b);b&&h7(this.C,"Missed "+b+" lounge tokens.")};
g.h.vD=function(a){h7(this.C,"Requesting lounge tokens failed: "+a)};g.t(t7,g.P);g.h=t7.prototype;g.h.start=function(){var a=parseInt(g.gt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.H)()-144E5<a?0:a)?w7(this):(this.o=(0,g.H)()+3E5,g.ft("yt-remote-fast-check-period",this.o),this.rs())};
g.h.isEmpty=function(){return g.Yb(this.g)};
g.h.update=function(){s7("Updating availability on schedule.");var a=this.A(),b=g.Mb(this.g,function(c,d){return c&&!!H5(a,d)},this);
v7(this,b)};
g.h.U=function(){g.Kp(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.P.prototype.U.call(this)};
g.h.rs=function(){g.Kp(this.l);this.l=NaN;this.i&&this.i.abort();var a=x7(this);if(t5(a)){var b=b7(this.u,"/pairing/get_screen_availability");this.i=c7(this.u,b,{lounge_token:g.Sb(a).join(",")},(0,g.x)(this.RK,this,a),(0,g.x)(this.QK,this))}else v7(this,{}),w7(this)};
g.h.RK=function(a,b){this.i=null;var c=g.Sb(x7(this));if(g.sb(c,g.Sb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;v7(this,d);w7(this)}else this.Hb("Changing Screen set during request."),this.rs()};
g.h.QK=function(a){this.Hb("Screen availability failed: "+a);this.i=null;w7(this)};
g.h.Hb=function(a){h7("OnlineScreenService",a)};g.y(y7,l7);g.h=y7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.fo=function(a,b,c,d){this.l.contains(a)?this.l.fo(a,b,c,d):(a="Updating name of unknown screen: "+a.name,h7(this.C,a),d(Error(a)))};
g.h.Hd=function(a){return a?this.g:g.gb(this.g,(0,g.Yd)(this.o,function(b){return!this.contains(b)},this))};
g.h.pB=function(){return(0,g.Yd)(this.Hd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.qB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.qf(f);d(z7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.qf(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.nN=function(a,b,c,d){g.Fq(b7(this.A,"/pairing/get_screen"),{method:"POST",ub:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new z5(f.screen||{});if(!k.name||B7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);B7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(z7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
ie:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.qf(this.l);g.qf(this.i);y7.Xa.U.call(this)};
g.h.ED=function(){C7(this);this.N("screenChange");this.i.update()};
y7.prototype.dispose=y7.prototype.dispose;g.y(E7,g.P);g.h=E7.prototype;g.h.xn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Kd=function(a){this.ea()||(a&&F7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){h7(this.P,a)};
g.h.sB=function(){return null};
g.h.Ds=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){F7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.Ds("");E7.Xa.U.call(this)};g.y(H7,E7);g.h=H7.prototype;g.h.Cs=function(a){if(this.g){if(this.g==a)return;F7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);Hqa(this)};
g.h.ni=function(a){this.info("launchWithParams no-op for Cast: "+g.Kg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Kd()},this),(0,g.x)(function(){this.Kd(Error("Failed to stop receiver app."))},this)):this.Kd(Error("Stopping cast device witout session."))};
g.h.Ds=g.Ja;g.h.U=function(){this.info("disposeInternal");g.Kp(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;H7.Xa.U.call(this)};
g.h.QL=function(a,b){if(!this.ea())if(b){var c=v5(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kg(c));switch(d){case "mdxSessionStatus":G7(this,c.screenId);break;default:F7(this,"Unknown youtube message: "+d)}}else F7(this,"Unable to parse message.")}else F7(this,"No data in message.")};
g.h.Yv=function(a,b,c,d){A7(this.F,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(F7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Ip((0,g.x)(this.Yv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.sB=function(){return this.g};
g.h.oN=function(a){this.ea()||a||(F7(this,"Cast session died."),this.Kd())};g.y(I7,E7);g.h=I7.prototype;g.h.Cs=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.ni=function(a){this.u=a;this.C()};
g.h.stop=function(){this.g();this.g=g.Ja;g.Kp(this.A);this.o?this.o.stop((0,g.x)(this.Kd,this,null),(0,g.x)(this.Kd,this,"Failed to stop DIAL device.")):this.Kd()};
g.h.U=function(){this.g();this.g=g.Ja;g.Kp(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;I7.Xa.U.call(this)};
g.h.rN=function(a){this.ea()||a||(F7(this,"DIAL session died."),this.g(),this.g=g.Ja,this.Kd())};
g.h.rq=function(a){this.H=F5();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,K7(this));a(b);J7(this)}else this.C=(0,g.x)(function(){g.Kp(this.A);this.C=g.Ja;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,K7(this));a(c);J7(this)},this),this.A=g.Ip((0,g.x)(function(){this.C()},this),100)};
g.h.aE=function(a,b,c){A7(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.xn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.rq(b,c)},this),(0,g.x)(function(d){F7(this,"Failed to get DIAL screen: "+d);
this.rq(b,c)},this))};g.y(L7,E7);L7.prototype.stop=function(){this.Kd()};
L7.prototype.Cs=g.Ja;L7.prototype.ni=function(){g.Kp(this.g);this.g=NaN;var a=H5(this.F.Hd(),this.i.label);a?this.xn(a):this.Kd(Error("No such screen"))};
L7.prototype.U=function(){g.Kp(this.g);this.g=NaN;L7.Xa.U.call(this)};g.y(M7,g.P);g.h=M7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.C);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.AK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.ez,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.NI,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.o),yqa(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.rB,this)),this.l=R7(this),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.x)(function(k){this.Hb("Failed to set initial custom receivers: "+g.Kg(k))},this)),this.N("yt-remote-cast2-availability-change",P7(this)),b(!0))},this),(0,g.x)(function(k){this.Hb("Failed to initialize API: "+g.Kg(k));
b(!1)},this))};
g.h.wM=function(a,b){O7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)O7("Unsetting old screen status: "+this.g.i.friendlyName),Q7(this,null)}if(a&&b){if(!this.g){c=H5(this.i.Hd(),a);if(!c){O7("setConnectedScreenStatus: Unknown screen.");return}var d=N7(this,c);d||(O7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ja,(0,g.x)(function(e){this.Hb("Failed to set initial custom receivers: "+g.Kg(e))},this)));
O7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);Q7(this,new L7(this.i,d),!0)}this.g.Ds(b)}else O7("setConnectedScreenStatus: no screen.")};
g.h.xM=function(a){this.ea()?this.Hb("Setting connection data on disposed cast v2"):this.g?this.g.ni(a):this.Hb("Setting connection data without a session")};
g.h.qN=function(){this.ea()?this.Hb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),Q7(this,null)):O7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.ez,this),(0,g.x)(this.WK,this))};
g.h.U=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.rB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.db(g.w("yt.mdx.remote.debug.handlers_")||[],d7);g.qf(this.g);M7.Xa.U.call(this)};
g.h.Hb=function(a){h7("Controller",a)};
g.h.fz=function(a,b){this.g==a&&(b||Q7(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.wK=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),O7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)O7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{O7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:Q7(this,
new L7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:Q7(this,new I7(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:Q7(this,new H7(this.i,a));break;default:this.Hb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Hb("Stopping receiver w/o session: "+a.friendlyName)}else this.Hb("onReceiverAction_ called without receiver.")};
g.h.NI=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Hb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Hb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return O7("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Hb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);Q7(this,new I7(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.aE,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.x)(b.rq,b))};
g.h.ez=function(a){if(!this.ea()){O7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)O7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),Q7(this,new H7(this.i,b),!0);else{this.Hb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=H5(this.i.Hd(),c.label);d&&A5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(O7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.qf(this.g),this.g=new H7(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.fz,this,this.g)),this.g.ni(null));this.g.Cs(a)}}};
g.h.pN=function(){return this.g?this.g.sB():null};
g.h.WK=function(a){this.ea()||(this.Hb("Failed to estabilish a session: "+g.Kg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&Q7(this,null))};
g.h.AK=function(a){O7("Receiver availability updated: "+a);if(!this.ea()){var b=P7(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;P7(this)!=b&&this.N("yt-remote-cast2-availability-change",P7(this))}};
g.h.rB=function(){this.ea()||(this.l=R7(this),O7("Updating custom receivers: "+g.Kg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ja,(0,g.x)(function(){this.Hb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",P7(this)))};
M7.prototype.setLaunchParams=M7.prototype.xM;M7.prototype.setConnectedScreenStatus=M7.prototype.wM;M7.prototype.stopSession=M7.prototype.qN;M7.prototype.getCastSession=M7.prototype.pN;M7.prototype.requestSession=M7.prototype.requestSession;M7.prototype.init=M7.prototype.init;M7.prototype.dispose=M7.prototype.dispose;var $7=[];h8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";i8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Je=a.hasPrevious,this.hasNext=a.hasNext,this.C=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
h8.prototype.isAdPlaying=function(){return 1081==this.playerState};
h8.prototype.getDuration=function(){return this.u?this.D+j8(this):this.D};
h8.prototype.clone=function(){return new h8(n8(this))};g.t(q8,g.P);g.h=q8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ja,y8(this,"play")):w8(this,"play"),v8(this,1,l8(r8(this))),this.N("remotePlayerChange")):t8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ja,y8(this,"pause")):w8(this,"pause"),v8(this,2,l8(r8(this))),this.N("remotePlayerChange")):t8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=r8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ja,y8(this,"seekTo",{newTime:a}))}else w8(this,"seekTo",{newTime:a});v8(this,3,a);this.N("remotePlayerChange")}else t8(this,g.Sa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ja,y8(this,"stopVideo")):w8(this,"stopVideo");var a=r8(this);a.index=-1;a.videoId="";i8(a);u8(this,a);this.N("remotePlayerChange")}else t8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=r8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){h7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Hb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){h7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Hb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);w8(this,"setVolume",e)}c.muted=b;c.volume=a;u8(this,c)}else t8(this,g.Sa(this.setVolume,a,b))};
g.h.rA=function(a,b){if(1==this.g){var c=r8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Kg(b.style),g.fc(d,c.g));w8(this,"setSubtitlesTrack",d);u8(this,c)}else t8(this,g.Sa(this.rA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();w8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=r8(this);d.audioTrackId=c;u8(this,d)}else t8(this,g.Sa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=r8(this);c=c||0;var m={videoId:a,currentIndex:c};m8(l,a,c);g.Ea(b)&&(k8(l,b),m.currentTime=b);g.Ea(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Kg(k));w8(this,"setPlaylist",m);d||u8(this,l)};
g.h.En=function(a,b){if(1==this.g){if(a&&b){var c=r8(this);m8(c,a,b);u8(this,c)}w8(this,"previous")}else t8(this,g.Sa(this.En,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=r8(this);m8(c,a,b);u8(this,c)}w8(this,"next")}else t8(this,g.Sa(this.nextVideo,a,b))};
g.h.kv=function(){1==this.g?w8(this,"dismissAutoplay"):t8(this,this.kv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}g.P.prototype.dispose.call(this)};
g.h.U=function(){s8(this);this.o=null;this.u.clear();p8(this,null);g.P.prototype.U.call(this)};
g.h.qt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.tK=function(a,b){this.N(a,b)};
g.h.sI=function(a){if(!a)this.Ek(null),p8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=r8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)h7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,u8(this,b)}};
g.h.Ek=function(a){h7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),x8(this),this.N("remotePlayerChange")};
g.h.rI=function(a){a?(x8(this),this.N("remotePlayerChange")):this.Ek(null)};
g.h.Vs=function(){w8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.GI=function(){var a=d8();a&&p8(this,a)};
g.h.Hb=function(a){h7("CP",a)};g.t(z8,g.P);g.h=z8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ea(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ea(k)&&(l.currentIndex=k);c&&(this.Oa.listId=c);this.Oa.videoId=d;this.Oa.index=k||0;this.Oa.state=3;k8(this.Oa,m);this.o="UNSUPPORTED";A8("Connecting with setPlaylist and params: "+g.Kg(l));this.g.connect({method:"setPlaylist",
params:g.Kg(l)},a,O5())}else A8("Connecting without params"),this.g.connect({},a,O5());Oqa(this)};
g.h.dispose=function(){this.ea()||(this.N("beforeDispose"),B8(this,3));g.P.prototype.dispose.call(this)};
g.h.U=function(){C8(this);E8(this);D8(this);g.Kp(this.C);this.C=NaN;g.Kp(this.D);this.D=NaN;this.l=null;g.Or(this.P);this.P.length=0;this.g.dispose();g.P.prototype.U.call(this);this.o=this.A=this.i=this.Oa=this.g=null};
g.h.pD=function(){this.Oh(2)};
g.h.wI=function(){A8("Channel opened");this.I&&(this.I=!1,D8(this),this.H=g.Ip((0,g.x)(function(){A8("Timing out waiting for a screen.");this.Oh(1)},this),15E3));
pqa(wqa(this.g),this.M)};
g.h.tI=function(){A8("Channel closed");isNaN(this.u)?R5(!0):R5();this.dispose()};
g.h.uI=function(a){R5();isNaN(this.Jj())?(A8("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,A8("Channel error: "+a+" with reconnection in "+this.Jj()+" ms"),B8(this,2))};
g.h.vI=function(a){a.params?A8("Received: action="+a.action+", params="+g.Kg(a.params)):A8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=v5(a.params.devices);this.i=(0,g.B)(a,function(c){return new y5(c)});
a=!!g.Ya(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
H8(this,a);break;case "loungeScreenDisconnected":g.eb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
H8(this,!1);break;case "remoteConnected":var b=new y5(v5(a.params.device));g.Ya(this.i,function(c){return b?c.id==b.id:!1})||eqa(this.i,b);
break;case "remoteDisconnected":b=new y5(v5(a.params.device));g.eb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":I8(this,a);break;case "nowPlaying":Rqa(this,a);break;case "onStateChange":J8(this,a);break;case "onAdStateChange":Sqa(this,a);break;case "onVolumeChanged":Tqa(this,a);break;case "onSubtitlesTrackChanged":Qqa(this,a);break;case "nowAutoplaying":Uqa(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.N("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":Vqa(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:A8("Unrecognized action: "+a.action)}};
g.h.kM=function(){if(this.l){var a=this.l;this.l=null;this.Oa.videoId!=a&&F8(this,"getNowPlaying")}};
g.h.fD=function(){var a=3;this.ea()||(a=0,isNaN(this.Jj())?$6(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Oh=function(a){A8("Disconnecting with "+a);C8(this);this.N("beforeDisconnect",a);1==a&&R5();Z6(this.g,a);this.dispose()};
g.h.eD=function(){var a=this.Oa;this.l&&(a=this.Oa.clone(),m8(a,this.l,a.index));return n8(a)};
g.h.yM=function(a){var b=new h8(a);b.videoId&&b.videoId!=this.Oa.videoId&&(this.l=b.videoId,g.Kp(this.C),this.C=g.Ip((0,g.x)(this.kM,this),5E3));var c=[];this.Oa.listId==b.listId&&this.Oa.videoId==b.videoId&&this.Oa.index==b.index||c.push("remoteQueueChange");this.Oa.playerState==b.playerState&&this.Oa.volume==b.volume&&this.Oa.muted==b.muted&&l8(this.Oa)==l8(b)&&g.Kg(this.Oa.g)==g.Kg(b.g)||c.push("remotePlayerChange");this.Oa.reset(a);(0,g.z)(c,function(d){this.N(d)},this)};
g.h.Vv=function(){var a=this.g.A.id,b=g.Ya(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Jj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.H)():NaN};
g.h.XC=function(){return this.o||"UNSUPPORTED"};
g.h.YC=function(){return this.A||""};
g.h.iN=function(){if(!isNaN(this.Jj())){var a=this.g.i;g.co(a.g);a.start()}};
g.h.rM=function(a,b){F8(this,a,b);G8(this)};
z8.prototype.subscribe=z8.prototype.subscribe;z8.prototype.unsubscribeByKey=z8.prototype.Lf;z8.prototype.getProxyState=z8.prototype.fD;z8.prototype.disconnect=z8.prototype.Oh;z8.prototype.getPlayerContextData=z8.prototype.eD;z8.prototype.setPlayerContextData=z8.prototype.yM;z8.prototype.getOtherConnectedRemoteId=z8.prototype.Vv;z8.prototype.getReconnectTimeout=z8.prototype.Jj;z8.prototype.getAutoplayMode=z8.prototype.XC;z8.prototype.getAutoplayVideoId=z8.prototype.YC;z8.prototype.reconnect=z8.prototype.iN;
z8.prototype.sendMessage=z8.prototype.rM;g.t(K8,l7);g.h=K8.prototype;g.h.Hd=function(a){return this.Vc.$_gs(a)};
g.h.contains=function(a){return!!this.Vc.$_c(a)};
g.h.get=function(a){return this.Vc.$_g(a)};
g.h.start=function(){this.Vc.$_st()};
g.h.add=function(a,b,c){this.Vc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Vc.$_r(a,b,c)};
g.h.fo=function(a,b,c,d){this.Vc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.i.length;a<b;++a)this.Vc.$_ubk(this.i[a]);this.i.length=0;this.Vc=null;l7.prototype.U.call(this)};
g.h.mN=function(){this.N("screenChange")};
g.h.XJ=function(){this.N("onlineScreenChange")};
y7.prototype.$_st=y7.prototype.start;y7.prototype.$_gspc=y7.prototype.nN;y7.prototype.$_gsppc=y7.prototype.qB;y7.prototype.$_c=y7.prototype.contains;y7.prototype.$_g=y7.prototype.get;y7.prototype.$_a=y7.prototype.add;y7.prototype.$_un=y7.prototype.fo;y7.prototype.$_r=y7.prototype.remove;y7.prototype.$_gs=y7.prototype.Hd;y7.prototype.$_gos=y7.prototype.pB;y7.prototype.$_s=y7.prototype.subscribe;y7.prototype.$_ubk=y7.prototype.Lf;var f9=null,e9=!1,L8=null,M8=null,b9=null,Q8=[];g.t(g9,g.D);g.h=g9.prototype;
g.h.U=function(){g.D.prototype.U.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.bz,this);this.g.unsubscribe("remotePlayerChange",this.Gk,this);this.g.unsubscribe("remoteQueueChange",this.yn,this);this.g.unsubscribe("autoplayUpNext",this.Fy,this);this.g.unsubscribe("previousNextChange",this.Yy,this);this.g.unsubscribe("nowAutoplaying",this.Uy,this);this.g.unsubscribe("autoplayDismissed",this.Ey,this);this.g=this.u=null};
g.h.Bx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(k9(this)){if(!r8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==r8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Rj(c[0],c[1]);break;case "control_subtitles_set_track":l9(this,c[0]);break;case "control_set_audio_track":c=c[0],k9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();m9(this,0==c?void 0:c);break;case "control_seek":m9(this,c[0]);break;case "control_subtitles_set_track":l9(this,c[0]);break;case "control_set_audio_track":c=c[0],k9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.qI=function(a){this.I.lD(a)};
g.h.TM=function(a){this.Bx("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.EA=function(){var a=this.i.getOption("captions","track");g.Yb(a)||l9(this,a)};
g.h.Qy=function(a){if(k9(this)){this.g.unsubscribe("remotePlayerChange",this.Gk,this);var b=Math.round(a.volume);a=!!a.muted;var c=r8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.Gk,this)}};
g.h.rJ=function(){g.Yb(this.C)||n9(this,this.C);this.D=!1};
g.h.bz=function(a,b){this.A.stop();2==b&&this.DA()};
g.h.Gk=function(){if(k9(this)){this.o.stop();var a=r8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Lm=1;break;case 1082:case 1083:this.u.Lm=0;break;default:this.u.Lm=-1}switch(a.playerState){case 1081:case 1:i9(this,new g.iC(8));this.CA();break;case 1085:case 3:i9(this,new g.iC(9));break;case 1083:case 0:i9(this,new g.iC(2));this.H.stop();h9(this,this.i.getVideoData().lengthSeconds);break;case 1084:i9(this,new g.iC(4));break;case 2:i9(this,new g.iC(4));h9(this,l8(a));
break;case -1:i9(this,new g.iC(64));break;case -1E3:i9(this,new g.iC(128,{errorCode:"mdx.remoteerror",message:"\u0e27\u0e34\u0e14\u0e35\u0e42\u0e2d\u0e19\u0e35\u0e49\u0e44\u0e21\u0e48\u0e2a\u0e32\u0e21\u0e32\u0e23\u0e16\u0e40\u0e25\u0e48\u0e19\u0e23\u0e30\u0e22\u0e30\u0e44\u0e01\u0e25\u0e44\u0e14\u0e49"}))}a=r8(this.g).g;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,n9(this,a));a=r8(this.g);-1==a.volume||
Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.cB()}else j9(this)};
g.h.Yy=function(){this.i.N("mdxpreviousnextchange")};
g.h.yn=function(){k9(this)||j9(this)};
g.h.rC=function(){this.g.kv()};
g.h.Fy=function(a){a&&(a=g.Fq("/watch_queue_ajax",{method:"GET",Dc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.yL,this)}))&&(this.M=(0,g.x)(a.abort,a))};
g.h.yL=function(a,b){var c=new g.VA(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Uy=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.Ey=function(){this.i.N("mdxautoplaycanceled")};
g.h.NF=function(a,b){-1==r8(this.g).playerState?m9(this,a):b&&this.g.seekTo(a)};
g.h.cB=function(){if(k9(this)){var a=r8(this.g);this.l.Ka(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.Qy)}};
g.h.CA=function(){this.o.stop();if(!this.g.ea()){var a=r8(this.g);1==a.playerState&&i9(this,new g.iC(8));h9(this,l8(a));this.o.start()}};
g.h.DA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(p9,g.W);p9.prototype.o=function(){x5("mdx-privacy-popup-cancel");this.l.hide()};
p9.prototype.A=function(){x5("mdx-privacy-popup-confirm");this.l.hide()};g.t(r9,g.W);r9.prototype.u=function(a){q9(this,a.state)};g.t(s9,g.GT);s9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.ub(a,this.A,this),g.HT(this,(0,g.B)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.se(this.A(a)),this.enable(!0)):this.enable(!1)};
s9.prototype.A=function(a){return a.key};
s9.prototype.re=function(a){return"cast-selector-receiver"==a?"\u0e41\u0e04\u0e2a\u0e15\u0e4c...":this.F[a].name};
s9.prototype.Ic=function(a){g.GT.prototype.Ic.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.ib()};g.t(t9,g.zK);g.h=t9.prototype;
g.h.create=function(){$qa(g.Fy(g.X(this.player)));this.o.push(g.Pp("yt-remote-before-disconnect",this.nI,this));this.o.push(g.Pp("yt-remote-connection-change",this.BK,this));this.o.push(g.Pp("yt-remote-receiver-availability-change",this.Zy,this));this.o.push(g.Pp("yt-remote-auto-connect",this.zK,this));this.o.push(g.Pp("yt-remote-receiver-resumed",this.yK,this));this.o.push(g.Pp("mdx-privacy-popup-confirm",this.aM,this));this.o.push(g.Pp("mdx-privacy-popup-cancel",this.ZL,this));this.Zy()};
g.h.load=function(){this.player.cancelPlayback();g.zK.prototype.load.call(this);this.u=new g9(this,this.player,this.g);var a=(a=d9())?a.currentTime:0;var b=a9()?new q8(W8(),void 0):null;0==a&&b&&(a=l8(r8(b)));0!=a&&this.Kc(a);o9(this,this.pk,this.pk);g.GX(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.rf(this.u,this.g);this.g=this.u=null;g.zK.prototype.unload.call(this);g.GX(this.player.app,5)};
g.h.U=function(){g.Qp(this.o);g.zK.prototype.U.call(this)};
g.h.Xe=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.Bx.apply(this.u,[a].concat(g.fa(c)))};
g.h.getAdState=function(){return this.Lm};
g.h.hD=function(){return this.loaded?this.u.suggestion:null};
g.h.Je=function(){return this.g?r8(this.g).Je:!1};
g.h.hasNext=function(){return this.g?r8(this.g).hasNext:!1};
g.h.Kc=function(a,b){this.H=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.H};
g.h.getProgressState=function(){var a=r8(this.g),b=this.player.getVideoData();return{allowSeeking:g.Q(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.dc():!a.isAdPlaying()&&this.player.dc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+j8(a):a.l,isAtLiveHead:1>=(a.u?a.i+j8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+j8(a):a.i,seekableStart:0<a.o?a.o+
j8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.En=function(){this.g&&this.g.En()};
g.h.nI=function(a){1==a&&(this.C=this.g?r8(this.g):null)};
g.h.BK=function(){var a=a9()?new q8(W8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.C=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.qf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.C)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,l8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Zy=function(){this.A=[this.i].concat(ara());var a=X8()||this.i;u9(this,a);this.player.la("onMdxReceiversChange")};
g.h.zK=function(){var a=X8();u9(this,a)};
g.h.yK=function(){this.l=X8()};
g.h.aM=function(){this.D=!0;e9=!1;f9&&Z8(f9,1);f9=null};
g.h.ZL=function(){this.D=!1;u9(this,this.i);this.l=this.i;e9=!1;f9=null;this.player.playVideo()};
g.h.xc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?f8():u9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&f8(),!0):!1}};
g.h.Vs=function(){this.g.Vs()};
g.h.Lb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.XU.remote=t9;})(_yt_player);
